"""Algorithm track lesson guides."""

LESSONS = [
    {
        "slug": "01_two_pointers",
        "track": "algorithms",
        "difficulty": "easy",
        "title": "Two Pointers",
        "tags": ["two-pointers", "array"],
        "exercise": "content/problems/algorithms/easy/01_two_sum_sorted.py",
        "body": (
            "# Two Pointers Technique\n\n"
            "## Overview\n\n"
            "The two-pointer technique replaces nested loops with two indices that move "
            "through data in a single pass. On sorted arrays it often turns O(n²) brute "
            "force into O(n).\n\n"
            "**Why does it work?** Each pointer move eliminates an entire class of "
            "impossible answers. Instead of checking every pair with nested loops, "
            "you use structure in the data (usually sorted order) to skip combinations "
            "you know will fail.\n\n"
            "Picture two fingers walking inward on a sorted number line. When the sum is "
            "too small, you cannot fix it by moving the right finger left — you need a "
            "bigger left value. That single observation removes many pairs at once.\n\n"
            "## When to use it\n\n"
            "- Input is sorted (or sorting is allowed)\n"
            "- You need a pair, triple, or contiguous range matching a rule\n"
            "- You compare from both ends (converging) or scan together (fast/slow)\n"
            "- Problem asks for \"in place\" modification with O(1) extra space\n\n"
            "## Prerequisites\n\n"
            "Comfort with loops, indexing, and basic big-O notation. You should be able "
            "to trace how `left` and `right` change step by step on paper.\n\n"
            "## Converging pointers\n\n"
            "Place one index at each end and move inward based on a comparison:\n\n"
            "```python\n"
            "def two_sum_sorted(nums, target):\n"
            "    left, right = 0, len(nums) - 1\n"
            "    while left < right:\n"
            "        total = nums[left] + nums[right]\n"
            "        if total == target:\n"
            "            return [left, right]\n"
            "        elif total < target:\n"
            "            left += 1\n"
            "        else:\n"
            "            right -= 1\n"
            "    return [-1, -1]\n"
            "```\n\n"
            "### Why it works\n\n"
            "On a sorted array, if the sum is too small, every pair involving `nums[left]` "
            "with indices `< right` is also too small — so increment `left`. If the sum is "
            "too large, decrement `right` for the symmetric reason.\n\n"
            "You never discard the correct answer because:\n\n"
            "- If `nums[left] + nums[right] > target`, then `nums[left] + nums[right - 1]`, "
            "`nums[left] + nums[right - 2]`, etc. are all too large — safe to shrink `right`\n"
            "- The mirror argument applies when the sum is too small\n\n"
            "Check if a pair sums to at least a minimum:\n\n"
            "```python\n"
            "def has_pair_at_least(nums, target):\n"
            "    left, right = 0, len(nums) - 1\n"
            "    while left < right:\n"
            "        if nums[left] + nums[right] >= target:\n"
            "            return True\n"
            "        left += 1\n"
            "    return False\n"
            "```\n\n"
            "## Worked example: two-sum on sorted array\n\n"
            "`nums = [1, 3, 4, 6, 8]`, target `7`:\n\n"
            "| Step | left | right | nums[left] | nums[right] | sum | Action        |\n"
            "|------|------|-------|------------|-------------|-----|---------------|\n"
            "| 1    | 0    | 4     | 1          | 8           | 9   | too big → right-- |\n"
            "| 2    | 0    | 3     | 1          | 6           | 7   | found! return [0, 3] |\n\n"
            "**Output:** `[0, 3]` because `nums[0] + nums[3] = 1 + 6 = 7`.\n\n"
            "**Why not check all pairs?** Five elements → 10 pairs with brute force. "
            "Two pointers checked only 2 pairs because sorting let us eliminate candidates.\n\n"
            "Another input: `nums = [2, 3, 5, 8]`, target `10`:\n\n"
            "| Step | left | right | sum | Action |\n"
            "|------|------|-------|-----|--------|\n"
            "| 1    | 0    | 3     | 10  | found [0, 3] |\n\n"
            "Target `100` on the same array → pointers cross with no match → `[-1, -1]`.\n\n"
            "## Worked example: palindrome check\n\n"
            "```python\n"
            "def is_palindrome(s):\n"
            "    left, right = 0, len(s) - 1\n"
            "    while left < right:\n"
            "        if s[left] != s[right]:\n"
            "            return False\n"
            "        left += 1\n"
            "        right -= 1\n"
            "    return True\n"
            "```\n\n"
            "**Input:** `s = \"racecar\"`\n\n"
            "- Compare `r` vs `r` → match, move inward\n"
            "- Compare `a` vs `a` → match\n"
            "- Continue until `left >= right`\n"
            "- **Output:** `True`\n\n"
            "**Input:** `s = \"hello\"` → compare `h` vs `o` → mismatch → **Output:** `False`\n\n"
            "**Input:** `s = \"abba\"` → compare `a`/`a`, then `b`/`b` → **Output:** `True`\n\n"
            "**Why converging pointers?** Palindrome symmetry means the outer characters "
            "must match first. If they fail, inner characters do not matter.\n\n"
            "## Same-direction (fast/slow)\n\n"
            "Both pointers start at the left and move forward:\n\n"
            "```python\n"
            "def remove_duplicates(nums):\n"
            "    if not nums:\n"
            "        return 0\n"
            "    slow = 0\n"
            "    for fast in range(1, len(nums)):\n"
            "        if nums[fast] != nums[slow]:\n"
            "            slow += 1\n"
            "            nums[slow] = nums[fast]\n"
            "    return slow + 1  # new length\n"
            "```\n\n"
            "**Input:** `nums = [1, 1, 2, 2, 3]`\n\n"
            "| fast | slow | nums (relevant prefix) |\n"
            "|------|------|------------------------|\n"
            "| 1    | 0    | [1, 1, ...]            |\n"
            "| 2    | 1    | [1, 2, ...]            |\n"
            "| 3    | 1    | [1, 2, 2, ...]         |\n"
            "| 4    | 2    | [1, 2, 3, ...]         |\n\n"
            "**Output:** length `3`, first three elements `[1, 2, 3]`.\n\n"
            "**Why fast/slow?** `slow` marks the write position for the deduplicated prefix; "
            "`fast` scans ahead. Each element is visited once → O(n).\n\n"
            "Move zeros to the end (stable relative order):\n\n"
            "```python\n"
            "def move_zeroes(nums):\n"
            "    slow = 0\n"
            "    for fast in range(len(nums)):\n"
            "        if nums[fast] != 0:\n"
            "            nums[slow], nums[fast] = nums[fast], nums[slow]\n"
            "            slow += 1\n"
            "```\n\n"
            "**Input:** `[0, 1, 0, 3, 12]` → **Output:** `[1, 3, 12, 0, 0]`\n\n"
            "Other same-direction uses:\n\n"
            "- **Container with most water**: converging pointers, move the shorter line\n"
            "- **Merge sorted arrays**: compare heads, advance the smaller side\n"
            "- **Partition arrays**: Dutch national flag (three pointers)\n\n"
            "## Worked example: merge two sorted lists (concept)\n\n"
            "```python\n"
            "def merge_sorted(a, b):\n"
            "    i = j = 0\n"
            "    out = []\n"
            "    while i < len(a) and j < len(b):\n"
            "        if a[i] <= b[j]:\n"
            "            out.append(a[i])\n"
            "            i += 1\n"
            "        else:\n"
            "            out.append(b[j])\n"
            "            j += 1\n"
            "    out.extend(a[i:])\n"
            "    out.extend(b[j:])\n"
            "    return out\n"
            "```\n\n"
            "**Input:** `a = [1, 3, 5]`, `b = [2, 4]` → **Output:** `[1, 2, 3, 4, 5]`\n\n"
            "**Why two pointers instead of concatenating and sorting?** Merging sorted "
            "lists is O(n + m). Sorting the combined list would be O((n+m) log(n+m)).\n\n"
            "## Common pitfalls\n\n"
            "- Using converging two-sum on unsorted data without sorting first\n"
            "- Off-by-one: `left < right` vs `left <= right` changes whether pairs repeat\n"
            "- Forgetting empty or single-element inputs\n"
            "- Moving the wrong pointer — always justify each move with the sorted-order argument\n"
            "- Sorting when the problem forbids it (check constraints first)\n\n"
            "## Complexity\n\n"
            "- Time: O(n) per pass (each pointer moves at most n steps)\n"
            "- Space: O(1) for the pointer variables\n"
            "- If you sort first: O(n log n) time for sort + O(n) for two pointers\n\n"
            "## Practice\n\n"
            "Open the linked exercise and implement two-sum on a sorted array.\n\n"
            "```python\n"
            "two_sum_sorted([1, 3, 4, 6, 8], 7)  # [0, 3]\n"
            "```\n\n"
            "## Cheat sheet\n\n"
            "| Pattern      | Move rule              | Example problems   |\n"
            "|--------------|------------------------|--------------------|\n"
            "| Converging   | shrink from wrong side | two-sum, palindrome|\n"
            "| Fast/slow    | both forward           | dedupe, partition  |"
        ),
    },
    {
        "slug": "02_sliding_window",
        "track": "algorithms",
        "difficulty": "medium",
        "title": "Sliding Window",
        "tags": ["sliding-window"],
        "exercise": "content/problems/algorithms/medium/03_longest_substring_without_repeating.py",
        "body": (
            "# Sliding Window\n\n"
            "## Overview\n\n"
            "A sliding window tracks a contiguous range `[left, right]` in a string or array. "
            "You expand the window by advancing `right`, and shrink from `left` when a "
            "constraint breaks. Many substring/subarray problems become O(n) instead of O(n²).\n\n"
            "**Why not check every substring?** A string of length n has O(n²) substrings. "
            "Brute force rechecks overlapping regions repeatedly. A sliding window reuses "
            "work from the previous step — each element enters and leaves the window at most once.\n\n"
            "Imagine a fixed-size frame sliding along a timeline. Instead of recomputing "
            "the whole sum inside the frame from scratch each step, you add the new entry "
            "and drop the one that left.\n\n"
            "## When to use it\n\n"
            "- \"Longest/shortest substring/subarray where …\"\n"
            "- Fixed-size window of length k (moving average, max in window)\n"
            "- Running sum or frequency counts over a range\n"
            "- Contiguous subarray with a sum/count constraint\n\n"
            "## Fixed vs variable window\n\n"
            "**Fixed size k**: maintain a sum or deque of the last k elements; slide one step "
            "at a time.\n\n"
            "**Variable size**: grow `right` until invalid, then shrink `left` until valid again.\n\n"
            "**Why two flavors?** Fixed-k problems always know the window width. Variable "
            "problems hunt for the best length that still satisfies a rule.\n\n"
            "## Template: longest substring without repeats\n\n"
            "```python\n"
            "def length_of_longest_substring(s):\n"
            "    left = 0\n"
            "    best = 0\n"
            "    seen = set()\n"
            "    for right, ch in enumerate(s):\n"
            "        while ch in seen:\n"
            "            seen.remove(s[left])\n"
            "            left += 1\n"
            "        seen.add(ch)\n"
            "        best = max(best, right - left + 1)\n"
            "    return best\n"
            "```\n\n"
            "**Why `while` not `if`?** A single shrink step may not be enough. If `left` "
            "skips duplicate characters, you may need multiple removals before `ch` is safe to add.\n\n"
            "**Why `right - left + 1`?** Both endpoints are inclusive. A window from index 2 "
            "to 4 has length `4 - 2 + 1 = 3`.\n\n"
            "Frequency-map variant (allows at most k duplicates):\n\n"
            "```python\n"
            "def longest_with_k_distinct(s, k):\n"
            "    left = 0\n"
            "    counts = {}\n"
            "    best = 0\n"
            "    for right, ch in enumerate(s):\n"
            "        counts[ch] = counts.get(ch, 0) + 1\n"
            "        while len(counts) > k:\n"
            "            left_ch = s[left]\n"
            "            counts[left_ch] -= 1\n"
            "            if counts[left_ch] == 0:\n"
            "                del counts[left_ch]\n"
            "            left += 1\n"
            "        best = max(best, right - left + 1)\n"
            "    return best\n"
            "```\n\n"
            "## Worked example: longest unique substring\n\n"
            "**Input:** `s = \"abcabcbb\"`\n\n"
            "| right | ch | seen after add | action on duplicate | left | window  | best |\n"
            "|-------|----|----------------|---------------------|------|---------|------|\n"
            "| 0     | a  | {a}            | —                   | 0    | \"a\"     | 1    |\n"
            "| 1     | b  | {a,b}          | —                   | 0    | \"ab\"    | 2    |\n"
            "| 2     | c  | {a,b,c}        | —                   | 0    | \"abc\"   | 3    |\n"
            "| 3     | a  | —              | shrink until a gone | 1    | \"bca\"   | 3    |\n"
            "| 4     | b  | —              | shrink until b gone | 2    | \"cab\"   | 3    |\n"
            "| 5     | c  | —              | shrink until c gone | 3    | \"abc\"   | 3    |\n"
            "| 6     | b  | —              | shrink              | 4    | \"cb\"    | 3    |\n"
            "| 7     | b  | —              | shrink              | 5    | \"b\"     | 3    |\n\n"
            "**Output:** `3` (windows like `\"abc\"`, `\"bca\"`, `\"cab\"` all have length 3).\n\n"
            "**Input:** `s = \"bbbbb\"` → best window `\"bbb\"` but unique chars force length `1` "
            "at any time → **Output:** `1`.\n\n"
            "## Worked example: max sum subarray of size k\n\n"
            "**Input:** `arr = [2, 1, 5, 1, 3, 2]`, `k = 3`\n\n"
            "```python\n"
            "def max_sum_fixed_window(arr, k):\n"
            "    window_sum = sum(arr[:k])\n"
            "    best = window_sum\n"
            "    for right in range(k, len(arr)):\n"
            "        window_sum += arr[right] - arr[right - k]\n"
            "        best = max(best, window_sum)\n"
            "    return best\n"
            "```\n\n"
            "**Step-by-step:**\n\n"
            "- Initial window `[2, 1, 5]` → sum = 8, best = 8\n"
            "- Slide right: add `arr[3]=1`, subtract `arr[0]=2` → sum = 7\n"
            "- Slide: add `arr[4]=3`, subtract `arr[1]=1` → sum = 9, best = 9\n"
            "- Slide: add `arr[5]=2`, subtract `arr[2]=5` → sum = 6\n\n"
            "**Output:** `9` from window `[5, 1, 3]`.\n\n"
            "**Why subtract `arr[right - k]`?** When the window slides one step right, "
            "the leftmost element leaves. Adding the new right element and removing the "
            "old left element updates the sum in O(1).\n\n"
            "Moving average with the same pattern:\n\n"
            "```python\n"
            "def moving_average(arr, k):\n"
            "    window_sum = sum(arr[:k])\n"
            "    averages = [window_sum / k]\n"
            "    for right in range(k, len(arr)):\n"
            "        window_sum += arr[right] - arr[right - k]\n"
            "        averages.append(window_sum / k)\n"
            "    return averages\n"
            "```\n\n"
            "**Input:** `arr = [1, 2, 3, 4]`, `k = 2` → **Output:** `[1.5, 2.5, 3.5]`\n\n"
            "## Variable window: sum at most target\n\n"
            "```python\n"
            "def min_subarray_len(target, nums):\n"
            "    left = 0\n"
            "    window_sum = 0\n"
            "    best = float('inf')\n"
            "    for right, num in enumerate(nums):\n"
            "        window_sum += num\n"
            "        while window_sum >= target:\n"
            "            best = min(best, right - left + 1)\n"
            "            window_sum -= nums[left]\n"
            "            left += 1\n"
            "    return 0 if best == float('inf') else best\n"
            "```\n\n"
            "**Input:** `target = 7`, `nums = [2, 3, 1, 2, 4, 3]`\n\n"
            "| right | num | window_sum | left | window      | best len |\n"
            "|-------|-----|------------|------|-------------|----------|\n"
            "| 0     | 2   | 2          | 0    | [2]         | inf      |\n"
            "| 1     | 3   | 5          | 0    | [2,3]       | inf      |\n"
            "| 2     | 1   | 6          | 0    | [2,3,1]     | inf      |\n"
            "| 3     | 2   | 8          | 0→1  | shrink/grow | 4        |\n"
            "| ...   |     |            |      |             |          |\n"
            "| 5     | 3   | 7          | 4    | [4,3]       | 2        |\n\n"
            "**Output:** `2` (subarray `[4, 3]`).\n\n"
            "**Why shrink while `window_sum >= target`?** We want the **shortest** valid "
            "window. Once valid, tightening from the left might still leave a valid window "
            "with smaller length.\n\n"
            "## Maintaining the invariant\n\n"
            "Write down what must always be true inside the window:\n\n"
            "- All characters unique\n"
            "- Sum ≥ target (or ≤ target for maximum-length problems)\n"
            "- At most k distinct characters\n"
            "- No zeros in the window (for product problems)\n\n"
            "The inner `while` restores the invariant after each expansion.\n\n"
            "**Why write the invariant first?** It tells you whether to use `if` or `while`, "
            "when to update `best`, and what data structure (set, dict, running sum) to maintain.\n\n"
            "Count subarrays with exactly k odd numbers (advanced pattern):\n\n"
            "```python\n"
            "# Idea: at_most(k) - at_most(k-1)\n"
            "# Build at_most by sliding window on odd count\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Shrinking with `if` instead of `while` when multiple steps are needed\n"
            "- Updating the answer before the window is valid again\n"
            "- Using O(n) work inside each shrink (use a frequency map or running sum)\n"
            "- Off-by-one in window length: `right - left + 1` includes both endpoints\n"
            "- Forgetting to handle empty input or `k > len(arr)` in fixed windows\n\n"
            "```python\n"
            "# Bug: missing closing paren (always verify your max/min line)\n"
            "best = max(best, right - left + 1)  # correct\n"
            "```\n\n"
            "## Complexity\n\n"
            "Each index enters and leaves the window at most once → O(n) time, O(k) space "
            "for auxiliary structures (set, dict, or deque of size at most k).\n\n"
            "## Practice\n\n"
            "Implement longest substring without repeating characters using the template above.\n\n"
            "```python\n"
            "length_of_longest_substring('abcabcbb')  # 3\n"
            "length_of_longest_substring('pwwkew')    # 3 ('wke')\n"
            "```\n\n"
            "## Related patterns\n\n"
            "- **Prefix sums** when the window rule involves arbitrary range sums\n"
            "- **Monotonic deque** for \"max in sliding window of size k\" in O(n)"
        ),
    },
    {
        "slug": "03_stacks",
        "track": "algorithms",
        "difficulty": "easy",
        "title": "Stacks for Parsing",
        "tags": ["stack"],
        "exercise": "content/problems/algorithms/easy/11_valid_parentheses.py",
        "body": (
            "# Stacks for Parsing and Matching\n\n"
            "## Overview\n\n"
            "A stack is last-in, first-out (LIFO). Python lists with `.append()` and `.pop()` "
            "make a perfect stack. Use one whenever the problem involves nesting, matching "
            "pairs, or \"undo the most recent\" logic.\n\n"
            "**Why LIFO?** The most recently opened bracket must close first — exactly "
            "like a stack of plates. The last item you push is the first one you pop.\n\n"
            "Stacks appear in browsers (back button), undo editors, call stacks during "
            "recursion, and syntax parsers. If the problem says \"most recent unmatched\", "
            "think stack.\n\n"
            "## When to use a stack\n\n"
            "- Valid parentheses / HTML tags / bracket matching\n"
            "- Evaluate postfix or prefix expressions\n"
            "- Next greater/smaller element (monotonic stack variant)\n"
            "- DFS on trees/graphs (explicit stack or recursion call stack)\n"
            "- Undo operations, browser back button, syntax parsing\n\n"
            "## Valid parentheses template\n\n"
            "```python\n"
            "def is_valid(s):\n"
            "    pairs = {')': '(', ']': '[', '}': '{'}\n"
            "    stack = []\n"
            "    for ch in s:\n"
            "        if ch in '([{':\n"
            "            stack.append(ch)\n"
            "        elif ch in ')]}':\n"
            "            if not stack or stack.pop() != pairs[ch]:\n"
            "                return False\n"
            "    return not stack\n"
            "```\n\n"
            "Openers push; closers must match the most recent opener.\n\n"
            "**Why map closers to openers?** When you see `)`, you need to know the "
            "expected opener is `(`. The dict makes that lookup O(1).\n\n"
            "**Why `return not stack`?** A leftover opener like `'('` means the string "
            "ended before everything closed.\n\n"
            "Only brackets, ignore other characters:\n\n"
            "```python\n"
            "def is_valid_ignore_noise(s):\n"
            "    pairs = {')': '(', ']': '[', '}': '{'}\n"
            "    stack = []\n"
            "    for ch in s:\n"
            "        if ch in '([{':\n"
            "            stack.append(ch)\n"
            "        elif ch in ')]}':\n"
            "            if not stack or stack.pop() != pairs[ch]:\n"
            "                return False\n"
            "        # else: ignore letters, digits, spaces\n"
            "    return not stack\n"
            "```\n\n"
            "## Worked trace: valid string\n\n"
            "`s = \"({[]})\"`:\n\n"
            "| ch | action        | stack after   |\n"
            "|----|---------------|---------------|\n"
            "| (  | push          | ['(']         |\n"
            "| {  | push          | ['(', '{']    |\n"
            "| [  | push          | ['(', '{', '[']|\n"
            "| ]  | pop, matches [| ['(', '{']     |\n"
            "| }  | pop, matches { | ['(']         |\n"
            "| )  | pop, matches ( | []            |\n\n"
            "Stack empty at end → **Output:** `True`\n\n"
            "## Worked trace: invalid strings\n\n"
            "`s = \"(]\"`:\n\n"
            "- `(` push → stack `['(']`\n"
            "- `]` pop → top is `'('` but `pairs[']']` is `'['` → mismatch\n"
            "- **Output:** `False`\n\n"
            "`s = \"(()\"`:\n\n"
            "- Process all chars → stack `['(']` not empty\n"
            "- **Output:** `False` (unclosed opener)\n\n"
            "`s = \")(\"`:\n\n"
            "- `)` seen with empty stack → **Output:** `False` immediately\n\n"
            "## Reverse a string with a stack\n\n"
            "```python\n"
            "def reverse_string(s):\n"
            "    stack = list(s)\n"
            "    out = []\n"
            "    while stack:\n"
            "        out.append(stack.pop())\n"
            "    return ''.join(out)\n"
            "```\n\n"
            "**Input:** `'stack'` → **Output:** `'kcats'`\n\n"
            "**Why a stack for reversal?** Pop order is opposite of push order — LIFO "
            "naturally reverses a sequence.\n\n"
            "## Evaluate postfix notation\n\n"
            "```python\n"
            "def eval_postfix(tokens):\n"
            "    stack = []\n"
            "    ops = {'+', '-', '*', '/'}\n"
            "    for tok in tokens:\n"
            "        if tok not in ops:\n"
            "            stack.append(int(tok))\n"
            "        else:\n"
            "            b, a = stack.pop(), stack.pop()\n"
            "            if tok == '+': stack.append(a + b)\n"
            "            elif tok == '-': stack.append(a - b)\n"
            "            elif tok == '*': stack.append(a * b)\n"
            "            else: stack.append(a // b)\n"
            "    return stack[0]\n"
            "```\n\n"
            "**Input:** `tokens = ['2', '3', '+', '4', '*']`\n\n"
            "- Push 2, push 3 → stack `[2, 3]`\n"
            "- `+` → pop 3, 2 → push 5 → `[5]`\n"
            "- Push 4 → `[5, 4]`\n"
            "- `*` → pop 4, 5 → push 20 → `[20]`\n\n"
            "**Output:** `20` (because `(2 + 3) * 4 = 20`)\n\n"
            "**Input:** `['4', '13', '5', '/', '+']` → `4 + (13 // 5) = 4 + 2 = 6`\n\n"
            "**Why a stack?** Operators apply to the most recent operands — LIFO again.\n\n"
            "**Why pop `b` then `a`?** For subtraction and division, order matters: "
            "`a - b`, not `b - a`.\n\n"
            "## Monotonic stack (preview)\n\n"
            "Find how many days until a warmer temperature:\n\n"
            "```python\n"
            "def daily_temperatures(temps):\n"
            "    n = len(temps)\n"
            "    answer = [0] * n\n"
            "    stack = []  # indices of decreasing temperatures\n"
            "    for i, temp in enumerate(temps):\n"
            "        while stack and temps[stack[-1]] < temp:\n"
            "            prev = stack.pop()\n"
            "            answer[prev] = i - prev\n"
            "        stack.append(i)\n"
            "    return answer\n"
            "```\n\n"
            "**Input:** `temps = [73, 74, 75, 71, 69, 72, 76, 73]`\n\n"
            "**Output:** `[1, 1, 4, 2, 1, 1, 0, 0]`\n\n"
            "**Trace for index 0 (73°):** Next warmer day is index 1 (74°) → wait 1 day.\n\n"
            "When a warmer day arrives, pop colder days from the stack and record "
            "distances. Each index is pushed and popped at most once → O(n).\n\n"
            "**Why monotonic?** Stack temperatures stay in decreasing order. A warmer day "
            "resolves all colder pending days stacked below it.\n\n"
            "Next greater element for each position:\n\n"
            "```python\n"
            "def next_greater(nums):\n"
            "    result = [-1] * len(nums)\n"
            "    stack = []\n"
            "    for i, n in enumerate(nums):\n"
            "        while stack and nums[stack[-1]] < n:\n"
            "            result[stack.pop()] = n\n"
            "        stack.append(i)\n"
            "    return result\n"
            "```\n\n"
            "**Input:** `[2, 1, 2, 4, 3]` → **Output:** `[4, 2, 4, -1, -1]`\n\n"
            "## Common pitfalls\n\n"
            "- Forgetting to check stack empty before pop (causes `IndexError`)\n"
            "- Returning True when stack still has openers at the end\n"
            "- Confusing stack with queue (FIFO) for BFS problems\n"
            "- Popping operands in wrong order for non-commutative ops (`a - b` vs `b - a`)\n"
            "- Using `stack.pop(0)` — that is queue behavior and is O(n) on lists\n\n"
            "## Complexity\n\n"
            "One push/pop per character or element → O(n) time, O(n) space worst case "
            "(when input is all openers like `\"((((\"`).\n\n"
            "## Practice\n\n"
            "Implement valid parentheses, then try daily temperatures (monotonic stack).\n\n"
            "```python\n"
            "is_valid('()[]{}')  # True\n"
            "is_valid('(]')      # False\n"
            "```\n\n"
            "## Summary\n\n"
            "Stack = \"most recent unmatched item.\" If your problem sounds like nesting, "
            "matching, or undo, reach for a stack first."
        ),
    },
    {
        "slug": "04_binary_search",
        "track": "algorithms",
        "difficulty": "easy",
        "title": "Binary Search",
        "tags": ["binary-search"],
        "exercise": "content/problems/algorithms/easy/16_binary_search.py",
        "body": (
            "# Binary Search\n\n"
            "## Overview\n\n"
            "Binary search halves the search space each step on **sorted** data. "
            "It finds a target in O(log n) comparisons instead of O(n) linear scan.\n\n"
            "**Why O(log n)?** Each comparison eliminates half the remaining elements. "
            "For 1,000,000 items you need at most ~20 comparisons, not 1,000,000.\n\n"
            "Binary search is not just for arrays — any time you can ask \"is the answer "
            "too big or too small?\" and get a monotonic yes/no, you can binary search "
            "the answer space.\n\n"
            "## When to use it\n\n"
            "- Sorted array lookup\n"
            "- \"Find minimum value that satisfies X\" (answer space search)\n"
            "- Rotated sorted array, first/last occurrence\n"
            "- Any monotonic predicate: once `f(x)` flips from False to True, binary search applies\n\n"
            "## Classic template\n\n"
            "```python\n"
            "def binary_search(nums, target):\n"
            "    lo, hi = 0, len(nums) - 1\n"
            "    while lo <= hi:\n"
            "        mid = (lo + hi) // 2\n"
            "        if nums[mid] == target:\n"
            "            return mid\n"
            "        elif nums[mid] < target:\n"
            "            lo = mid + 1\n"
            "        else:\n"
            "            hi = mid - 1\n"
            "    return -1\n"
            "```\n\n"
            "Linear scan for comparison:\n\n"
            "```python\n"
            "def linear_search(nums, target):\n"
            "    for i, n in enumerate(nums):\n"
            "        if n == target:\n"
            "            return i\n"
            "    return -1\n"
            "```\n\n"
            "**Why binary wins on big sorted data:** 1M elements → ~20 steps vs up to 1M.\n\n"
            "## Worked example: find target\n\n"
            "**Input:** `nums = [1, 3, 5, 7, 9, 11]`, `target = 7`\n\n"
            "| step | lo | hi | mid | nums[mid] | action      |\n"
            "|------|----|----|-----|-----------|-------------|\n"
            "| 1    | 0  | 5  | 2   | 5         | 5 < 7 → lo=3 |\n"
            "| 2    | 3  | 5  | 4   | 11        | 11 > 7 → hi=3|\n"
            "| 3    | 3  | 3  | 3   | 7         | found! return 3 |\n\n"
            "**Output:** index `3`\n\n"
            "**Input:** `target = 4` → no exact match → **Output:** `-1`\n\n"
            "**Input:** `target = 1` → found at index `0` on first or second step.\n\n"
            "## Invariants\n\n"
            "Pick one template and stick to it:\n\n"
            "- **Closed interval** `[lo, hi]`: loop while `lo <= hi`, move to `mid ± 1`\n"
            "- **Half-open** `[lo, hi)`: loop while `lo < hi`, `hi = mid` or `lo = mid + 1`\n\n"
            "Mixing templates causes infinite loops or missed answers.\n\n"
            "**Why invariants matter?** They define what region still might contain the "
            "answer. If you shrink wrong, you can skip the target or loop forever.\n\n"
            "Closed-interval mental model: \"the target, if it exists, is always between "
            "`lo` and `hi` inclusive until the loop ends.\"\n\n"
            "## Find first index >= target (lower bound)\n\n"
            "```python\n"
            "def lower_bound(nums, target):\n"
            "    lo, hi = 0, len(nums)\n"
            "    while lo < hi:\n"
            "        mid = (lo + hi) // 2\n"
            "        if nums[mid] < target:\n"
            "            lo = mid + 1\n"
            "        else:\n"
            "            hi = mid\n"
            "    return lo\n"
            "```\n\n"
            "**Input:** `nums = [1, 2, 4, 4, 5]`, `target = 4`\n\n"
            "- Search narrows to first `4` at index 2\n"
            "- **Output:** `2`\n\n"
            "**Input:** `target = 6` → **Output:** `5` (insert position past end)\n\n"
            "**Why `hi = mid` not `mid - 1`?** You want the first position where "
            "`nums[mid] >= target`. When `nums[mid] == target`, the answer could still "
            "be to the left.\n\n"
            "Find last index <= target (upper bound style):\n\n"
            "```python\n"
            "def upper_bound(nums, target):\n"
            "    lo, hi = 0, len(nums)\n"
            "    while lo < hi:\n"
            "        mid = (lo + hi) // 2\n"
            "        if nums[mid] <= target:\n"
            "            lo = mid + 1\n"
            "        else:\n"
            "            hi = mid\n"
            "    return lo - 1\n"
            "```\n\n"
            "**Input:** `nums = [1, 2, 4, 4, 5]`, `target = 4` → **Output:** `3` (last 4)\n\n"
            "## Beyond arrays: search the answer space\n\n"
            "Binary search works on any monotonic predicate — not just sorted arrays:\n\n"
            "```python\n"
            "def min_capacity(weights, days):\n"
            "    # find smallest ship capacity to ship all packages in `days` days\n"
            "    lo, hi = max(weights), sum(weights)\n"
            "    while lo < hi:\n"
            "        mid = (lo + hi) // 2\n"
            "        if can_ship(weights, days, mid):\n"
            "            hi = mid\n"
            "        else:\n"
            "            lo = mid + 1\n"
            "    return lo\n"
            "```\n\n"
            "**Why search capacities?** If capacity `C` works, any capacity `> C` also works "
            "(monotonic). Binary search finds the minimum feasible value in O(log S) where "
            "S is the search range.\n\n"
            "Guess square root (integer):\n\n"
            "```python\n"
            "def int_sqrt(n):\n"
            "    lo, hi = 0, n\n"
            "    while lo < hi:\n"
            "        mid = (lo + hi + 1) // 2  # bias up to avoid infinite loop\n"
            "        if mid * mid <= n:\n"
            "            lo = mid\n"
            "        else:\n"
            "            hi = mid - 1\n"
            "    return lo\n"
            "```\n\n"
            "**Input:** `n = 8` → **Output:** `2` (since 2² ≤ 8 < 3²)\n\n"
            "## Worked example: search insert position\n\n"
            "```python\n"
            "def search_insert(nums, target):\n"
            "    lo, hi = 0, len(nums) - 1\n"
            "    while lo <= hi:\n"
            "        mid = (lo + hi) // 2\n"
            "        if nums[mid] < target:\n"
            "            lo = mid + 1\n"
            "        else:\n"
            "            hi = mid - 1\n"
            "    return lo\n"
            "```\n\n"
            "**Input:** `nums = [1, 3, 5, 6]`, `target = 2`\n\n"
            "- `nums[1] = 3 > 2` → search left half\n"
            "- Loop ends with `lo = 1`\n"
            "- **Output:** `1` (insert between 1 and 3)\n\n"
            "**Input:** `target = 7` → **Output:** `4` (append after 6)\n\n"
            "## Using bisect in production code\n\n"
            "```python\n"
            "import bisect\n\n"
            "nums = [1, 3, 5, 5, 7]\n"
            "bisect.bisect_left(nums, 5)   # 2 — first 5\n"
            "bisect.bisect_right(nums, 5)  # 4 — insert after existing 5s\n"
            "```\n\n"
            "**Why learn templates first?** Interviews and bug fixes require knowing "
            "what `bisect` is doing under the hood.\n\n"
            "## Common pitfalls\n\n"
            "- Integer overflow in other languages; Python `(lo + hi) // 2` is safe\n"
            "- Off-by-one on `<=` vs `<` in the loop condition\n"
            "- Searching unsorted data without sorting or re-framing the problem\n"
            "- Using `mid - 1` when the template calls for `mid` (loses valid answers)\n"
            "- Infinite loop when `lo = mid` without biasing `mid` upward in some templates\n\n"
            "## Complexity\n\n"
            "O(log n) time, O(1) extra space for the standard template.\n\n"
            "## Practice\n\n"
            "Implement standard binary search, then try \"search insert position\" variants.\n\n"
            "```python\n"
            "binary_search([1, 3, 5, 7, 9, 11], 7)  # 3\n"
            "search_insert([1, 3, 5, 6], 2)         # 1\n"
            "```\n\n"
            "## Cheat sheet\n\n"
            "| Goal              | Move when true     |\n"
            "|-------------------|--------------------|\n"
            "| Find exact target | compare at mid       |\n"
            "| First >= target   | hi = mid, else lo  |\n"
            "| Last <= target    | lo = mid, else hi  |"
        ),
    },
    {
        "slug": "05_dynamic_programming_intro",
        "track": "algorithms",
        "difficulty": "medium",
        "title": "Dynamic Programming Intro",
        "tags": ["dp", "memoization"],
        "exercise": "content/problems/algorithms/easy/07_climbing_stairs.py",
        "body": (
            "# Introduction to Dynamic Programming\n\n"
            "## Overview\n\n"
            "Dynamic programming (DP) solves problems with **overlapping subproblems** and "
            "**optimal substructure**. Instead of recomputing the same states, you store "
            "results in a table or cache.\n\n"
            "**Why DP?** Naive recursion on problems like Fibonacci or climbing stairs "
            "recomputes the same values exponentially many times. DP trades memory for "
            "speed by remembering answers to subproblems you've already solved.\n\n"
            "DP is not a trick — it is careful bookkeeping. Once you spot repeated "
            "subquestions, caching or tabulating them collapses exponential work to "
            "polynomial time.\n\n"
            "## When to recognize DP\n\n"
            "- Counting ways (climbing stairs, coin change)\n"
            "- Min/max cost paths\n"
            "- \"Can you partition / reach / form …?\"\n"
            "- Recursive solution explodes in branching (Fibonacci, knapsack)\n"
            "- Problem has choices at each step with optimal substructure\n\n"
            "**Key question:** If I solve a smaller version optimally, can I build the "
            "full answer from it? If yes, and subproblems repeat, DP likely applies.\n\n"
            "## Naive vs memoized: Fibonacci\n\n"
            "Naive recursion — exponential time:\n\n"
            "```python\n"
            "def fib_naive(n):\n"
            "    if n < 2:\n"
            "        return n\n"
            "    return fib_naive(n - 1) + fib_naive(n - 2)\n"
            "# fib_naive(35) already feels slow — branches recompute fib(5) many times\n"
            "```\n\n"
            "Top-down with memo — linear time:\n\n"
            "```python\n"
            "from functools import lru_cache\n\n"
            "@lru_cache(maxsize=None)\n"
            "def fib(n):\n"
            "    if n < 2:\n"
            "        return n\n"
            "    return fib(n - 1) + fib(n - 2)\n"
            "```\n\n"
            "**Concrete outputs:**\n\n"
            "```python\n"
            "fib(1)  # 1\n"
            "fib(2)  # 1\n"
            "fib(5)  # 5\n"
            "fib(10) # 55\n"
            "fib(100)  # fast with cache; naive would hang\n"
            "```\n\n"
            "**Why top-down first?** It mirrors the natural recursive definition. You can "
            "write the brute-force recursion, add `@lru_cache`, and immediately see speedup.\n\n"
            "## Top-down (memoization) — climbing stairs\n\n"
            "```python\n"
            "from functools import lru_cache\n\n"
            "@lru_cache(maxsize=None)\n"
            "def climb(n):\n"
            "    if n <= 2:\n"
            "        return n\n"
            "    return climb(n - 1) + climb(n - 2)\n"
            "```\n\n"
            "**Concrete outputs:**\n\n"
            "```python\n"
            "climb(1)  # 1\n"
            "climb(2)  # 2\n"
            "climb(3)  # 3  (1+1+1 or 1+2 or 2+1)\n"
            "climb(5)  # 8\n"
            "```\n\n"
            "Add caching to recursion; each `n` computed once → O(n) time.\n\n"
            "## Bottom-up (tabulation)\n\n"
            "```python\n"
            "def climb(n):\n"
            "    if n <= 2:\n"
            "        return n\n"
            "    prev, curr = 1, 2\n"
            "    for _ in range(3, n + 1):\n"
            "        prev, curr = curr, prev + curr\n"
            "    return curr\n"
            "```\n\n"
            "**Walkthrough for n = 5:**\n\n"
            "| step i | prev | curr | next curr |\n"
            "|--------|------|------|-----------|\n"
            "| start  | 1    | 2    | —         |\n"
            "| 3      | 2    | 3    | 2+1       |\n"
            "| 4      | 3    | 5    | 3+2       |\n"
            "| 5      | 5    | 8    | 5+3       |\n\n"
            "**Output:** `8`\n\n"
            "Fill from base cases upward. No recursion stack — often better for large n.\n\n"
            "**Why bottom-up?** You control iteration order explicitly and can often shrink "
            "the table to a few variables (`prev`, `curr`).\n\n"
            "## The DP recipe\n\n"
            "1. **Define state:** what subproblem does `dp[i]` represent?\n"
            "2. **Write recurrence:** how does `dp[i]` relate to smaller states?\n"
            "3. **Set base cases:** smallest inputs with known answers\n"
            "4. **Choose iteration order:** usually forward (small → large)\n"
            "5. **Return** `dp[target]`\n\n"
            "Skipping step 1 is the most common mistake. Write in plain English: "
            "\"`dp[i]` = number of ways to reach step i.\"\n\n"
            "## Climbing stairs example\n\n"
            "State: `ways(n)` = number of distinct ways to reach step n (1 or 2 steps at a time).\n\n"
            "Recurrence: `ways(n) = ways(n-1) + ways(n-2)`\n\n"
            "**Why?** To land on step n, you either came from step n-1 (one step) or "
            "step n-2 (two steps). Those are independent paths — add them.\n\n"
            "Base cases: `ways(1) = 1`, `ways(2) = 2`.\n\n"
            "Tabulation version:\n\n"
            "```python\n"
            "def climb_stairs(n):\n"
            "    if n <= 2:\n"
            "        return n\n"
            "    dp = [0] * (n + 1)\n"
            "    dp[1], dp[2] = 1, 2\n"
            "    for i in range(3, n + 1):\n"
            "        dp[i] = dp[i - 1] + dp[i - 2]\n"
            "    return dp[n]\n"
            "```\n\n"
            "**Input:** `n = 4` → `dp = [0,1,2,3,5]` → **Output:** `5`\n\n"
            "## Worked example: min cost path\n\n"
            "**Input:** `cost = [10, 15, 20]` (cost to step on each tile; start off array)\n\n"
            "```python\n"
            "def min_cost_climbing_stairs(cost):\n"
            "    n = len(cost)\n"
            "    dp = [0] * (n + 1)\n"
            "    # dp[i] = min cost to reach step i (top is step n)\n"
            "    for i in range(2, n + 1):\n"
            "        dp[i] = min(dp[i - 1] + cost[i - 1], dp[i - 2] + cost[i - 2])\n"
            "    return dp[n]\n"
            "```\n\n"
            "**Step-by-step:**\n\n"
            "- `dp[0] = dp[1] = 0` (free starting positions)\n"
            "- `dp[2] = min(0+10, 0+15) = 10`\n"
            "- `dp[3] = min(10+15, 0+20) = 20`\n\n"
            "**Output:** `20` (step on index 0 costing 10, then jump to top; or 1→2)\n\n"
            "**Why min of two predecessors?** You can only arrive at step `i` from "
            "`i-1` or `i-2`; pick the cheaper path.\n\n"
            "## House robber preview\n\n"
            "```python\n"
            "def rob(nums):\n"
            "    if not nums:\n"
            "        return 0\n"
            "    prev2, prev1 = 0, 0\n"
            "    for n in nums:\n"
            "        prev2, prev1 = prev1, max(prev1, prev2 + n)\n"
            "    return prev1\n"
            "```\n\n"
            "**Input:** `[2, 7, 9, 3, 1]` → rob houses 0, 2, 4 → `2 + 9 + 1 = 12`\n\n"
            "**State idea:** `dp[i]` = max money robbing houses up to index `i` without "
            "adjacent picks.\n\n"
            "## Coin change preview\n\n"
            "```python\n"
            "def coin_change(coins, amount):\n"
            "    dp = [float('inf')] * (amount + 1)\n"
            "    dp[0] = 0\n"
            "    for a in range(1, amount + 1):\n"
            "        for coin in coins:\n"
            "            if coin <= a:\n"
            "                dp[a] = min(dp[a], dp[a - coin] + 1)\n"
            "    return dp[amount] if dp[amount] != float('inf') else -1\n"
            "```\n\n"
            "**Input:** `coins = [1, 2, 5]`, `amount = 11`\n\n"
            "**Build table (selected entries):**\n\n"
            "| amount a | dp[a] | how |\n"
            "|----------|-------|-----|\n"
            "| 0        | 0     | base |\n"
            "| 1        | 1     | one 1-coin |\n"
            "| 2        | 1     | one 2-coin |\n"
            "| 3        | 2     | 2+1 |\n"
            "| 5        | 1     | one 5-coin |\n"
            "| 11       | 3     | 5+5+1 |\n\n"
            "**Output:** `3` (5 + 5 + 1)\n\n"
            "**Why unbounded knapsack flavor?** Each coin can be reused; inner loop tries "
            "every coin for each amount.\n\n"
            "**Input:** `coins = [2]`, `amount = 3` → impossible → **Output:** `-1`\n\n"
            "## Common pitfalls\n\n"
            "- Unclear state definition → wrong recurrence\n"
            "- Forgetting base cases for n=0 or n=1\n"
            "- Using O(n²) nested loops when a 1D DP suffices\n"
            "- Off-by-one in array indexing (dp size vs problem size)\n"
            "- Not initializing `dp[0]` correctly in coin change (should be 0 ways, cost 0)\n\n"
            "## Complexity\n\n"
            "Climbing stairs: O(n) time, O(1) space with rolling variables.\n"
            "Coin change: O(amount × len(coins)) time, O(amount) space.\n"
            "Fibonacci with memo: O(n) time, O(n) cache space (O(1) with rolling).\n\n"
            "## Practice\n\n"
            "Solve climbing stairs, then coin change (unbounded knapsack flavor).\n\n"
            "```python\n"
            "climb_stairs(5)              # 8\n"
            "coin_change([1, 2, 5], 11)   # 3\n"
            "```\n\n"
            "## Next steps\n\n"
            "2D DP grids (edit distance), bitmask DP, and interval DP build on the same "
            "recipe: define state, write recurrence, set bases, fill table."
        ),
    },
]
