"""APIs track lesson guides."""

LESSONS = [
    {
        "slug": "01_http_basics",
        "track": "apis",
        "difficulty": "easy",
        "title": "HTTP Status Codes and JSON",
        "tags": ["http", "json"],
        "exercise": "content/problems/apis/easy/04_status_class.py",
        "body": (
            "# HTTP Status Codes and JSON\n\n"
            "## Overview\n\n"
            "HTTP is the protocol behind web APIs. Clients send requests (method, URL, "
            "headers, body); servers respond with status, headers, and body. Most REST "
            "APIs return JSON in the body.\n\n"
            "You do not need to memorize every header on day one. Focus on three ideas: "
            "what you are asking for (method + URL), whether it worked (status code), "
            "and the payload (usually JSON text in the body).\n\n"
            "Think of an API call like ordering at a restaurant: you state what you want "
            "(GET /menu), the kitchen replies with a code (200 = here you go, 404 = "
            "that item is not on the menu), and the plate is the response body.\n\n"
            "## Request anatomy\n\n"
            "A raw HTTP request has a request line, headers, and an optional body:\n\n"
            "```\n"
            "GET /users?page=2 HTTP/1.1\n"
            "Host: api.example.com\n"
            "Accept: application/json\n"
            "\n"
            "```\n\n"
            "Common methods and their usual meaning:\n\n"
            "| Method | Typical use              |\n"
            "|--------|--------------------------|\n"
            "| GET    | Read data (no body)      |\n"
            "| POST   | Create a new resource    |\n"
            "| PUT    | Replace a resource       |\n"
            "| PATCH  | Update part of a resource|\n"
            "| DELETE | Remove a resource        |\n\n"
            "The response mirrors this structure: status line, headers, body.\n\n"
            "```\n"
            "HTTP/1.1 200 OK\n"
            "Content-Type: application/json\n"
            "\n"
            "{\"id\": 1, \"name\": \"Ada\"}\n"
            "```\n\n"
            "Headers are key-value metadata. `Content-Type: application/json` tells the "
            "client how to interpret the body. `Accept: application/json` on the "
            "request tells the server what format you prefer back.\n\n"
            "## Status code families\n\n"
            "The three-digit status code tells you the outcome at a glance:\n\n"
            "| Range | Meaning        | Examples              |\n"
            "|-------|----------------|-----------------------|\n"
            "| 1xx   | informational  | 100 Continue          |\n"
            "| 2xx   | success        | 200 OK, 201 Created   |\n"
            "| 3xx   | redirect       | 301 Moved, 304 Not Modified |\n"
            "| 4xx   | client error   | 400 Bad Request, 404 Not Found, 401 Unauthorized |\n"
            "| 5xx   | server error   | 500 Internal Error    |\n\n"
            "Classify by the first digit — the status *family*:\n\n"
            "```python\n"
            "def status_class(code: int) -> int:\n"
            "    return code // 100\n\n"
            "status_class(404)  # 4 — client error\n"
            "status_class(201)  # 2 — success\n"
            "```\n\n"
            "In practice you branch on specific codes or ranges:\n\n"
            "```python\n"
            "def is_success(code: int) -> bool:\n"
            "    return 200 <= code < 300\n\n"
            "def is_client_error(code: int) -> bool:\n"
            "    return 400 <= code < 500\n\n"
            "def describe_status(code: int) -> str:\n"
            "    if is_success(code):\n"
            "        return 'ok'\n"
            "    if code == 404:\n"
            "        return 'not found'\n"
            "    if code == 429:\n"
            "        return 'rate limited — slow down'\n"
            "    if 500 <= code < 600:\n"
            "        return 'server error — retry later'\n"
            "    return f'unexpected status {code}'\n"
            "```\n\n"
            "Memorize a handful you will see daily: 200, 201, 204, 400, 401, 403, 404, "
            "409, 422, 429, 500.\n\n"
            "## Worked example: handle a response safely\n\n"
            "Never assume the body is JSON or that a 404 is fine:\n\n"
            "```python\n"
            "import json\n\n"
            "def parse_api_response(status: int, body: str) -> dict:\n"
            "    if not (200 <= status < 300):\n"
            "        raise RuntimeError(f'HTTP {status}: {body[:200]}')\n"
            "    try:\n"
            "        return json.loads(body)\n"
            "    except json.JSONDecodeError as exc:\n"
            "        raise ValueError('expected JSON body') from exc\n"
            "```\n\n"
            "Step by step:\n"
            "1. Check the status before parsing — 4xx/5xx responses may return HTML error pages.\n"
            "2. `json.loads` on the response text converts JSON → Python dict/list.\n"
            "3. Wrap decode errors so callers know the server returned non-JSON.\n\n"
            "Walk through two scenarios:\n\n"
            "```python\n"
            "# Success\n"
            "data = parse_api_response(200, '{\"id\": 1, \"name\": \"Ada\"}')\n"
            "print(data['name'])   # Ada\n\n"
            "# Failure — raises before json.loads runs\n"
            "parse_api_response(404, '<html>Not Found</html>')\n"
            "```\n\n"
            "Libraries like `requests` and `httpx` expose `.json()` but you should still "
            "check `.status_code` or call `.raise_for_status()` first:\n\n"
            "```python\n"
            "# import httpx\n"
            "# response = httpx.get('https://api.example.com/users/1')\n"
            "# response.raise_for_status()\n"
            "# data = response.json()\n"
            "```\n\n"
            "## JSON in Python\n\n"
            "JSON maps directly to Python types you already know:\n\n"
            "```python\n"
            "import json\n\n"
            "payload = {'name': 'Ada', 'active': True, 'tags': ['python', 'api']}\n"
            "body = json.dumps(payload)              # dict → JSON string\n"
            "data = json.loads('{\"id\": 42}')       # JSON string → dict\n"
            "```\n\n"
            "Nested structures round-trip cleanly:\n\n"
            "```python\n"
            "user = {\n"
            "    'id': 42,\n"
            "    'profile': {'city': 'London', 'skills': ['python', 'http']},\n"
            "}\n"
            "text = json.dumps(user, indent=2)\n"
            "restored = json.loads(text)\n"
            "assert restored['profile']['skills'][0] == 'python'\n"
            "```\n\n"
            "Sending JSON in a POST body (conceptually):\n\n"
            "```python\n"
            "import json\n\n"
            "headers = {'Content-Type': 'application/json'}\n"
            "body = json.dumps({'email': 'ada@example.com'})\n"
            "# client.post(url, data=body, headers=headers)\n"
            "```\n\n"
            "`Content-Type: application/json` tells the server how to interpret the body.\n\n"
            "## Worked example: build and parse a mock exchange\n\n"
            "Practice the full round trip without a network:\n\n"
            "```python\n"
            "import json\n\n"
            "def create_user_request(email: str) -> tuple[str, dict, str]:\n"
            "    method = 'POST'\n"
            "    headers = {'Content-Type': 'application/json'}\n"
            "    body = json.dumps({'email': email})\n"
            "    return method, headers, body\n\n"
            "def handle_create_user(status: int, body: str) -> dict:\n"
            "    if status == 201:\n"
            "        return json.loads(body)\n"
            "    if status == 409:\n"
            "        raise ValueError('email already registered')\n"
            "    raise RuntimeError(f'unexpected status {status}')\n\n"
            "_, _, req_body = create_user_request('ada@example.com')\n"
            "resp_body = json.dumps({'id': 7, 'email': 'ada@example.com'})\n"
            "user = handle_create_user(201, resp_body)\n"
            "print(user['id'])   # 7\n"
            "```\n\n"
            "## Query strings\n\n"
            "Query parameters append key-value pairs after `?` in the URL:\n\n"
            "```\n"
            "https://api.example.com/search?q=python&page=2\n"
            "```\n\n"
            "Build them safely — never hand-join user input (spaces, `&`, and `=` need escaping):\n\n"
            "```python\n"
            "from urllib.parse import urlencode\n\n"
            "params = {'q': 'python tutorial', 'page': 2}\n"
            "qs = urlencode(params)\n"
            "url = f'https://api.example.com/search?{qs}'\n"
            "# https://api.example.com/search?q=python+tutorial&page=2\n"
            "```\n\n"
            "For multiple values per key, pass a sequence:\n\n"
            "```python\n"
            "urlencode([('tag', 'python'), ('tag', 'api')])\n"
            "# 'tag=python&tag=api'\n"
            "```\n\n"
            "Parse an existing URL to read parameters back:\n\n"
            "```python\n"
            "from urllib.parse import urlparse, parse_qs\n\n"
            "parts = urlparse('https://api.example.com/search?q=python&page=2')\n"
            "parse_qs(parts.query)   # {'q': ['python'], 'page': ['2']}\n"
            "```\n\n"
            "Note: `parse_qs` values are lists because keys can repeat.\n\n"
            "## Common pitfalls\n\n"
            "- Treating 404 as success — always check status\n"
            "- Assuming JSON body on error responses (may be HTML)\n"
            "- Ignoring rate limits (429) and retry-after headers\n"
            "- Forgetting to set `Content-Type` when sending JSON\n"
            "- Comparing float JSON numbers with `==` — rounding surprises\n"
            "- Logging full response bodies that contain passwords or tokens\n\n"
            "## Practice\n\n"
            "Write a helper that returns the status class (2, 4, 5, etc.).\n\n"
            "## Summary\n\n"
            "Know methods, status families, and JSON encode/decode — the foundation "
            "for every HTTP client and server exercise in this track. Check status "
            "first, parse JSON second, and build URLs with `urlencode`."
        ),
    },
    {
        "slug": "02_rest_design",
        "track": "apis",
        "difficulty": "medium",
        "title": "REST API Design Basics",
        "tags": ["rest", "api-design"],
        "exercise": "content/problems/apis/medium/12_merge_query_params.py",
        "body": (
            "# REST API Design Basics\n\n"
            "## Overview\n\n"
            "REST (Representational State Transfer) organizes APIs around resources "
            "(nouns) and HTTP verbs (actions). Good design is predictable: the same "
            "patterns everywhere.\n\n"
            "When you read a well-designed API, you should guess the next endpoint "
            "before reading the docs: plural nouns, standard methods, consistent JSON "
            "shapes, and status codes that match what actually happened.\n\n"
            "Bad APIs mix verbs into URLs, return 200 for everything, and rename fields "
            "between endpoints. Good APIs feel boring — in a good way.\n\n"
            "## Resource-oriented URLs\n\n"
            "Paths name *things*, not actions. HTTP methods carry the verb:\n\n"
            "```\n"
            "GET    /users          list users\n"
            "POST   /users          create user\n"
            "GET    /users/42       get user 42\n"
            "PATCH  /users/42       update fields\n"
            "DELETE /users/42       remove user\n"
            "GET    /users/42/posts nested collection\n"
            "```\n\n"
            "Use plural nouns (`/users`, not `/user`). Avoid verbs in paths — "
            "`/getUser` and `/createOrder` fight the HTTP method model.\n\n"
            "IDs identify one resource. Collections live at the plural path:\n\n"
            "```\n"
            "GET /items        → [{\"id\": 1, ...}, {\"id\": 2, ...}]\n"
            "GET /items/7      → {\"id\": 7, ...}\n"
            "```\n\n"
            "Nested resources express ownership:\n\n"
            "```\n"
            "GET  /users/42/orders       list orders for user 42\n"
            "POST /users/42/orders       create order for user 42\n"
            "GET  /orders/99/items       line items on order 99\n"
            "```\n\n"
            "Do not nest more than two levels deep (`/a/b/c` is usually a smell).\n\n"
            "## Status codes that match intent\n\n"
            "Return the code that describes the outcome, not always 200:\n\n"
            "- 200 OK — successful GET, PATCH, or PUT with a body\n"
            "- 201 Created + `Location` header on POST\n"
            "- 204 No Content on DELETE success (no body needed)\n"
            "- 400 Bad Request for validation errors (bad JSON, missing field)\n"
            "- 404 Not Found when the resource ID does not exist\n"
            "- 409 Conflict for duplicate unique keys (email already taken)\n\n"
            "Example POST response headers:\n\n"
            "```\n"
            "HTTP/1.1 201 Created\n"
            "Location: /users/42\n"
            "Content-Type: application/json\n"
            "\n"
            "{\"id\": 42, \"email\": \"ada@example.com\"}\n"
            "```\n\n"
            "Worked example: choose the right code in a tiny handler:\n\n"
            "```python\n"
            "def delete_user(user_id: int, db: dict) -> tuple[int, str | None]:\n"
            "    if user_id not in db:\n"
            "        return 404, '{\"error\": \"not_found\"}'\n"
            "    del db[user_id]\n"
            "    return 204, None   # success, no body\n"
            "```\n\n"
            "## Request and response shapes\n\n"
            "Keep field names consistent across every endpoint — pick snake_case or "
            "camelCase and stick with it:\n\n"
            "```json\n"
            "{\n"
            "  \"id\": 42,\n"
            "  \"email\": \"ada@example.com\",\n"
            "  \"created_at\": \"2026-01-15T10:00:00Z\"\n"
            "}\n"
            "```\n\n"
            "Timestamps as ISO-8601 strings (`2026-01-15T10:00:00Z`) parse cleanly in "
            "every language. Booleans are `true`/`false`, not `1`/`0`.\n\n"
            "List responses wrap items plus metadata:\n\n"
            "```json\n"
            "{\n"
            "  \"items\": [\n"
            "    {\"id\": 1, \"name\": \"Widget\"},\n"
            "    {\"id\": 2, \"name\": \"Gadget\"}\n"
            "  ]\n"
            "}\n"
            "```\n\n"
            "Error bodies should be machine- and human-readable:\n\n"
            "```json\n"
            "{\n"
            "  \"error\": \"validation_failed\",\n"
            "  \"message\": \"email is required\",\n"
            "  \"fields\": {\"email\": \"missing\"}\n"
            "}\n"
            "```\n\n"
            "## Pagination and filtering\n\n"
            "List endpoints accept query parameters instead of new paths:\n\n"
            "```\n"
            "GET /items?limit=20&offset=40\n"
            "GET /items?sort=-created_at&tag=python\n"
            "GET /items?status=active&min_price=10\n"
            "```\n\n"
            "Return metadata so clients know how to fetch the next page:\n\n"
            "```json\n"
            "{\n"
            "  \"items\": [...],\n"
            "  \"total\": 150,\n"
            "  \"limit\": 20,\n"
            "  \"offset\": 40\n"
            "}\n"
            "```\n\n"
            "Client logic for paging through all results:\n\n"
            "```python\n"
            "def fetch_all_items(client, base_url: str, limit: int = 50) -> list[dict]:\n"
            "    offset = 0\n"
            "    all_items = []\n"
            "    while True:\n"
            "        url = f'{base_url}?limit={limit}&offset={offset}'\n"
            "        page = client.get(url).json()\n"
            "        all_items.extend(page['items'])\n"
            "        offset += limit\n"
            "        if offset >= page['total']:\n"
            "            break\n"
            "    return all_items\n"
            "```\n\n"
            "## Worked example: merge and build query strings\n\n"
            "Clients often combine default filters with user-supplied ones. Merge dicts, "
            "then encode safely:\n\n"
            "```python\n"
            "from urllib.parse import urlencode, urlparse, parse_qs, urlunparse\n\n"
            "def merge_query_params(url: str, extra: dict) -> str:\n"
            "    parts = urlparse(url)\n"
            "    existing = {k: v[0] for k, v in parse_qs(parts.query).items()}\n"
            "    merged = {**existing, **extra}\n"
            "    new_query = urlencode(merged)\n"
            "    return urlunparse(parts._replace(query=new_query))\n\n"
            "base = 'https://api.example.com/items?limit=20&tag=python'\n"
            "merged = merge_query_params(base, {'page': 2, 'tag': 'api'})\n"
            "# tag=api overwrites tag=python; page=2 is added\n"
            "```\n\n"
            "Step by step:\n"
            "1. `urlparse` splits the URL into components.\n"
            "2. `parse_qs` reads existing query keys (values are lists).\n"
            "3. Dict merge lets new params override old ones.\n"
            "4. `urlencode` + `urlunparse` rebuilds a valid URL.\n\n"
            "Trace the merge:\n\n"
            "```python\n"
            "print(merged)\n"
            "# https://api.example.com/items?limit=20&tag=api&page=2\n"
            "```\n\n"
            "For greenfield URLs without existing params:\n\n"
            "```python\n"
            "from urllib.parse import urlencode\n\n"
            "def build_list_url(base: str, **filters) -> str:\n"
            "    clean = {k: v for k, v in filters.items() if v is not None}\n"
            "    if not clean:\n"
            "        return base\n"
            "    return f'{base}?{urlencode(clean)}'\n\n"
            "build_list_url('https://api.example.com/items', limit=20, tag='python')\n"
            "# https://api.example.com/items?limit=20&tag=python\n"
            "build_list_url('https://api.example.com/items', limit=20, tag=None)\n"
            "# https://api.example.com/items?limit=20  — None keys dropped\n"
            "```\n\n"
            "## Idempotency and method choice\n\n"
            "GET, PUT, and DELETE should be safe to repeat — calling them twice should "
            "not create duplicate side effects. POST creates new resources each time.\n\n"
            "```\n"
            "GET    /items/7     → read (safe, repeatable)\n"
            "PUT    /items/7     → replace entire resource\n"
            "PATCH  /items/7     → change one field\n"
            "POST   /items       → create (each call may add another row)\n"
            "```\n\n"
            "Use PATCH for partial updates (`{\"email\": \"new@x.com\"}`), PUT when "
            "the client sends the full resource representation.\n\n"
            "## Versioning and errors\n\n"
            "- Prefix: `/v1/users` or header `Accept: application/vnd.myapp.v1+json`\n"
            "- Bump version when you remove or rename fields — clients depend on stability\n"
            "- Never return stack traces in 500 responses; log them server-side\n\n"
            "## Common pitfalls\n\n"
            "- Using POST for everything (including idempotent reads)\n"
            "- Leaking internal IDs or stack traces in 500 responses\n"
            "- Breaking changes without version bump\n"
            "- Inconsistent pluralization (`/user` vs `/users`)\n"
            "- Pagination without total count or next-page link\n"
            "- Encoding query params by hand — spaces and `&` break URLs\n\n"
            "## Practice\n\n"
            "Build query strings for filter parameters safely with urlencode.\n\n"
            "## Summary\n\n"
            "REST = resources + HTTP semantics + consistent JSON. Design for the client "
            "you wish you had when reading someone else's API: predictable URLs, honest "
            "status codes, and query strings built with `urlencode`, not string concat."
        ),
    },
]
