"""Apps track lesson guides."""

LESSONS = [
    {
        "slug": "01_oop_basics",
        "track": "apps",
        "difficulty": "easy",
        "title": "Classes and Application State",
        "tags": ["oop"],
        "exercise": "content/problems/apps/easy/02_todo_list.py",
        "body": (
            "# Classes and Application State\n\n"
            "## Overview\n\n"
            "A class bundles data (attributes) and behavior (methods) for one concept: "
            "a todo list, shopping cart, game board. Application logic becomes easier "
            "to test when state lives in well-named objects.\n\n"
            "Without classes, a growing script accumulates loose variables and functions "
            "that pass the same dict everywhere. A class says: this data and these "
            "operations belong together. Callers interact through a small public API "
            "instead of reaching into raw lists and indexes.\n\n"
            "If you can describe something as a noun with verbs — a cart that adds items, "
            "a list that completes tasks — it is probably a class candidate.\n\n"
            "## Minimal class\n\n"
            "Every instance method takes `self` as the first parameter — the object "
            "being operated on. `__init__` runs when you construct a new instance:\n\n"
            "```python\n"
            "class TodoList:\n"
            "    def __init__(self):\n"
            "        self.items = []\n\n"
            "    def add(self, task: str) -> None:\n"
            "        self.items.append(task)\n\n"
            "    def done(self, index: int) -> str:\n"
            "        return self.items.pop(index)\n"
            "```\n\n"
            "Usage:\n\n"
            "```python\n"
            "todos = TodoList()\n"
            "todos.add('buy milk')\n"
            "todos.add('write tests')\n"
            "finished = todos.done(0)   # removes and returns 'buy milk'\n"
            "```\n\n"
            "`self.items` is per-instance state. Two `TodoList` objects do not share the "
            "same list unless you deliberately wire them that way:\n\n"
            "```python\n"
            "work = TodoList()\n"
            "home = TodoList()\n"
            "work.add('deploy')\n"
            "len(home.items)   # 0 — separate lists\n"
            "```\n\n"
            "## Worked example: a complete TodoList\n\n"
            "A more realistic version validates input and exposes read-only views:\n\n"
            "```python\n"
            "class TodoList:\n"
            "    def __init__(self):\n"
            "        self._items: list[str] = []\n\n"
            "    def add(self, task: str) -> None:\n"
            "        task = task.strip()\n"
            "        if not task:\n"
            "            raise ValueError('task cannot be empty')\n"
            "        self._items.append(task)\n\n"
            "    def list(self) -> list[str]:\n"
            "        return list(self._items)\n\n"
            "    def complete(self, index: int) -> str:\n"
            "        if index < 0 or index >= len(self._items):\n"
            "            raise IndexError('no task at that index')\n"
            "        return self._items.pop(index)\n\n"
            "    def __len__(self) -> int:\n"
            "        return len(self._items)\n\n"
            "    def __repr__(self) -> str:\n"
            "        return f'TodoList({self._items!r})'\n"
            "```\n\n"
            "Step by step:\n"
            "1. `_items` with a leading underscore signals internal storage (convention, not enforcement).\n"
            "2. `add` strips whitespace and rejects empty strings.\n"
            "3. `list` returns a copy so callers cannot mutate internal state directly.\n"
            "4. `complete` bounds-checks before `pop`.\n"
            "5. `__len__` enables `len(todos)`; `__repr__` helps debugging.\n\n"
            "Quick test in the REPL:\n\n"
            "```python\n"
            "t = TodoList()\n"
            "t.add('read chapter 3')\n"
            "assert len(t) == 1\n"
            "assert t.list() == ['read chapter 3']\n"
            "t.complete(0)\n"
            "assert len(t) == 0\n"
            "```\n\n"
            "Why return a copy from `list()`?\n\n"
            "```python\n"
            "t = TodoList()\n"
            "t.add('task')\n"
            "view = t.list()\n"
            "view.clear()        # does NOT empty the TodoList\n"
            "len(t)              # still 1\n"
            "```\n\n"
            "## Encapsulation convention\n\n"
            "Python trusts the programmer — conventions over strict privacy:\n\n"
            "- Public API: no leading underscore (`add`, `complete`)\n"
            "- Internal helper or storage: `_validate()`, `_items`\n"
            "- Name mangling: `__secret` (rare; avoid unless subclass interference is a real problem)\n\n"
            "Callers should use public methods. If you need to change how tasks are stored "
            "(list → database), you change `_items` internals without breaking `add`/`complete`.\n\n"
            "## When to use a class vs functions\n\n"
            "| Use a class when…              | Use functions when…     |\n"
            "|--------------------------------|-------------------------|\n"
            "| State persists across calls    | One-off transform       |\n"
            "| Multiple related operations    | Single pure computation |\n"
            "| You need several instances     | No shared state         |\n\n"
            "Example: `normalize_email(s)` is a function; `ShoppingCart` is a class because "
            "it accumulates items across many `add` calls.\n\n"
            "Worked example: shopping cart sketch:\n\n"
            "```python\n"
            "class ShoppingCart:\n"
            "    def __init__(self):\n"
            "        self._lines: list[tuple[str, int]] = []\n\n"
            "    def add(self, name: str, price_cents: int) -> None:\n"
            "        self._lines.append((name, price_cents))\n\n"
            "    def total_cents(self) -> int:\n"
            "        return sum(price for _, price in self._lines)\n\n"
            "cart = ShoppingCart()\n"
            "cart.add('notebook', 499)\n"
            "cart.add('pen', 199)\n"
            "cart.total_cents()   # 698\n"
            "```\n\n"
            "## Dataclasses for data-heavy objects\n\n"
            "When a class is mostly fields with little behavior, `@dataclass` removes "
            "boilerplate:\n\n"
            "```python\n"
            "from dataclasses import dataclass\n\n"
            "@dataclass\n"
            "class Task:\n"
            "    title: str\n"
            "    done: bool = False\n\n"
            "task = Task('deploy')\n"
            "task.done = True\n"
            "```\n\n"
            "Dataclasses auto-generate `__init__`, `__repr__`, and equality. Use a regular "
            "class when behavior dominates; use dataclass for structured records.\n\n"
            "Combine dataclass records with a class that owns a collection:\n\n"
            "```python\n"
            "from dataclasses import dataclass\n\n"
            "@dataclass\n"
            "class Task:\n"
            "    title: str\n"
            "    done: bool = False\n\n"
            "class TaskBoard:\n"
            "    def __init__(self):\n"
            "        self._tasks: list[Task] = []\n\n"
            "    def add(self, title: str) -> None:\n"
            "        self._tasks.append(Task(title))\n\n"
            "    def pending(self) -> list[Task]:\n"
            "        return [t for t in self._tasks if not t.done]\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Mutable default args in `__init__` — use `None` and assign in body:\n\n"
            "```python\n"
            "def __init__(self, items=None):\n"
            "    self.items = [] if items is None else list(items)\n"
            "```\n\n"
            "Wrong version `def __init__(self, items=[])` shares one list across all instances.\n\n"
            "- God objects that know everything — split responsibilities (storage vs UI)\n"
            "- Forgetting `self.` when assigning instance attributes\n"
            "- Returning the internal list directly — callers can `.clear()` your state\n"
            "- Putting I/O (print, input) inside domain classes — keep them testable\n\n"
            "## Practice\n\n"
            "Implement a TodoList with add, list, and complete operations.\n\n"
            "## Summary\n\n"
            "Classes model things your app manipulates over time. Keep them small; "
            "test methods in isolation. Use `__init__` for setup, underscore conventions "
            "for internals, and return copies when exposing mutable state."
        ),
    },
    {
        "slug": "02_state_machines",
        "track": "apps",
        "difficulty": "medium",
        "title": "State Machines in Applications",
        "tags": ["state-machine"],
        "exercise": "content/problems/apps/medium/08_pomodoro_state.py",
        "body": (
            "# State Machines in Applications\n\n"
            "## Overview\n\n"
            "Many app workflows are finite state machines: orders (pending → paid → "
            "shipped), tickets (open → in progress → closed), games (menu → playing → "
            "game over). Explicit states prevent impossible transitions.\n\n"
            "A boolean flag per concern (`is_paid`, `is_shipped`, `is_cancelled`) "
            "explodes into illegal combinations — paid and cancelled at once. A state "
            "machine allows exactly one current state and defines which moves are legal.\n\n"
            "Think of states as rooms and transitions as doors. You can only walk through "
            "doors that exist; the transition table is the floor plan.\n\n"
            "## Modeling states\n\n"
            "`Enum` gives named constants and blocks typos like `'PENDNG'`:\n\n"
            "```python\n"
            "from enum import Enum, auto\n\n"
            "class OrderState(Enum):\n"
            "    PENDING = auto()\n"
            "    PAID = auto()\n"
            "    SHIPPED = auto()\n"
            "    CANCELLED = auto()\n"
            "```\n\n"
            "Compare with `is` or `==` — never compare to raw strings loaded from a database "
            "without validating first:\n\n"
            "```python\n"
            "def parse_state(name: str) -> OrderState:\n"
            "    try:\n"
            "        return OrderState[name]\n"
            "    except KeyError:\n"
            "        raise ValueError(f'unknown state: {name}')\n"
            "```\n\n"
            "## Transition table\n\n"
            "Encode allowed edges in one data structure. Every transition goes through one function:\n\n"
            "```python\n"
            "ALLOWED = {\n"
            "    OrderState.PENDING: {OrderState.PAID, OrderState.CANCELLED},\n"
            "    OrderState.PAID: {OrderState.SHIPPED},\n"
            "    OrderState.SHIPPED: set(),\n"
            "    OrderState.CANCELLED: set(),\n"
            "}\n\n"
            "def transition(order, new_state: OrderState) -> None:\n"
            "    allowed = ALLOWED[order.state]\n"
            "    if new_state not in allowed:\n"
            "        raise ValueError(\n"
            "            f'cannot go {order.state.name} -> {new_state.name}'\n"
            "        )\n"
            "    order.state = new_state\n"
            "```\n\n"
            "Terminal states (`SHIPPED`, `CANCELLED`) have empty allowed sets — no way out "
            "without adding a new business rule.\n\n"
            "Draw the table as a diagram while learning:\n\n"
            "```\n"
            "PENDING ──→ PAID ──→ SHIPPED\n"
            "   │\n"
            "   └──→ CANCELLED\n"
            "```\n\n"
            "## Worked example: Order object with history\n\n"
            "Wrap state in a class so callers cannot assign `order.state` directly:\n\n"
            "```python\n"
            "from dataclasses import dataclass, field\n"
            "from enum import Enum, auto\n\n"
            "class OrderState(Enum):\n"
            "    PENDING = auto()\n"
            "    PAID = auto()\n"
            "    SHIPPED = auto()\n"
            "    CANCELLED = auto()\n\n"
            "ALLOWED = {\n"
            "    OrderState.PENDING: {OrderState.PAID, OrderState.CANCELLED},\n"
            "    OrderState.PAID: {OrderState.SHIPPED},\n"
            "    OrderState.SHIPPED: set(),\n"
            "    OrderState.CANCELLED: set(),\n"
            "}\n\n"
            "@dataclass\n"
            "class Order:\n"
            "    id: int\n"
            "    state: OrderState = OrderState.PENDING\n"
            "    history: list[str] = field(default_factory=list)\n\n"
            "    def advance(self, new_state: OrderState) -> None:\n"
            "        if new_state not in ALLOWED[self.state]:\n"
            "            raise ValueError(f'{self.state.name} -> {new_state.name} not allowed')\n"
            "        self.history.append(f'{self.state.name} -> {new_state.name}')\n"
            "        self.state = new_state\n"
            "```\n\n"
            "Walk through a happy path:\n\n"
            "```python\n"
            "order = Order(id=1)\n"
            "order.advance(OrderState.PAID)\n"
            "order.advance(OrderState.SHIPPED)\n"
            "order.history\n"
            "# ['PENDING -> PAID', 'PAID -> SHIPPED']\n\n"
            "order.advance(OrderState.CANCELLED)  # ValueError\n"
            "```\n\n"
            "Step by step:\n"
            "1. New orders start in `PENDING`.\n"
            "2. `advance` checks the table before mutating.\n"
            "3. `history` records an audit trail for support and debugging.\n"
            "4. Illegal moves raise immediately instead of corrupting data.\n\n"
            "List legal next moves for UI buttons:\n\n"
            "```python\n"
            "def available_actions(order: Order) -> list[OrderState]:\n"
            "    return sorted(ALLOWED[order.state], key=lambda s: s.name)\n\n"
            "available_actions(Order(id=1))\n"
            "# [OrderState.PAID, OrderState.CANCELLED]\n"
            "```\n\n"
            "## Worked example: timer states (Pomodoro-style)\n\n"
            "The same pattern fits UI timers with fewer states:\n\n"
            "```python\n"
            "from enum import Enum, auto\n\n"
            "class TimerPhase(Enum):\n"
            "    IDLE = auto()\n"
            "    RUNNING = auto()\n"
            "    PAUSED = auto()\n"
            "    FINISHED = auto()\n\n"
            "TIMER_ALLOWED = {\n"
            "    TimerPhase.IDLE: {TimerPhase.RUNNING},\n"
            "    TimerPhase.RUNNING: {TimerPhase.PAUSED, TimerPhase.FINISHED},\n"
            "    TimerPhase.PAUSED: {TimerPhase.RUNNING, TimerPhase.IDLE},\n"
            "    TimerPhase.FINISHED: {TimerPhase.IDLE},\n"
            "}\n\n"
            "def advance_timer(phase: TimerPhase, event: str) -> TimerPhase:\n"
            "    targets = {\n"
            "        'start': TimerPhase.RUNNING,\n"
            "        'pause': TimerPhase.PAUSED,\n"
            "        'finish': TimerPhase.FINISHED,\n"
            "        'reset': TimerPhase.IDLE,\n"
            "    }\n"
            "    new = targets[event]\n"
            "    if new not in TIMER_ALLOWED[phase]:\n"
            "        raise ValueError(f'cannot {event} while {phase.name}')\n"
            "    return new\n"
            "```\n\n"
            "Map button clicks to events (`start`, `pause`, `reset`) and only enable "
            "buttons when the event is legal from the current phase.\n\n"
            "Walk through a session:\n\n"
            "```python\n"
            "phase = TimerPhase.IDLE\n"
            "phase = advance_timer(phase, 'start')    # RUNNING\n"
            "phase = advance_timer(phase, 'pause')    # PAUSED\n"
            "phase = advance_timer(phase, 'start')    # RUNNING again\n"
            "phase = advance_timer(phase, 'finish')   # FINISHED\n"
            "phase = advance_timer(phase, 'reset')    # IDLE\n"
            "advance_timer(phase, 'pause')            # ValueError — cannot pause while IDLE\n"
            "```\n\n"
            "## Benefits\n\n"
            "- Business rules live in one place (the transition table)\n"
            "- Easy to diagram and review with stakeholders\n"
            "- Tests cover every allowed and forbidden edge in a loop\n\n"
            "```python\n"
            "def test_all_illegal_transitions():\n"
            "    for src in OrderState:\n"
            "        for dst in OrderState:\n"
            "            if dst not in ALLOWED[src]:\n"
            "                order = Order(id=0, state=src)\n"
            "                try:\n"
            "                    order.advance(dst)\n"
            "                except ValueError:\n"
            "                    pass\n"
            "                else:\n"
            "                    raise AssertionError(f'{src} -> {dst} should fail')\n"
            "```\n\n"
            "This loop tests every forbidden edge automatically — add a new state and "
            "the test still covers it.\n\n"
            "## Persisting state safely\n\n"
            "When saving to a database or file, store the enum name as a string:\n\n"
            "```python\n"
            "def order_to_dict(order: Order) -> dict:\n"
            "    return {'id': order.id, 'state': order.state.name, 'history': order.history}\n\n"
            "def order_from_dict(data: dict) -> Order:\n"
            "    return Order(\n"
            "        id=data['id'],\n"
            "        state=OrderState[data['state']],\n"
            "        history=list(data.get('history', [])),\n"
            "    )\n"
            "```\n\n"
            "Always validate on load — never trust raw strings from storage.\n\n"
            "## UI connection\n\n"
            "Enable buttons only for valid transitions. Display current state clearly — "
            "users should never wonder whether an order is paid or merely pending.\n\n"
            "```python\n"
            "def button_enabled(order: Order, action: OrderState) -> bool:\n"
            "    return action in ALLOWED[order.state]\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Scattering `if status == ...` across dozens of files\n"
            "- Allowing backward transitions without explicit business approval\n"
            "- Persisting state as free-form strings without validation on load\n"
            "- Skipping terminal states in the table (implicit None → anything)\n"
            "- Letting callers set `.state` directly — route changes through `advance`\n\n"
            "## Practice\n\n"
            "Implement order state transitions with a validation table.\n\n"
            "## Summary\n\n"
            "State machine = states + allowed edges + transition function. Use when "
            "workflow rules matter more than free-form flags. Centralize the table, "
            "route every change through one method, and test illegal paths as thoroughly "
            "as happy paths."
        ),
    },
]
