"""Automations track lesson guides."""

LESSONS = [
    {
        "slug": "01_pathlib",
        "track": "automations",
        "difficulty": "easy",
        "title": "pathlib Essentials",
        "tags": ["pathlib", "files"],
        "exercise": "content/problems/automations/easy/10_extension_grouper.py",
        "body": (
            "# pathlib Essentials\n\n"
            "## Overview\n\n"
            "Every automation script eventually touches the filesystem: reading configs, "
            "renaming photos, archiving logs, or organizing downloads. For years Python "
            "used string paths with `os.path.join` and `os.listdir`. `pathlib.Path` "
            "replaces that with a single object that knows how to join segments, test "
            "existence, read text, and walk directories — all with readable, chainable "
            "methods.\n\n"
            "Think of a `Path` as an address label for a file or folder. You can inspect "
            "the label (`name`, `suffix`), check whether the place exists, and open it "
            "without converting back and forth between strings. If you are new to file "
            "automation, start here: pathlib is the modern default for any script that "
            "reads or writes files.\n\n"
            "## Why pathlib instead of strings?\n\n"
            "String paths work, but they are easy to get wrong:\n\n"
            "```python\n"
            "# Old style — easy to mix separators or forget edge cases\n"
            "import os\n"
            "folder = os.path.join('output', 'reports', '2026')\n"
            "for name in os.listdir(folder):\n"
            "    full = os.path.join(folder, name)\n"
            "```\n\n"
            "The pathlib version reads top to bottom like a sentence:\n\n"
            "```python\n"
            "from pathlib import Path\n\n"
            "folder = Path('output') / 'reports' / '2026'\n"
            "for path in folder.iterdir():\n"
            "    print(path.name)\n"
            "```\n\n"
            "Same result, fewer moving parts, and `path` is already a `Path` object — "
            "no re-wrapping on every loop iteration.\n\n"
            "## Creating paths\n\n"
            "Start by importing `Path` and building locations from strings or other paths:\n\n"
            "```python\n"
            "from pathlib import Path\n\n"
            "root = Path('.')                          # current directory\n"
            "readme = Path('docs/readme.md')           # relative path\n"
            "config = Path.home() / '.config' / 'myapp' / 'settings.json'\n"
            "```\n\n"
            "The `/` operator joins segments. Python picks `/` on Linux and macOS, `\\` on "
            "Windows — you never hard-code separators. `Path.home()` expands to the user's "
            "home directory (`/home/you` or `C:\\Users\\you`).\n\n"
            "Build paths step by step when a script receives parts from different places:\n\n"
            "```python\n"
            "base = Path('/var/log')\n"
            "app_name = 'myapp'\n"
            "log_file = base / app_name / 'app.log'\n"
            "# Path('/var/log/myapp/app.log')\n"
            "```\n\n"
            "Convert legacy APIs that expect strings with `str(p)` or `os.fspath(p)`:\n\n"
            "```python\n"
            "import subprocess\n"
            "subprocess.run(['ls', str(root)], check=True)\n"
            "```\n\n"
            "## Inspecting paths\n\n"
            "Path objects expose the pieces of a filepath as attributes. This is faster "
            "and clearer than splitting strings yourself:\n\n"
            "```python\n"
            "p = Path('docs/readme.md')\n"
            "p.name       # 'readme.md'   — filename with extension\n"
            "p.stem       # 'readme'      — filename without extension\n"
            "p.suffix     # '.md'         — extension including the dot\n"
            "p.parent     # Path('docs')  — containing folder\n"
            "p.parts      # ('docs', 'readme.md')\n"
            "```\n\n"
            "Walk through a real rename scenario. You have `photo.JPG` and want a lowercase "
            "extension plus a dated backup name:\n\n"
            "```python\n"
            "original = Path('downloads/photo.JPG')\n"
            "normalized = original.with_suffix('.jpg')\n"
            "backup = original.with_name(f'{original.stem}_2026-07-01{original.suffix}')\n"
            "# Path('downloads/photo_2026-07-01.JPG')\n"
            "```\n\n"
            "Useful variations when building output names:\n\n"
            "```python\n"
            "backup = p.with_suffix('.bak')       # Path('docs/readme.bak')\n"
            "copy = p.with_name('readme_copy.md') # Path('docs/readme_copy.md')\n"
            "```\n\n"
            "## Existence and type checks\n\n"
            "Before reading or writing, confirm the path points where you expect:\n\n"
            "```python\n"
            "p = Path('docs/readme.md')\n"
            "p.exists()     # True if anything is at this path\n"
            "p.is_file()    # True only for regular files\n"
            "p.is_dir()     # True only for directories\n"
            "p.resolve()    # absolute path, symlinks followed\n"
            "```\n\n"
            "A safe read pattern checks first and gives a clear error:\n\n"
            "```python\n"
            "def read_config(path: Path) -> str:\n"
            "    if not path.is_file():\n"
            "        raise FileNotFoundError(f'config not found: {path}')\n"
            "    return path.read_text(encoding='utf-8')\n"
            "```\n\n"
            "Create missing directories safely before writing output:\n\n"
            "```python\n"
            "out_dir = Path('output/reports')\n"
            "out_dir.mkdir(parents=True, exist_ok=True)\n"
            "(out_dir / 'summary.txt').write_text('done\\n', encoding='utf-8')\n"
            "```\n\n"
            "`parents=True` creates intermediate folders; `exist_ok=True` avoids errors "
            "when the folder already exists.\n\n"
            "## Reading and writing\n\n"
            "For small text files, pathlib shortcuts replace manual `open`/`close`:\n\n"
            "```python\n"
            "p = Path('notes.txt')\n"
            "text = p.read_text(encoding='utf-8')\n"
            "p.write_text('hello\\n', encoding='utf-8')\n"
            "raw = p.read_bytes()   # for images, PDFs, etc.\n"
            "```\n\n"
            "Always pass `encoding='utf-8'` on text files — especially on Windows, where "
            "the default encoding may not be UTF-8.\n\n"
            "Worked example: append a timestamped line to a log file:\n\n"
            "```python\n"
            "from datetime import datetime, timezone\n\n"
            "log = Path('logs/app.log')\n"
            "log.parent.mkdir(parents=True, exist_ok=True)\n"
            "stamp = datetime.now(timezone.utc).isoformat()\n"
            "with log.open('a', encoding='utf-8') as f:\n"
            "    f.write(f'{stamp} backup complete\\n')\n"
            "```\n\n"
            "Step by step:\n"
            "1. `log.parent.mkdir` ensures the `logs/` folder exists.\n"
            "2. Open in append mode (`'a'`) so previous lines stay.\n"
            "3. Write one line with a newline at the end.\n\n"
            "For large files or line-by-line processing, combine `Path` with `open`:\n\n"
            "```python\n"
            "with p.open(encoding='utf-8') as f:\n"
            "    for line in f:\n"
            "        print(line.rstrip())\n"
            "```\n\n"
            "## Walking directories\n\n"
            "List one directory or search recursively:\n\n"
            "```python\n"
            "folder = Path('src')\n"
            "for child in folder.iterdir():\n"
            "    print(child.name)\n\n"
            "for path in folder.glob('*.py'):      # this folder only\n"
            "    print(path)\n\n"
            "for path in folder.rglob('*.py'):     # all subfolders too\n"
            "    print(path.relative_to(folder))\n"
            "```\n\n"
            "`glob` matches a pattern in one directory; `rglob` walks the whole tree. "
            "Use `relative_to(root)` when you want paths without a long prefix.\n\n"
            "Find every `.log` file modified in the last 7 days:\n\n"
            "```python\n"
            "import time\n\n"
            "cutoff = time.time() - 7 * 24 * 3600\n"
            "for path in Path('/var/log').rglob('*.log'):\n"
            "    if path.is_file() and path.stat().st_mtime >= cutoff:\n"
            "        print(path, path.stat().st_size, 'bytes')\n"
            "```\n\n"
            "`stat()` returns metadata: size, modification time, permissions. Handy for "
            "cleanup scripts that delete old files.\n\n"
            "## Worked example: group files by extension\n\n"
            "Here is a complete script that scans a folder and groups filenames by "
            "extension — the pattern behind the practice exercise:\n\n"
            "```python\n"
            "from pathlib import Path\n"
            "from collections import defaultdict\n\n"
            "def group_by_extension(folder: Path) -> dict[str, list[Path]]:\n"
            "    groups: dict[str, list[Path]] = defaultdict(list)\n"
            "    for path in folder.iterdir():\n"
            "        if path.is_file():\n"
            "            ext = path.suffix.lower() or '(no extension)'\n"
            "            groups[ext].append(path)\n"
            "    return dict(groups)\n\n"
            "downloads = Path.home() / 'Downloads'\n"
            "for ext, files in sorted(group_by_extension(downloads).items()):\n"
            "    print(f'{ext}: {len(files)} file(s)')\n"
            "```\n\n"
            "Step by step:\n"
            "1. `iterdir()` yields every entry in the folder.\n"
            "2. `is_file()` skips subdirectories.\n"
            "3. `suffix` gives `.jpg`, `.pdf`, etc.; empty string means no extension.\n"
            "4. `defaultdict(list)` appends without checking if the key exists yet.\n"
            "5. `sorted(...)` prints extensions in alphabetical order.\n\n"
            "Extend it: move each group into its own subfolder:\n\n"
            "```python\n"
            "def organize_by_extension(folder: Path) -> None:\n"
            "    for ext, files in group_by_extension(folder).items():\n"
            "        target = folder / ext.lstrip('.')\n"
            "        target.mkdir(exist_ok=True)\n"
            "        for path in files:\n"
            "            path.rename(target / path.name)\n"
            "```\n\n"
            "A rename helper built from the same pieces:\n\n"
            "```python\n"
            "def backup_path(original: Path) -> Path:\n"
            "    return original.with_name(f'{original.stem}_backup{original.suffix}')\n"
            "```\n\n"
            "## Common automation patterns\n\n"
            "- Group files by extension for batch rename or organize\n"
            "- Find duplicate sizes or names under a tree with `rglob` + a dict\n"
            "- Build output paths with `dest = out_dir / f'{stem}_copy{p.suffix}'`\n"
            "- Filter by date with `path.stat().st_mtime` for cleanup scripts\n"
            "- Mirror a folder tree with `relative_to` and `mkdir(parents=True)`\n\n"
            "## Common pitfalls\n\n"
            "- Mixing `str` and `Path` — convert with `Path(s)` or `str(p)` for legacy APIs\n"
            "- Forgetting encoding on text files on Windows\n"
            "- Using `glob('*')` when you need recursion (`rglob`)\n"
            "- Calling `iterdir()` on a file path — it raises; check `is_dir()` first\n"
            "- Assuming `exists()` means readable — permissions still matter\n"
            "- `rename` across filesystems may fail — use `shutil.move` for cross-device moves\n\n"
            "## Practice\n\n"
            "Group files in a directory by extension using pathlib.\n\n"
            "## Summary\n\n"
            "Path objects are immutable values. Prefer them over raw strings for any "
            "script that touches the filesystem. Join with `/`, inspect with `.name` and "
            ".suffix`, walk with `rglob`, and always set `encoding='utf-8'` for text."
        ),
    },
    {
        "slug": "02_regex_basics",
        "track": "automations",
        "difficulty": "easy",
        "title": "Regular Expressions in Python",
        "tags": ["regex", "re"],
        "exercise": "content/problems/automations/easy/02_extract_emails.py",
        "body": (
            "# Regular Expressions in Python\n\n"
            "## Overview\n\n"
            "The `re` module matches patterns in text. Automations use regex for log "
            "parsing, validation, extraction, and cleanup — but prefer simpler tools "
            "(split, str methods) when they suffice.\n\n"
            "A regular expression is a tiny language for describing text shapes: digits, "
            "word characters, optional parts, repeated sections. You do not need to "
            "memorize every feature on day one — start with `search`, `findall`, and "
            "named groups, then grow from there.\n\n"
            "Rule of thumb: if `text.startswith`, `in`, or `split` solves the problem, "
            "skip regex. Reach for it when the structure varies (emails, IPs, log fields).\n\n"
            "## Your first pattern\n\n"
            "Suppose you want the first number in a string:\n\n"
            "```python\n"
            "import re\n\n"
            "text = 'Order 42 shipped to ada@example.com'\n"
            "match = re.search(r'\\d+', text)\n"
            "if match:\n"
            "    print(match.group())   # '42'\n"
            "    print(match.start())   # 6 — index where match begins\n"
            "```\n\n"
            "Read `r'\\d+'` as: one or more digits. The `r` prefix is a raw string — "
            "backslashes are passed to the regex engine without Python eating them first.\n\n"
            "## Core functions\n\n"
            "Four functions cover most automation tasks:\n\n"
            "```python\n"
            "import re\n\n"
            "text = 'Order 42 shipped to ada@example.com'\n\n"
            "re.search(r'\\d+', text)            # first match or None\n"
            "re.findall(r'\\w+@\\w+', text)       # all matches as strings\n"
            "re.sub(r'\\s+', ' ', text)          # replace every match\n"
            "re.split(r'[,;]', 'a,b;c')           # split on pattern\n"
            "```\n\n"
            "Use raw strings `r'...'` so backslashes behave as regex expects. In "
            "`r'\\d+'`, Python passes `\\d+` to the regex engine (digit, one or more).\n\n"
            "Three ways to anchor a match:\n\n"
            "```python\n"
            "re.match(r'\\d+', text)      # only at the start of the string\n"
            "re.search(r'\\d+', text)     # anywhere in the string\n"
            "re.fullmatch(r'\\d+', '42')  # entire string must match\n"
            "```\n\n"
            "`match` is often the wrong choice — most beginners want `search` or "
            "`fullmatch`. Use `fullmatch` when validating a whole line (a zip code, "
            "an ID).\n\n"
            "## Groups and capture\n\n"
            "Parentheses capture parts of a match. Named groups make extraction readable:\n\n"
            "```python\n"
            "email = 'ada.lovelace@example.co.uk'\n"
            "m = re.search(r'(?P<user>[\\w.+-]+)@(?P<domain>[\\w.-]+)', email)\n"
            "if m:\n"
            "    print(m.group('user'))    # 'ada.lovelace'\n"
            "    print(m.group('domain'))  # 'example.co.uk'\n"
            "    print(m.group(0))         # full match\n"
            "```\n\n"
            "Always check `if m:` before calling `group()` — otherwise you get "
            "`AttributeError: 'NoneType' object has no attribute 'group'`.\n\n"
            "Extract area code and local number from a phone string:\n\n"
            "```python\n"
            "PHONE = re.compile(r'\\((?P<area>\\d{3})\\) (?P<local>\\d{3}-\\d{4})')\n"
            "m = PHONE.search('Call (555) 123-4567 today')\n"
            "if m:\n"
            "    print(m['area'], m['local'])   # same as group('area')\n"
            "```\n\n"
            "## Common pattern building blocks\n\n"
            "| Token | Meaning        | Example match   |\n"
            "|-------|----------------|-----------------|\n"
            "| `.`   | any char       | `a`, `9`, space |\n"
            "| `\\d`  | digit          | `0`–`9`         |\n"
            "| `\\w`  | word char      | `a`, `_`, `9`   |\n"
            "| `\\s`  | whitespace     | space, tab      |\n"
            "| `+`   | one or more    | `\\d+` → `42`   |\n"
            "| `*`   | zero or more   | `\\d*` → `` or `7` |\n"
            "| `?`   | optional       | `-?\\d` → `5` or `-5` |\n"
            "| `^` `$`| start / end   | `^OK$` whole line |\n"
            "| `[]`  | char class     | `[aeiou]` vowel |\n\n"
            "Square brackets list allowed characters. `[^\\d]` means not a digit.\n\n"
            "Practice reading patterns aloud:\n\n"
            "```python\n"
            "r'^ERROR \\d{4}-\\d{2}-\\d{2}'   # line starts with ERROR and a date\n"
            "r'\\bpython\\b'                  # whole word python, not xpythony\n"
            "r'file_\\d{3}\\.txt'             # file_001.txt, file_042.txt\n"
            "```\n\n"
            "## Worked example: extract emails from a blob\n\n"
            "Start simple, then tighten the pattern as you see edge cases:\n\n"
            "```python\n"
            "import re\n\n"
            "blob = '''\n"
            "Contact ada@example.com or support@my-company.io.\n"
            "Invalid: not-an-email@\n"
            "Also: bob.smith+tag@mail.org\n"
            "'''\n\n"
            "EMAIL = re.compile(r'[\\w.+-]+@[\\w.-]+\\.[a-zA-Z]{2,}')\n"
            "found = EMAIL.findall(blob)\n"
            "print(found)\n"
            "# ['ada@example.com', 'support@my-company.io', 'bob.smith+tag@mail.org']\n"
            "```\n\n"
            "Step by step:\n"
            "1. `re.compile` builds the pattern once — reuse it when scanning many lines.\n"
            "2. `[\\w.+-]+` allows letters, digits, dots, plus, hyphen in the local part.\n"
            "3. `[a-zA-Z]{2,}` requires a TLD of at least two letters.\n"
            "4. `findall` returns plain strings; use `finditer` if you need match objects.\n\n"
            "Deduplicate while preserving order:\n\n"
            "```python\n"
            "def unique_emails(text: str) -> list[str]:\n"
            "    seen: set[str] = set()\n"
            "    result: list[str] = []\n"
            "    for addr in EMAIL.findall(text):\n"
            "        key = addr.lower()\n"
            "        if key not in seen:\n"
            "            seen.add(key)\n"
            "            result.append(addr)\n"
            "    return result\n"
            "```\n\n"
            "## Worked example: parse a log line\n\n"
            "Logs often follow a fixed template with variable fields:\n\n"
            "```python\n"
            "import re\n\n"
            "LINE = re.compile(\n"
            "    r'^(?P<level>\\w+) (?P<ts>\\d{4}-\\d{2}-\\d{2}) '\n"
            "    r'(?P<msg>.+)$'\n"
            ")\n"
            "line = 'ERROR 2026-06-30 Disk full on /var'\n"
            "m = LINE.search(line)\n"
            "if m:\n"
            "    record = m.groupdict()\n"
            "    if record['level'] == 'ERROR':\n"
            "        print(record['msg'])\n"
            "```\n\n"
            "`groupdict()` returns `{'level': 'ERROR', 'ts': '2026-06-30', ...}` — "
            "handy for feeding into CSV or JSON output.\n\n"
            "Process a whole log file:\n\n"
            "```python\n"
            "from pathlib import Path\n\n"
            "def error_messages(path: Path) -> list[str]:\n"
            "    errors = []\n"
            "    for line in path.read_text(encoding='utf-8').splitlines():\n"
            "        m = LINE.search(line)\n"
            "        if m and m['level'] == 'ERROR':\n"
            "            errors.append(m['msg'])\n"
            "    return errors\n"
            "```\n\n"
            "## Worked example: clean messy whitespace\n\n"
            "Regex shines at repetitive cleanup:\n\n"
            "```python\n"
            "import re\n\n"
            "messy = '  hello\\t\\tworld  \\n\\n  foo  '\n"
            "cleaned = re.sub(r'\\s+', ' ', messy).strip()\n"
            "print(cleaned)   # 'hello world foo'\n"
            "```\n\n"
            "Remove HTML tags (simple cases only):\n\n"
            "```python\n"
            "html = '<p>Hi <b>there</b></p>'\n"
            "plain = re.sub(r'<[^>]+>', '', html)\n"
            "print(plain)   # 'Hi there'\n"
            "```\n\n"
            "## Compiling for reuse\n\n"
            "When the same pattern runs hundreds of times, compile it once:\n\n"
            "```python\n"
            "EMAIL = re.compile(r'[\\w.+-]+@[\\w.-]+\\.[a-zA-Z]{2,}')\n"
            "for line in path.read_text().splitlines():\n"
            "    for addr in EMAIL.findall(line):\n"
            "        print(addr)\n"
            "```\n\n"
            "Flags modify behavior. Common ones:\n\n"
            "```python\n"
            "re.compile(r'^start', re.MULTILINE)   # ^ matches each line\n"
            "re.compile(r'foo', re.IGNORECASE)     # case-insensitive\n"
            "re.compile(r'#.*$', re.MULTILINE)     # strip end-of-line comments\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Over-using regex for fixed-string replace (`str.replace`)\n"
            "- Catastrophic backtracking on nested quantifiers — keep patterns simple\n"
            "- Forgetting `re.MULTILINE` when `^`/`$` must match line boundaries\n"
            "- Greedy `.*` swallowing too much — use non-greedy `.*?` or explicit groups\n"
            "- Validating emails with one giant regex — extract first, validate later\n"
            "- Testing only happy paths — feed real messy data from production logs\n\n"
            "## Practice\n\n"
            "Extract email addresses from a block of text.\n\n"
            "## Summary\n\n"
            "Regex excels at semi-structured text. Test patterns on real samples; "
            "compile once when scanning many lines. Start with `search` and `findall`, "
            "use named groups for clarity, and prefer simpler string tools when they fit."
        ),
    },
    {
        "slug": "03_csv_json_files",
        "track": "automations",
        "difficulty": "easy",
        "title": "CSV, JSON, and Line-Oriented Files",
        "tags": ["csv", "json", "files"],
        "exercise": "content/problems/automations/easy/13_json_lines_parse.py",
        "body": (
            "# CSV, JSON, and Line-Oriented Files\n\n"
            "## Overview\n\n"
            "Most automation scripts ingest or emit structured text: CSV spreadsheets, "
            "JSON configs, JSON Lines logs. Python's stdlib handles all three without "
            "extra dependencies.\n\n"
            "Choosing a format is usually not your decision — the data arrives as CSV "
            "from a spreadsheet export, JSON from an API, or JSONL from a log pipeline. "
            "Your job is to parse it safely, transform it, and write it back without "
            "corrupting structure (embedded commas, unicode, nested fields).\n\n"
            "This lesson walks through each format with small examples, then combines "
            "them in a realistic pipeline.\n\n"
            "## JSON: Python values ↔ text\n\n"
            "JSON maps closely to Python: objects → dict, arrays → list, strings, numbers, "
            "booleans, and `null` → `None`.\n\n"
            "```python\n"
            "import json\n\n"
            "data = {'name': 'Ada', 'scores': [98, 87], 'active': True}\n"
            "text = json.dumps(data, indent=2)   # Python → string\n"
            "back = json.loads(text)             # string → Python\n"
            "```\n\n"
            "Read and write files with `load` / `dump` (note the `f`):\n\n"
            "```python\n"
            "from pathlib import Path\n\n"
            "config_path = Path('config.json')\n"
            "with config_path.open(encoding='utf-8') as f:\n"
            "    config = json.load(f)\n\n"
            "config['debug'] = True\n"
            "with config_path.open('w', encoding='utf-8') as f:\n"
            "    json.dump(config, f, indent=2)\n"
            "```\n\n"
            "JSON requires double quotes; keys in objects must be strings. Trailing "
            "commas and comments are not valid JSON.\n\n"
            "Beginner tip: `loads`/`dumps` work on strings; `load`/`dump` work on "
            "file objects. The extra `s` means string.\n\n"
            "Pretty-print for humans, compact for APIs:\n\n"
            "```python\n"
            "json.dumps(data)                          # compact one-liner\n"
            "json.dumps(data, indent=2)                # readable config file\n"
            "json.dumps(data, ensure_ascii=False)      # keep é, ñ, 中文 as-is\n"
            "```\n\n"
            "## JSON Lines (JSONL)\n\n"
            "One JSON object per line — common for logs and ML datasets. Each line is "
            "independent, so you can stream huge files without loading everything:\n\n"
            "```python\n"
            "import json\n"
            "from pathlib import Path\n\n"
            "def load_jsonl(path: Path) -> list[dict]:\n"
            "    records = []\n"
            "    for line in path.read_text(encoding='utf-8').splitlines():\n"
            "        line = line.strip()\n"
            "        if line:\n"
            "            records.append(json.loads(line))\n"
            "    return records\n"
            "```\n\n"
            "Write JSONL the same way — one `dumps` call per line:\n\n"
            "```python\n"
            "def save_jsonl(path: Path, records: list[dict]) -> None:\n"
            "    lines = [json.dumps(r, ensure_ascii=False) for r in records]\n"
            "    path.write_text('\\n'.join(lines) + '\\n', encoding='utf-8')\n"
            "```\n\n"
            "Stream a large file without building a giant list:\n\n"
            "```python\n"
            "def iter_jsonl(path: Path):\n"
            "    with path.open(encoding='utf-8') as f:\n"
            "        for line in f:\n"
            "            line = line.strip()\n"
            "            if line:\n"
            "                yield json.loads(line)\n\n"
            "for event in iter_jsonl(Path('events.jsonl')):\n"
            "    if event.get('level') == 'ERROR':\n"
            "        print(event['message'])\n"
            "```\n\n"
            "## CSV: tabular data\n\n"
            "CSV files look like spreadsheets: a header row, then data rows. Use the "
            "`csv` module — never split on commas by hand (fields can contain commas "
            "inside quotes).\n\n"
            "Why not `line.split(',')`? This row breaks naive splitting:\n\n"
            "```\n"
            'Ada,"123 Main St, Apt 4",120\n'
            "```\n\n"
            "The address field contains a comma inside quotes. `csv` handles that.\n\n"
            "Reading rows as dictionaries (column name → value):\n\n"
            "```python\n"
            "import csv\n"
            "from pathlib import Path\n\n"
            "with Path('data.csv').open(newline='', encoding='utf-8') as f:\n"
            "    reader = csv.DictReader(f)\n"
            "    for row in reader:\n"
            "        print(row['name'], row['amount'])\n"
            "```\n\n"
            "Writing a CSV from scratch:\n\n"
            "```python\n"
            "rows = [\n"
            "    {'name': 'Ada', 'amount': '120'},\n"
            "    {'name': 'Grace', 'amount': '95'},\n"
            "]\n"
            "with Path('out.csv').open('w', newline='', encoding='utf-8') as f:\n"
            "    writer = csv.DictWriter(f, fieldnames=['name', 'amount'])\n"
            "    writer.writeheader()\n"
            "    writer.writerows(rows)\n"
            "```\n\n"
            "Always open CSV with `newline=''` to avoid extra blank lines on Windows.\n\n"
            "Convert string columns to numbers after reading:\n\n"
            "```python\n"
            "def load_sales(path: Path) -> list[dict]:\n"
            "    with path.open(newline='', encoding='utf-8') as f:\n"
            "        reader = csv.DictReader(f)\n"
            "        return [\n"
            "            {**row, 'amount': int(row['amount'])}\n"
            "            for row in reader\n"
            "        ]\n"
            "```\n\n"
            "`DictReader` returns every value as a string — convert numbers yourself.\n\n"
            "## Worked example: JSONL log → summary CSV\n\n"
            "Combine formats in a typical pipeline — read events, aggregate, export:\n\n"
            "```python\n"
            "import csv\n"
            "import json\n"
            "from collections import Counter\n"
            "from pathlib import Path\n\n"
            "def summarize_events(jsonl_path: Path, csv_path: Path) -> None:\n"
            "    counts: Counter[str] = Counter()\n"
            "    for line in jsonl_path.read_text(encoding='utf-8').splitlines():\n"
            "        if not line.strip():\n"
            "            continue\n"
            "        event = json.loads(line)\n"
            "        counts[event['type']] += 1\n\n"
            "    with csv_path.open('w', newline='', encoding='utf-8') as f:\n"
            "        writer = csv.writer(f)\n"
            "        writer.writerow(['type', 'count'])\n"
            "        for event_type, count in counts.most_common():\n"
            "            writer.writerow([event_type, count])\n"
            "```\n\n"
            "Step by step:\n"
            "1. Stream the JSONL file line by line (memory-safe).\n"
            "2. `json.loads` each non-empty line into a dict.\n"
            "3. Tally with `Counter`.\n"
            "4. Write a simple two-column CSV with `csv.writer`.\n\n"
            "Sample input (`events.jsonl`):\n\n"
            "```json\n"
            "{\"type\": \"click\", \"user\": \"ada\"}\n"
            "{\"type\": \"view\", \"user\": \"bob\"}\n"
            "{\"type\": \"click\", \"user\": \"ada\"}\n"
            "```\n\n"
            "Output (`summary.csv`):\n\n"
            "```\n"
            "type,count\n"
            "click,2\n"
            "view,1\n"
            "```\n\n"
            "## Worked example: merge JSON config with CSV defaults\n\n"
            "Sometimes automation reads a JSON config and a CSV lookup table:\n\n"
            "```python\n"
            "import csv\n"
            "import json\n"
            "from pathlib import Path\n\n"
            "def load_role_map(csv_path: Path) -> dict[str, str]:\n"
            "    with csv_path.open(newline='', encoding='utf-8') as f:\n"
            "        return {row['email']: row['role'] for row in csv.DictReader(f)}\n\n"
            "config = json.loads(Path('config.json').read_text(encoding='utf-8'))\n"
            "roles = load_role_map(Path('roles.csv'))\n"
            "admin_emails = [e for e, r in roles.items() if r == 'admin']\n"
            "config['notify'] = admin_emails\n"
            "Path('config.json').write_text(\n"
            "    json.dumps(config, indent=2), encoding='utf-8'\n"
            ")\n"
            "```\n\n"
            "## When to use which\n\n"
            "| Format | Good for                    | Avoid when…              |\n"
            "|--------|-----------------------------|--------------------------|\n"
            "| CSV    | tabular exports, spreadsheets| deeply nested data      |\n"
            "| JSON   | nested configs, APIs        | multi-GB single blob     |\n"
            "| JSONL  | streaming logs, big datasets| you need one array file  |\n\n"
            "## Common pitfalls\n\n"
            "- `json.loads` on empty string raises — guard with `strip()`\n"
            "- CSV with embedded commas needs proper quoting (use csv module)\n"
            "- Loading multi-GB JSON into memory — stream JSONL line by line\n"
            "- `json.dump` without `ensure_ascii=False` escapes non-ASCII as `\\uXXXX`\n"
            "- DictReader returns every value as a string — convert numbers yourself\n"
            "- Forgetting `newline=''` on CSV — extra blank lines on Windows\n"
            "- Assuming JSON from the web is valid — wrap `loads` in try/except\n\n"
            "## Practice\n\n"
            "Parse JSON Lines into a list of dicts.\n\n"
            "## Summary\n\n"
            "Pick the format your data already uses; use stdlib readers instead of "
            "manual splitting when structure matters. JSON for nested configs, CSV for "
            "tables, JSONL for streams — and always set `encoding='utf-8'` plus "
            "`newline=''` for CSV."
        ),
    },
]
