"""Beautiful Soup track lesson guides."""

LESSONS = [
    {
        "slug": "01_bs4_intro",
        "track": "bs4",
        "difficulty": "easy",
        "title": "Beautiful Soup Basics",
        "tags": ["bs4", "html"],
        "exercise": "content/problems/bs4/easy/01_parse_first_tag.py",
        "body": (
            "# Beautiful Soup Basics\n\n"
            "## Overview\n\n"
            "Beautiful Soup turns HTML and XML into a tree of Python objects you can "
            "search, traverse, and modify. It is the go-to library when you need to "
            "extract data from web pages, email templates, or exported reports.\n\n"
            "You do not need to understand the full HTML spec. Beautiful Soup repairs "
            "common markup mistakes and gives you Python methods to find the pieces "
            "you care about.\n\n"
            "Real-world uses:\n\n"
            "- Scraping product prices from an e-commerce page\n"
            "- Parsing HTML email digests for headlines and links\n"
            "- Extracting table rows from a saved financial report\n"
            "- Cleaning messy markup before feeding it to another tool\n\n"
            "Install with `pip install beautifulsoup4`. You also need a parser:\n\n"
            "| Parser        | Install          | Speed   | Notes                    |\n"
            "|---------------|------------------|---------|--------------------------|\n"
            "| `html.parser` | built-in         | moderate| good default, no extras  |\n"
            "| `lxml`        | `pip install lxml` | fast  | best for large documents |\n"
            "| `html5lib`    | `pip install html5lib` | slow | most lenient parsing |\n\n"
            "## Parse a document\n\n"
            "```python\n"
            "from bs4 import BeautifulSoup\n\n"
            "html = '<p class=\"lead\">Hello</p>'\n"
            "soup = BeautifulSoup(html, 'html.parser')\n"
            "tag = soup.find('p')\n"
            "print(tag.name)        # p\n"
            "print(tag.get_text())  # Hello\n"
            "print(tag['class'])    # ['lead']\n"
            "```\n\n"
            "The **first tag** in the document is available as `soup.contents[0]` "
            "(skipping the root `[document]` node) or via `find()`. The exercise asks "
            "you to identify that first tag's name.\n\n"
            "```python\n"
            "first = soup.find()          # first tag in the tree\n"
            "first.name                   # e.g. 'p', 'html', 'div'\n"
            "```\n\n"
            "## The parse tree mental model\n\n"
            "Think of HTML as nested boxes:\n\n"
            "```\n"
            "html\n"
            " └── body\n"
            "      ├── h1  (\"Products\")\n"
            "      └── ul\n"
            "           ├── li → a (\"Shoes\")\n"
            "           └── li → a (\"Hats\")\n"
            "```\n\n"
            "Every element is a `Tag`. Text between tags is a `NavigableString`. "
            "You navigate with `.parent`, `.children`, `.next_sibling`, and search "
            "methods like `.find()` and `.find_all()`.\n\n"
            "```python\n"
            "link = soup.find('a')\n"
            "link.name           # 'a'\n"
            "link.string         # direct text child, or None\n"
            "link.parent.name    # 'li'\n"
            "link['href']        # attribute value\n"
            "```\n\n"
            "## Finding elements\n\n"
            "### By tag name\n\n"
            "```python\n"
            "soup.find('title')            # first <title>, or None\n"
            "soup.find_all('a')            # list of every <a>\n"
            "soup.find_all('li', limit=5)  # stop after 5 matches\n"
            "soup.find_all(['h1', 'h2'])   # all h1 and h2 tags\n"
            "```\n\n"
            "`find` returns **one** tag or `None`. `find_all` always returns a **list** "
            "(possibly empty).\n\n"
            "### By attribute\n\n"
            "HTML `class` is a reserved word in Python, so use `class_`:\n\n"
            "```python\n"
            "soup.find(id='main-content')\n"
            "soup.find_all(class_='product-card')\n"
            "soup.find('input', attrs={'name': 'email', 'type': 'text'})\n"
            "soup.find('div', {'data-id': '42'})   # shorthand for attrs\n"
            "```\n\n"
            "The `class` attribute is often a **list** of class names:\n\n"
            "```python\n"
            "tag = soup.find(class_='btn')\n"
            "tag['class']   # ['btn', 'primary', 'large']\n"
            "'primary' in tag.get('class', [])   # safe membership check\n"
            "```\n\n"
            "### CSS selectors\n\n"
            "If you know CSS, `select` is often the clearest option:\n\n"
            "```python\n"
            "soup.select_one('p.lead')               # first <p class=\"lead\">\n"
            "soup.select('ul.menu li a')             # all links inside menu lists\n"
            "soup.select('div.product span.price')   # prices inside product divs\n"
            "soup.select('[data-sku]')               # any element with data-sku attr\n"
            "```\n\n"
            "## Worked example: scrape a product list\n\n"
            "```python\n"
            "html = '''\n"
            "<ul class=\"products\">\n"
            "  <li data-sku=\"A1\"><span class=\"name\">Widget</span><span class=\"price\">$9.99</span></li>\n"
            "  <li data-sku=\"B2\"><span class=\"name\">Gadget</span><span class=\"price\">$14.50</span></li>\n"
            "</ul>\n"
            "'''\n"
            "soup = BeautifulSoup(html, 'html.parser')\n"
            "products = []\n"
            "for item in soup.select('ul.products li'):\n"
            "    products.append({\n"
            "        'sku': item['data-sku'],\n"
            "        'name': item.select_one('.name').get_text(strip=True),\n"
            "        'price': item.select_one('.price').get_text(strip=True),\n"
            "    })\n"
            "# [{'sku': 'A1', 'name': 'Widget', 'price': '$9.99'},\n"
            "#  {'sku': 'B2', 'name': 'Gadget', 'price': '$14.50'}]\n"
            "```\n\n"
            "This pattern — loop containers, extract fields with `select_one` — "
            "covers most scraping tasks.\n\n"
            "## Worked example: HTML table to list of dicts\n\n"
            "Reports and dashboards often use `<table>`:\n\n"
            "```python\n"
            "html = '''\n"
            "<table>\n"
            "  <tr><th>Name</th><th>Score</th></tr>\n"
            "  <tr><td>Ada</td><td>98</td></tr>\n"
            "  <tr><td>Grace</td><td>95</td></tr>\n"
            "</table>\n"
            "'''\n"
            "soup = BeautifulSoup(html, 'html.parser')\n"
            "rows = soup.find('table').find_all('tr')\n"
            "headers = [th.get_text(strip=True) for th in rows[0].find_all('th')]\n"
            "records = []\n"
            "for row in rows[1:]:\n"
            "    cells = [td.get_text(strip=True) for td in row.find_all('td')]\n"
            "    records.append(dict(zip(headers, cells)))\n"
            "# [{'Name': 'Ada', 'Score': '98'}, {'Name': 'Grace', 'Score': '95'}]\n"
            "```\n\n"
            "## Text extraction\n\n"
            "```python\n"
            "tag.get_text()               # all text, including children\n"
            "tag.get_text(strip=True)     # trim whitespace on each piece\n"
            "tag.get_text(separator=' ')  # join fragments with a space\n"
            "tag.get_text(separator='\\n', strip=True)  # one line per block\n"
            "```\n\n"
            "**Cleaning invisible junk:** scripts and styles hold text you usually "
            "do not want. Remove them before extracting visible text:\n\n"
            "```python\n"
            "for bad in soup(['script', 'style', 'noscript']):\n"
            "    bad.decompose()  # remove from tree entirely\n"
            "visible = soup.get_text(separator='\\n', strip=True)\n"
            "```\n\n"
            "## Traversing the tree\n\n"
            "```python\n"
            "link = soup.find('a')\n"
            "link['href']              # attribute value\n"
            "link.parent.name          # enclosing tag name\n"
            "link.next_sibling         # node after this tag (may be whitespace)\n"
            "link.find_next('span')    # next <span> anywhere after this tag\n"
            "list(link.children)       # direct child nodes\n"
            "link.descendants          # all nested nodes (generator)\n"
            "```\n\n"
            "Whitespace between tags becomes `NavigableString` nodes — use "
            "`.strip()` or `get_text(strip=True)` to ignore them.\n\n"
            "## Worked example: extract all links\n\n"
            "```python\n"
            "page = '''\n"
            "<html><body>\n"
            "  <a href=\"/home\">Home</a>\n"
            "  <a href=\"https://example.com/docs\">Docs</a>\n"
            "  <a href=\"/about\">About</a>\n"
            "</body></html>\n"
            "'''\n"
            "soup = BeautifulSoup(page, 'html.parser')\n"
            "links = [\n"
            "    {'text': a.get_text(strip=True), 'href': a['href']}\n"
            "    for a in soup.find_all('a', href=True)\n"
            "]\n"
            "# [{'text': 'Home', 'href': '/home'}, ...]\n"
            "```\n\n"
            "Use `href=True` to skip anchor tags without an href attribute.\n\n"
            "## Real-world scenario: price change monitor\n\n"
            "```python\n"
            "import httpx\n"
            "from bs4 import BeautifulSoup\n\n"
            "def fetch_price(url: str, selector: str) -> str:\n"
            "    r = httpx.get(url, timeout=10, follow_redirects=True)\n"
            "    r.raise_for_status()\n"
            "    soup = BeautifulSoup(r.text, 'html.parser')\n"
            "    el = soup.select_one(selector)\n"
            "    if el is None:\n"
            "        raise ValueError(f'selector not found: {selector}')\n"
            "    return el.get_text(strip=True)\n\n"
            "# price = fetch_price('https://shop.example/item/42', 'span.price')\n"
            "```\n\n"
            "Always respect `robots.txt`, terms of service, and rate limits when "
            "scraping live sites. Cache responses during development.\n\n"
            "## Parsing from a file or HTTP response\n\n"
            "```python\n"
            "from pathlib import Path\n"
            "html = Path('report.html').read_text(encoding='utf-8')\n"
            "soup = BeautifulSoup(html, 'html.parser')\n"
            "```\n\n"
            "With httpx:\n\n"
            "```python\n"
            "import httpx\n"
            "from bs4 import BeautifulSoup\n\n"
            "r = httpx.get('https://example.com', timeout=10)\n"
            "r.raise_for_status()\n"
            "soup = BeautifulSoup(r.text, 'html.parser')\n"
            "```\n\n"
            "Always specify encoding when reading files (`utf-8` is typical).\n\n"
            "## Defensive scraping\n\n"
            "Websites change layout. Write selectors that fail loudly:\n\n"
            "```python\n"
            "def safe_text(soup, selector: str, default: str = '') -> str:\n"
            "    el = soup.select_one(selector)\n"
            "    return el.get_text(strip=True) if el else default\n\n"
            "name = safe_text(soup, 'span.product-name')\n"
            "if not name:\n"
            "    print('warning: product name missing — page layout may have changed')\n"
            "```\n\n"
            "## Modifying the tree\n\n"
            "Beautiful Soup can also build or fix HTML:\n\n"
            "```python\n"
            "new_tag = soup.new_tag('b')\n"
            "new_tag.string = 'important'\n"
            "soup.find('p').append(new_tag)\n"
            "print(soup.prettify())\n"
            "```\n\n"
            "Useful when generating email HTML or normalizing broken markup.\n\n"
            "## find vs find_all vs select\n\n"
            "| Method       | Returns              | Best for                    |\n"
            "|--------------|----------------------|-----------------------------|\n"
            "| `find`       | first match or None  | single element              |\n"
            "| `find_all`   | list (maybe empty)   | all matches, filter by attr |\n"
            "| `select`     | list via CSS         | complex nested selectors    |\n"
            "| `select_one` | first CSS match      | one element by CSS          |\n\n"
            "## Common pitfalls\n\n"
            "- Using `class=` instead of `class_=` (syntax error)\n"
            "- Expecting `find` to return a list (it returns one tag or `None`)\n"
            "- Forgetting that blank lines between tags are text nodes\n"
            "- Treating `class` as a string when it can be a list\n"
            "- Assuming HTML structure never changes — write defensive selectors\n"
            "- Not specifying encoding when reading files\n"
            "- Calling `.get_text()` on `None` because `find` returned nothing\n\n"
            "## Practice\n\n"
            "Parse HTML and return the name of the first tag.\n\n"
            "## Summary\n\n"
            "Beautiful Soup turns markup into a searchable tree. Parse with "
            "`BeautifulSoup(html, 'html.parser')`, locate elements with `find`, "
            "`find_all`, or `select`, and extract data with `.get_text(strip=True)` "
            "and attribute access. Loop container elements and pull fields — that "
            "pattern scales to real scraping jobs."
        ),
    },
]
