"""Click track lesson guides."""

LESSONS = [
    {
        "slug": "01_click_intro",
        "track": "click",
        "difficulty": "easy",
        "title": "Click CLI Basics",
        "tags": ["click", "cli"],
        "exercise": "content/problems/click/easy/01_option_greet.py",
        "body": (
            "# Click CLI Basics\n\n"
            "## Overview\n\n"
            "Click is Python's most popular library for building command-line interfaces. "
            "Instead of manually parsing `sys.argv`, you decorate functions with "
            "`@click.command()`, `@click.option()`, and `@click.argument()` — Click "
            "handles parsing, help text, and error messages for you.\n\n"
            "Before Click, CLI code looked like this:\n\n"
            "```python\n"
            "import sys\n"
            "name = 'world'\n"
            "for i, arg in enumerate(sys.argv[1:]):\n"
            "    if arg == '--name' and i + 1 < len(sys.argv):\n"
            "        name = sys.argv[i + 1]\n"
            "print(f'Hello {name}!')\n"
            "```\n\n"
            "Click replaces that boilerplate with declarative decorators and gives you "
            "`--help` for free.\n\n"
            "Real-world uses:\n\n"
            "- Deployment scripts (`deploy --env staging`)\n"
            "- Data tools (`csv-tool merge a.csv b.csv --output out.csv`)\n"
            "- Dev utilities (`lint --fix`, `seed-db --count 100`)\n"
            "- Packaging CLI entry points in `pyproject.toml`\n\n"
            "Install with `pip install click`. Test CLIs with `CliRunner` — no "
            "subprocess, no real terminal required.\n\n"
            "## A simple command\n\n"
            "```python\n"
            "import click\n\n"
            "@click.command()\n"
            "@click.option('--name', default='world', help='Who to greet.')\n"
            "def greet(name):\n"
            "    click.echo(f'Hello {name}!')\n\n"
            "if __name__ == '__main__':\n"
            "    greet()\n"
            "```\n\n"
            "Run it:\n\n"
            "```bash\n"
            "python greet.py                  # Hello world!\n"
            "python greet.py --name Ada         # Hello Ada!\n"
            "python greet.py --help             # shows options and defaults\n"
            "```\n\n"
            "**Exercise pattern:** return a command from a factory function:\n\n"
            "```python\n"
            "def make_greet_command():\n"
            "    @click.command()\n"
            "    @click.option('--name', default='world')\n"
            "    def greet(name):\n"
            "        click.echo(f'Hello {name}!')\n"
            "    return greet\n"
            "```\n\n"
            "`click.echo()` is preferred over `print()` because it handles encoding "
            "and Unicode correctly across platforms (especially Windows).\n\n"
            "## Options vs arguments\n\n"
            "- **Options** (`--flag`, `-f`) are usually optional and named\n"
            "- **Arguments** are positional and often required\n\n"
            "```python\n"
            "@click.command()\n"
            "@click.argument('filename')\n"
            "@click.option('--verbose', '-v', is_flag=True, help='More output.')\n"
            "def process(filename, verbose):\n"
            "    if verbose:\n"
            "        click.echo(f'Processing {filename}...')\n"
            "    click.echo('done')\n"
            "```\n\n"
            "```bash\n"
            "python process.py data.csv -v\n"
            "python process.py --help\n"
            "```\n\n"
            "Think of arguments as nouns (what to act on) and options as modifiers "
            "(how to act).\n\n"
            "## Typed options\n\n"
            "Click converts strings from the shell to Python types automatically:\n\n"
            "```python\n"
            "@click.command()\n"
            "@click.option('--count', default=1, type=int, help='Number of greetings.')\n"
            "@click.option('--name', default='world')\n"
            "def greet(count, name):\n"
            "    for _ in range(count):\n"
            "        click.echo(f'Hello {name}!')\n"
            "```\n\n"
            "Invalid input produces a friendly error:\n\n"
            "```bash\n"
            "python greet.py --count abc\n"
            "# Error: Invalid value for '--count': 'abc' is not a valid integer.\n"
            "```\n\n"
            "Useful built-in types:\n\n"
            "| Type                         | Validates                    |\n"
            "|------------------------------|------------------------------|\n"
            "| `int`, `float`, `str`        | Basic Python types           |\n"
            "| `click.Path(exists=True)`    | File or directory exists     |\n"
            "| `click.Choice(['a', 'b'])`   | Value in allowed list        |\n"
            "| `click.DateTime()`           | Parses date strings          |\n\n"
            "```python\n"
            "@click.option('--env', type=click.Choice(['dev', 'staging', 'prod']), default='dev')\n"
            "@click.argument('config', type=click.Path(exists=True))\n"
            "def deploy(config, env):\n"
            "    click.echo(f'Deploying {config} to {env}')\n"
            "```\n\n"
            "## Worked example: file line counter\n\n"
            "```python\n"
            "import click\n\n"
            "@click.command()\n"
            "@click.argument('path', type=click.Path(exists=True, dir_okay=False))\n"
            "@click.option('--max', default=None, type=int, help='Stop after N lines.')\n"
            "def linecount(path, max):\n"
            "    with open(path, encoding='utf-8') as f:\n"
            "        for i, _ in enumerate(f, start=1):\n"
            "            if max is not None and i > max:\n"
            "                break\n"
            "    click.echo(i)\n"
            "```\n\n"
            "Click validates that the file exists **before** your function runs — "
            "you never get a confusing `FileNotFoundError` deep inside your logic.\n\n"
            "## Worked example: deploy CLI\n\n"
            "```python\n"
            "import click\n\n"
            "@click.command()\n"
            "@click.option('--env', type=click.Choice(['staging', 'prod']), required=True)\n"
            "@click.option('--dry-run', is_flag=True, help='Print plan without deploying.')\n"
            "@click.option('--version', is_flag=True, help='Show version and exit.')\n"
            "def deploy(env, dry_run, version):\n"
            "    if version:\n"
            "        click.echo('myapp 1.2.0')\n"
            "        return\n"
            "    if env == 'prod' and not dry_run:\n"
            "        click.confirm('Deploy to PRODUCTION?', abort=True)\n"
            "    action = 'Would deploy' if dry_run else 'Deploying'\n"
            "    click.echo(f'{action} to {env}...')\n"
            "```\n\n"
            "```bash\n"
            "python deploy.py --env staging --dry-run\n"
            "python deploy.py --env prod          # prompts for confirmation\n"
            "```\n\n"
            "## Testing with CliRunner\n\n"
            "Never shell out to test a CLI. `CliRunner.invoke()` calls your command "
            "in-process:\n\n"
            "```python\n"
            "from click.testing import CliRunner\n\n"
            "def test_greet_default():\n"
            "    runner = CliRunner()\n"
            "    result = runner.invoke(greet, [])\n"
            "    assert result.exit_code == 0\n"
            "    assert 'Hello world!' in result.output\n\n"
            "def test_greet_named():\n"
            "    runner = CliRunner()\n"
            "    result = runner.invoke(greet, ['--name', 'Ada'])\n"
            "    assert result.exit_code == 0\n"
            "    assert 'Ada' in result.output\n"
            "```\n\n"
            "**Testing with files:** use `CliRunner.isolated_filesystem()` or pytest "
            "`tmp_path`:\n\n"
            "```python\n"
            "def test_linecount(tmp_path):\n"
            "    f = tmp_path / 'sample.txt'\n"
            "    f.write_text('one\\ntwo\\nthree\\n', encoding='utf-8')\n"
            "    runner = CliRunner()\n"
            "    result = runner.invoke(linecount, [str(f)])\n"
            "    assert result.exit_code == 0\n"
            "    assert result.output.strip() == '3'\n"
            "```\n\n"
            "**Testing prompts:** pass `input=` to answer interactive questions:\n\n"
            "```python\n"
            "def test_deploy_prod_confirmed():\n"
            "    runner = CliRunner()\n"
            "    result = runner.invoke(deploy, ['--env', 'prod'], input='y\\n')\n"
            "    assert result.exit_code == 0\n"
            "    assert 'Deploying' in result.output\n"
            "```\n\n"
            "## Subcommands (command groups)\n\n"
            "Larger tools split into subcommands like `git commit` or `docker run`:\n\n"
            "```python\n"
            "@click.group()\n"
            "def cli():\n"
            "    \"\"\"My toolkit.\"\"\"\n\n"
            "@cli.command()\n"
            "@click.option('--name', default='world')\n"
            "def greet(name):\n"
            "    click.echo(f'Hello {name}!')\n\n"
            "@cli.command()\n"
            "def version():\n"
            "    click.echo('1.0.0')\n\n"
            "if __name__ == '__main__':\n"
            "    cli()\n"
            "```\n\n"
            "```bash\n"
            "python tool.py --help\n"
            "python tool.py greet --name Ada\n"
            "python tool.py version\n"
            "```\n\n"
            "## Environment variables\n\n"
            "Read config from the environment with `envvar=`:\n\n"
            "```python\n"
            "@click.option('--api-key', envvar='MYAPP_API_KEY', required=True)\n"
            "def upload(api_key):\n"
            "    click.echo(f'Using key ending in ...{api_key[-4:]}')\n"
            "```\n\n"
            "```bash\n"
            "export MYAPP_API_KEY=secret123\n"
            "python upload.py   # --api-key not needed on command line\n"
            "```\n\n"
            "Keeps secrets out of shell history.\n\n"
            "## Prompts and confirmations\n\n"
            "```python\n"
            "@click.command()\n"
            "def setup():\n"
            "    name = click.prompt('Project name')\n"
            "    password = click.prompt('Password', hide_input=True)\n"
            "    env = click.prompt('Environment', type=click.Choice(['staging', 'prod']))\n"
            "    if env == 'prod':\n"
            "        click.confirm('Deploy to PRODUCTION?', abort=True)\n"
            "    click.echo(f'Creating {name} in {env}')\n"
            "```\n\n"
            "## Exit codes and errors\n\n"
            "```python\n"
            "@click.command()\n"
            "def fail():\n"
            "    click.echo('Something went wrong', err=True)\n"
            "    raise SystemExit(1)\n"
            "```\n\n"
            "Or use Click's exception for formatted errors:\n\n"
            "```python\n"
            "raise click.ClickException('Config file not found')\n"
            "# prints: Error: Config file not found\n"
            "# exit code: 2\n"
            "```\n\n"
            "CliRunner captures `result.exit_code` and `result.exception`.\n\n"
            "## Typer: type hints on top of Click\n\n"
            "Typer builds on Click using annotations — great for new projects:\n\n"
            "```python\n"
            "import typer\n\n"
            "app = typer.Typer()\n\n"
            "@app.command()\n"
            "def greet(name: str = 'world'):\n"
            "    typer.echo(f'Hello {name}!')\n\n"
            "if __name__ == '__main__':\n"
            "    app()\n"
            "```\n\n"
            "Under the hood it is still Click — same `CliRunner` patterns apply.\n\n"
            "## Packaging as an installed command\n\n"
            "In `pyproject.toml`:\n\n"
            "```toml\n"
            "[project.scripts]\n"
            "mytool = \"myapp.cli:main\"\n"
            "```\n\n"
            "Where `main` is your `@click.group()` or `@click.command()` function. "
            "After `pip install -e .`, users run `mytool --help` from anywhere.\n\n"
            "## Common pitfalls\n\n"
            "- Forgetting `@click.command()` on the function you invoke\n"
            "- Option names must use `--kebab-case` or `--snake_case`, not spaces\n"
            "- Using `print()` instead of `click.echo()` (encoding issues on Windows)\n"
            "- Testing via subprocess instead of `CliRunner` (slow and brittle)\n"
            "- Boolean flags: use `is_flag=True`, not `type=bool` (Click treats "
            "`--flag False` oddly with `type=bool`)\n"
            "- Decorator order: `@click.command()` goes **below** `@click.option()` "
            "(options closest to the function)\n"
            "- Mutable default arguments in command callbacks — pass via option, "
            "not as function default list/dict\n\n"
            "## Practice\n\n"
            "Return a click command with a `--name` option.\n\n"
            "## Summary\n\n"
            "Click = decorators for commands, options, and arguments + automatic `--help`. "
            "Test with `CliRunner.invoke()` in pytest. Start with a single `@click.command()`, "
            "add typed options, then grow into `@click.group()` subcommands as your tool "
            "gets bigger. Typer offers the same runtime with type-hint ergonomics."
        ),
    },
]
