"""FastAPI track lesson guides."""

LESSONS = [
    {
        "slug": "01_fastapi_basics",
        "track": "fastapi",
        "difficulty": "easy",
        "title": "FastAPI Basics",
        "tags": ["fastapi", "http"],
        "exercise": "content/problems/fastapi/easy/01_hello_route.py",
        "body": (
            "# FastAPI Basics\n\n"
            "## Overview\n\n"
            "FastAPI is a modern Python web framework for building APIs. It uses type "
            "hints for automatic validation, generates interactive OpenAPI docs, and "
            "runs on ASGI servers like Uvicorn (async-capable, high performance).\n\n"
            "You write ordinary Python functions with type annotations; FastAPI turns "
            "them into HTTP endpoints with JSON request/response handling.\n\n"
            "Real-world uses:\n\n"
            "- REST backends for web and mobile apps\n"
            "- Internal microservices behind a gateway\n"
            "- Webhook receivers (Stripe, GitHub, Slack)\n"
            "- ML model serving endpoints\n\n"
            "Install with `pip install fastapi uvicorn`.\n\n"
            "## Minimal app\n\n"
            "```python\n"
            "from fastapi import FastAPI\n\n"
            "app = FastAPI()\n\n"
            "@app.get('/')\n"
            "def root():\n"
            "    return {'message': 'hello'}\n"
            "```\n\n"
            "Return dicts, lists, or Pydantic models — FastAPI serializes them to JSON "
            "automatically. You do not need to call `json.dumps()` yourself.\n\n"
            "Run locally:\n\n"
            "```bash\n"
            "uvicorn main:app --reload\n"
            "```\n\n"
            "- `main` = Python file name (`main.py`)\n"
            "- `app` = the FastAPI instance variable\n"
            "- `--reload` = restart on code changes (development only)\n\n"
            "Open `http://127.0.0.1:8000/docs` for Swagger UI — try endpoints in the "
            "browser. `/redoc` is an alternative docs view.\n\n"
            "## Path and query parameters\n\n"
            "Path segments in `{braces}` and function parameters share names:\n\n"
            "```python\n"
            "@app.get('/items/{item_id}')\n"
            "def read_item(item_id: int, q: str | None = None):\n"
            "    return {'item_id': item_id, 'q': q}\n"
            "```\n\n"
            "```bash\n"
            "GET /items/42?q=python\n"
            "# → {\"item_id\": 42, \"q\": \"python\"}\n\n"
            "GET /items/not-a-number\n"
            "# → 422 Unprocessable Entity with field-level error details\n"
            "```\n\n"
            "Types in the signature drive parsing and validation. FastAPI rejects "
            "bad input before your function body runs.\n\n"
            "Optional query params use `None` as default:\n\n"
            "```python\n"
            "@app.get('/search')\n"
            "def search(q: str, page: int = 1, limit: int = 20):\n"
            "    return {'q': q, 'page': page, 'limit': limit}\n"
            "```\n\n"
            "## HTTP methods\n\n"
            "```python\n"
            "@app.get('/items')       # read list\n"
            "@app.get('/items/{id}') # read one\n"
            "@app.post('/items')      # create\n"
            "@app.put('/items/{id}')  # replace\n"
            "@app.patch('/items/{id}')# partial update\n"
            "@app.delete('/items/{id}')# remove\n"
            "```\n\n"
            "## Request body (preview)\n\n"
            "POST/PATCH routes accept JSON bodies via Pydantic models (covered in the "
            "next lesson). For now, know that FastAPI reads the body, validates it, "
            "and passes a Python object to your handler.\n\n"
            "## Status codes and responses\n\n"
            "```python\n"
            "from fastapi import FastAPI, HTTPException, status\n\n"
            "app = FastAPI()\n\n"
            "@app.post('/items', status_code=status.HTTP_201_CREATED)\n"
            "def create_item():\n"
            "    return {'id': 1}\n\n"
            "@app.get('/items/{item_id}')\n"
            "def get_item(item_id: int):\n"
            "    if item_id == 404:\n"
            "        raise HTTPException(status_code=404, detail='Item not found')\n"
            "    return {'id': item_id}\n"
            "```\n\n"
            "Use `status_code=` on the decorator for non-200 defaults. "
            "`HTTPException` returns JSON like `{\"detail\": \"...\"}`.\n\n"
            "## Testing without a live server\n\n"
            "`TestClient` runs the app in-process — no port, no network flake:\n\n"
            "```python\n"
            "from fastapi.testclient import TestClient\n\n"
            "client = TestClient(app)\n\n"
            "def test_root():\n"
            "    response = client.get('/')\n"
            "    assert response.status_code == 200\n"
            "    assert response.json() == {'message': 'hello'}\n\n"
            "def test_item_with_query():\n"
            "    response = client.get('/items/7?q=test')\n"
            "    assert response.status_code == 200\n"
            "    assert response.json()['item_id'] == 7\n"
            "```\n\n"
            "**Worked example:** test validation failure:\n\n"
            "```python\n"
            "def test_invalid_item_id():\n"
            "    response = client.get('/items/abc')\n"
            "    assert response.status_code == 422\n"
            "    detail = response.json()['detail']\n"
            "    assert any('item_id' in str(err.get('loc', [])) for err in detail)\n"
            "```\n\n"
            "**Worked example:** test 404:\n\n"
            "```python\n"
            "def test_missing_item():\n"
            "    response = client.get('/items/404')\n"
            "    assert response.status_code == 404\n"
            "    assert response.json()['detail'] == 'Item not found'\n"
            "```\n\n"
            "Always prefer `TestClient` in unit tests over `requests.get('localhost:8000')`.\n\n"
            "## Sync vs async routes\n\n"
            "```python\n"
            "@app.get('/fast')\n"
            "def sync_route():\n"
            "    return {'ok': True}\n\n"
            "@app.get('/async')\n"
            "async def async_route():\n"
            "    return {'ok': True}\n"
            "```\n\n"
            "Use `async def` when you `await` non-blocking I/O (httpx.AsyncClient, "
            "async database drivers). Do not put blocking calls (`time.sleep`, "
            "sync `requests.get`) inside `async def` — they block the event loop. "
            "Either use sync `def` or run blocking code in a thread pool.\n\n"
            "## Real-world scenario: health check endpoint\n\n"
            "```python\n"
            "from datetime import datetime, timezone\n\n"
            "@app.get('/health')\n"
            "def health():\n"
            "    return {\n"
            "        'status': 'ok',\n"
            "        'timestamp': datetime.now(timezone.utc).isoformat(),\n"
            "    }\n"
            "```\n\n"
            "Load balancers and Kubernetes probes call `/health` to verify the service "
            "is alive. Keep it fast — no heavy database queries.\n\n"
            "## Project layout tips\n\n"
            "```\n"
            "app/\n"
            "  main.py          # app = FastAPI(); include routers\n"
            "  routers/\n"
            "    users.py       # APIRouter(prefix='/users')\n"
            "  models.py        # Pydantic schemas\n"
            "  settings.py      # env-based config\n"
            "```\n\n"
            "Split routers to keep files small:\n\n"
            "```python\n"
            "from fastapi import APIRouter\n"
            "router = APIRouter()\n\n"
            "@router.get('/')\n"
            "def list_users():\n"
            "    return []\n\n"
            "# in main.py:\n"
            "app.include_router(router, prefix='/users', tags=['users'])\n"
            "```\n\n"
            "Load settings from environment variables (pydantic-settings or `os.environ`).\n\n"
            "## Common pitfalls\n\n"
            "- Returning non-JSON-serializable objects (datetime without conversion, "
            "custom classes)\n"
            "- Blocking I/O in `async def` routes\n"
            "- Testing with real HTTP when TestClient suffices\n"
            "- Forgetting `--reload` is dev-only; use a process manager in production\n"
            "- Putting business logic directly in route functions — extract services "
            "as the app grows\n"
            "- Defining routes after `uvicorn` starts — import order matters\n\n"
            "## Practice\n\n"
            "Create a GET `/` route that returns a greeting JSON object.\n\n"
            "## Summary\n\n"
            "FastAPI = typed routes + automatic validation + OpenAPI docs + easy testing. "
            "Define `app = FastAPI()`, decorate handlers with `@app.get`/`@app.post`, "
            "return dicts, and verify behavior with `TestClient` before deploying."
        ),
    },
    {
        "slug": "02_pydantic_models",
        "track": "fastapi",
        "difficulty": "medium",
        "title": "Pydantic Models and Validation",
        "tags": ["pydantic", "validation"],
        "exercise": "content/problems/fastapi/medium/06_response_model.py",
        "body": (
            "# Pydantic Models and Validation\n\n"
            "## Overview\n\n"
            "Pydantic models describe the shape of request and response data. FastAPI "
            "uses them to parse JSON bodies, validate fields, and generate OpenAPI "
            "schemas — your docs stay in sync with your code automatically.\n\n"
            "Think of a Pydantic model as a contract: \"this endpoint accepts exactly "
            "these fields, with these types and constraints.\"\n\n"
            "## Defining a model\n\n"
            "```python\n"
            "from pydantic import BaseModel, EmailStr, Field\n\n"
            "class UserCreate(BaseModel):\n"
            "    email: EmailStr\n"
            "    name: str = Field(min_length=1, max_length=100)\n"
            "    age: int | None = None\n"
            "```\n\n"
            "Field constraints produce clear 422 errors when violated:\n\n"
            "```json\n"
            "{\n"
            "  \"detail\": [\n"
            "    {\"loc\": [\"body\", \"email\"], \"msg\": \"value is not a valid email address\"}\n"
            "  ]\n"
            "}\n"
            "```\n\n"
            "Common validators:\n\n"
            "```python\n"
            "from pydantic import Field\n\n"
            "price: float = Field(gt=0, description='Must be positive')\n"
            "tags: list[str] = Field(default_factory=list, max_length=10)\n"
            "role: str = Field(pattern=r'^(admin|user|guest)$')\n"
            "```\n\n"
            "## Using models in routes\n\n"
            "```python\n"
            "from fastapi import FastAPI, status\n\n"
            "app = FastAPI()\n\n"
            "@app.post('/users', status_code=status.HTTP_201_CREATED)\n"
            "def create_user(user: UserCreate):\n"
            "    # user is already validated — safe to use\n"
            "    return {'id': 1, **user.model_dump()}\n"
            "```\n\n"
            "Send JSON from a client or TestClient:\n\n"
            "```python\n"
            "client.post('/users', json={'email': 'ada@example.com', 'name': 'Ada'})\n"
            "```\n\n"
            "Invalid body → automatic 422 with per-field errors. Your handler never runs.\n\n"
            "## Worked example: separate create and response shapes\n\n"
            "Clients send passwords; responses should not echo them:\n\n"
            "```python\n"
            "class UserCreate(BaseModel):\n"
            "    email: EmailStr\n"
            "    password: str = Field(min_length=8)\n\n"
            "class UserOut(BaseModel):\n"
            "    id: int\n"
            "    email: EmailStr\n\n"
            "@app.post('/users', response_model=UserOut, status_code=201)\n"
            "def create_user(user: UserCreate):\n"
            "    stored = save_user(user)  # hashes password internally\n"
            "    return stored  # extra fields like password_hash are stripped\n"
            "```\n\n"
            "Even if `save_user` returns `password_hash`, `response_model=UserOut` "
            "filters it out of the JSON response.\n\n"
            "## Response models\n\n"
            "`response_model=` filters and validates what leaves your API:\n\n"
            "```python\n"
            "class UserOut(BaseModel):\n"
            "    id: int\n"
            "    email: EmailStr\n"
            "    name: str\n\n"
            "@app.get('/users/{uid}', response_model=UserOut)\n"
            "def get_user(uid: int):\n"
            "    row = db.get_user(uid)\n"
            "    return row  # Pydantic drops extra keys, coerces types\n"
            "```\n\n"
            "This prevents accidentally leaking internal fields (`password_hash`, "
            "`internal_notes`) in JSON responses.\n\n"
            "## model_dump and model_validate (Pydantic v2)\n\n"
            "```python\n"
            "user = UserCreate(email='a@b.com', name='Ada', password='long-enough')\n"
            "data = user.model_dump()                    # dict for JSON/DB insert\n"
            "safe = user.model_dump(exclude={'password'})  # omit sensitive fields\n"
            "restored = UserCreate.model_validate({'email': 'a@b.com', 'name': 'Ada', 'password': 'long-enough'})\n"
            "```\n\n"
            "Pydantic v1 used `.dict()` and `.parse_obj()` — check your project's "
            "version in `requirements.txt` or `pyproject.toml`.\n\n"
            "## Nested and optional models\n\n"
            "```python\n"
            "class Address(BaseModel):\n"
            "    street: str\n"
            "    city: str\n\n"
            "class UserCreate(BaseModel):\n"
            "    name: str\n"
            "    address: Address | None = None\n"
            "```\n\n"
            "FastAPI validates nested objects recursively:\n\n"
            "```python\n"
            "client.post('/users', json={\n"
            "    'name': 'Ada',\n"
            "    'address': {'street': '1 Analytical Engine Rd', 'city': 'London'},\n"
            "})\n"
            "```\n\n"
            "## Sharing fields with inheritance\n\n"
            "```python\n"
            "class UserBase(BaseModel):\n"
            "    email: EmailStr\n"
            "    name: str\n\n"
            "class UserCreate(UserBase):\n"
            "    password: str\n\n"
            "class UserUpdate(BaseModel):\n"
            "    name: str | None = None\n"
            "    email: EmailStr | None = None\n\n"
            "class UserOut(UserBase):\n"
            "    id: int\n"
            "    model_config = {'from_attributes': True}\n"
            "```\n\n"
            "Create / Update / Out variants keep schemas DRY.\n\n"
            "## Config for ORM objects\n\n"
            "When returning SQLAlchemy or other ORM rows:\n\n"
            "```python\n"
            "class UserOut(BaseModel):\n"
            "    model_config = {'from_attributes': True}\n"
            "    id: int\n"
            "    email: str\n"
            "```\n\n"
            "`from_attributes=True` lets Pydantic read attributes from arbitrary objects, "
            "not just dicts.\n\n"
            "## Real-world scenario: webhook payload\n\n"
            "```python\n"
            "class StripeEvent(BaseModel):\n"
            "    id: str\n"
            "    type: str\n"
            "    data: dict\n\n"
            "@app.post('/webhooks/stripe')\n"
            "def stripe_webhook(event: StripeEvent):\n"
            "    if event.type == 'payment_intent.succeeded':\n"
            "        handle_payment(event.data)\n"
            "    return {'received': True}\n"
            "```\n\n"
            "Pydantic rejects malformed webhooks before your handler processes them.\n\n"
            "## Testing validation\n\n"
            "```python\n"
            "def test_create_user_ok():\n"
            "    r = client.post('/users', json={'email': 'ada@ex.com', 'name': 'Ada', 'password': 'secret123'})\n"
            "    assert r.status_code == 201\n"
            "    body = r.json()\n"
            "    assert 'password' not in body\n\n"
            "def test_create_user_bad_email():\n"
            "    r = client.post('/users', json={'email': 'not-email', 'name': 'Ada', 'password': 'secret123'})\n"
            "    assert r.status_code == 422\n\n"
            "def test_create_user_short_password():\n"
            "    r = client.post('/users', json={'email': 'ada@ex.com', 'name': 'Ada', 'password': 'short'})\n"
            "    assert r.status_code == 422\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Mutable defaults on model fields — use `Field(default_factory=list)` "
            "for lists/dicts\n"
            "- Returning ORM objects without `from_attributes=True`\n"
            "- One giant model for everything — split Create/Update/Out variants\n"
            "- Validating the same rules in the route *and* the model (DRY violation)\n"
            "- Forgetting `response_model` and leaking sensitive columns\n"
            "- Using Pydantic v1 methods (`.dict()`) in a v2 project\n\n"
            "## Practice\n\n"
            "Define a User model with email and name validation.\n\n"
            "## Summary\n\n"
            "Pydantic = schema + validation + serialization. Define input models for "
            "request bodies, output models with `response_model` for responses, and "
            "share base fields via inheritance or composition. FastAPI + Pydantic "
            "turn type hints into live API contracts."
        ),
    },
]
