"""HTTPX track lesson guides."""

LESSONS = [
    {
        "slug": "01_httpx_intro",
        "track": "httpx",
        "difficulty": "easy",
        "title": "HTTPX Basics",
        "tags": ["httpx"],
        "exercise": "content/problems/httpx/easy/01_build_request.py",
        "body": (
            "# HTTPX Basics\n\n"
            "## Overview\n\n"
            "HTTPX is a modern HTTP client for Python. If you have used `requests`, "
            "HTTPX will feel familiar — but it also supports **async** (`await client.get(...)`) "
            "and ships with testing tools that do not require a live network.\n\n"
            "Think of HTTPX as \"requests, plus async and built-in mocking.\" You still "
            "send a method and URL; you still get back a response with status, headers, "
            "and body. The API is intentionally similar so migration is easy.\n\n"
            "Real-world uses:\n\n"
            "- Calling REST APIs from scripts and microservices\n"
            "- Async services that fan out to many endpoints at once\n"
            "- Testing FastAPI/Starlette apps with `httpx.ASGITransport`\n"
            "- Unit tests that mock HTTP without hitting the internet\n"
            "- HTTP/2 connections to modern APIs (optional extra)\n\n"
            "Install with `pip install httpx`. For HTTP/2 support, add the optional "
            "`httpx[http2]` extra.\n\n"
            "## Your first GET request\n\n"
            "The one-liner pattern mirrors `requests` exactly:\n\n"
            "```python\n"
            "import httpx\n\n"
            "response = httpx.get('https://httpbin.org/get', timeout=10.0)\n"
            "response.raise_for_status()   # raise if 4xx or 5xx\n"
            "data = response.json()\n"
            "print(data['url'])            # echo of the URL you requested\n"
            "```\n\n"
            "Step by step:\n"
            "1. `httpx.get(...)` sends an HTTP GET and waits for the response.\n"
            "2. `raise_for_status()` turns HTTP errors into exceptions you can catch.\n"
            "3. `.json()` parses the body as JSON (raises if the body is not JSON).\n\n"
            "**Always set `timeout=`** in production. Without it, a hung server blocks "
            "your worker forever.\n\n"
            "## Sync client: GET and POST\n\n"
            "For multiple calls to the same host, use a `Client` so TCP connections "
            "are reused (faster, fewer sockets):\n\n"
            "```python\n"
            "with httpx.Client(timeout=10.0) as client:\n"
            "    r = client.get('https://api.example.com/users')\n"
            "    r.raise_for_status()\n"
            "    users = r.json()\n\n"
            "    created = client.post(\n"
            "        'https://api.example.com/users',\n"
            "        json={'name': 'Ada', 'role': 'admin'},\n"
            "        headers={'Authorization': 'Bearer TOKEN'},\n"
            "    )\n"
            "    created.raise_for_status()\n"
            "    print(created.json())\n"
            "```\n\n"
            "Request body helpers:\n\n"
            "| Parameter | Sends as                         | Content-Type                    |\n"
            "|-----------|----------------------------------|---------------------------------|\n"
            "| `json=`   | JSON-encoded dict/list           | `application/json` (automatic)  |\n"
            "| `data=`   | Form fields                      | `application/x-www-form-urlencoded` |\n"
            "| `content=`| Raw bytes                        | You set headers manually        |\n"
            "| `files=`  | Multipart upload                 | `multipart/form-data`           |\n\n"
            "## base_url on Client\n\n"
            "When every call shares a host, set `base_url` once:\n\n"
            "```python\n"
            "with httpx.Client(base_url='https://api.example.com', timeout=10.0) as client:\n"
            "    users = client.get('/users').json()       # → https://api.example.com/users\n"
            "    user = client.get('/users/42').json()     # → https://api.example.com/users/42\n"
            "```\n\n"
            "Relative paths join cleanly — no string concatenation bugs.\n\n"
            "## Building requests without sending\n\n"
            "Construct a `Request` object and inspect it before any network I/O. "
            "Ideal for unit tests that verify URL construction:\n\n"
            "```python\n"
            "import httpx\n\n"
            "req = httpx.Request(\n"
            "    'GET',\n"
            "    'https://api.example.com/search',\n"
            "    params={'q': 'python', 'page': 2},\n"
            ")\n"
            "assert req.method == 'GET'\n"
            "assert 'q=python' in str(req.url)\n"
            "assert 'page=2' in str(req.url)\n"
            "```\n\n"
            "HTTPX handles URL encoding — spaces become `%20`, `&` and `=` in values "
            "are escaped safely.\n\n"
            "**Worked example:** build a search URL helper:\n\n"
            "```python\n"
            "def build_search_request(base_url: str, query: str, page: int = 1) -> httpx.Request:\n"
            "    return httpx.Request('GET', base_url, params={'q': query, 'page': page})\n\n"
            "req = build_search_request('https://shop.example.com/api/search', 'blue socks', page=3)\n"
            "url = str(req.url)\n"
            "# https://shop.example.com/api/search?q=blue+socks&page=3\n"
            "```\n\n"
            "**Worked example:** POST with JSON headers (no network):\n\n"
            "```python\n"
            "def build_create_user_request(url: str, payload: dict, token: str) -> httpx.Request:\n"
            "    return httpx.Request(\n"
            "        'POST',\n"
            "        url,\n"
            "        json=payload,\n"
            "        headers={'Authorization': f'Bearer {token}'},\n"
            "    )\n\n"
            "req = build_create_user_request(\n"
            "    'https://api.example.com/users',\n"
            "    {'name': 'Ada'},\n"
            "    'secret-token',\n"
            ")\n"
            "assert req.method == 'POST'\n"
            "assert req.headers['Authorization'] == 'Bearer secret-token'\n"
            "```\n\n"
            "## Real-world scenario: paginated API client\n\n"
            "```python\n"
            "def fetch_all_pages(client: httpx.Client, path: str) -> list[dict]:\n"
            "    results = []\n"
            "    page = 1\n"
            "    while True:\n"
            "        r = client.get(path, params={'page': page, 'limit': 100})\n"
            "        r.raise_for_status()\n"
            "        batch = r.json()\n"
            "        if not batch:\n"
            "            break\n"
            "        results.extend(batch)\n"
            "        page += 1\n"
            "    return results\n"
            "```\n\n"
            "Build each page URL with `params=` — never hand-concatenate `?page=` strings.\n\n"
            "## Async client\n\n"
            "When you need to call many APIs concurrently, async saves wall-clock time:\n\n"
            "```python\n"
            "import asyncio\n"
            "import httpx\n\n"
            "async def fetch_all(urls: list[str]) -> list[dict]:\n"
            "    async with httpx.AsyncClient(timeout=10.0) as client:\n"
            "        tasks = [client.get(url) for url in urls]\n"
            "        responses = await asyncio.gather(*tasks)\n"
            "        for r in responses:\n"
            "            r.raise_for_status()\n"
            "        return [r.json() for r in responses]\n\n"
            "results = asyncio.run(fetch_all([\n"
            "    'https://api.example.com/users/1',\n"
            "    'https://api.example.com/users/2',\n"
            "    'https://api.example.com/users/3',\n"
            "]))\n"
            "```\n\n"
            "Rules for async:\n"
            "- Use `AsyncClient` inside `async def` functions.\n"
            "- Do **not** call blocking `httpx.get()` inside FastAPI `async def` routes — "
            "that blocks the event loop.\n"
            "- Either use `async def` + `AsyncClient`, or use sync `def` routes + sync `Client`.\n\n"
            "## MockTransport for tests\n\n"
            "Replace the network with a handler function that returns canned responses. "
            "No internet, no flaky CI:\n\n"
            "```python\n"
            "import httpx\n\n"
            "def handler(request: httpx.Request) -> httpx.Response:\n"
            "    if request.url.path == '/health':\n"
            "        return httpx.Response(200, json={'status': 'ok'})\n"
            "    if request.url.path == '/users':\n"
            "        return httpx.Response(200, json=[{'id': 1, 'name': 'Ada'}])\n"
            "    return httpx.Response(404, json={'error': 'not found'})\n\n"
            "transport = httpx.MockTransport(handler)\n"
            "with httpx.Client(transport=transport, base_url='https://fake.test') as client:\n"
            "    assert client.get('/health').json() == {'status': 'ok'}\n"
            "    assert client.get('/users').json()[0]['name'] == 'Ada'\n"
            "    assert client.get('/nope').status_code == 404\n"
            "```\n\n"
            "**Worked example:** test a client wrapper without network:\n\n"
            "```python\n"
            "def get_user_name(client: httpx.Client, user_id: int) -> str:\n"
            "    r = client.get(f'/users/{user_id}')\n"
            "    r.raise_for_status()\n"
            "    return r.json()['name']\n\n"
            "def mock_handler(request: httpx.Request) -> httpx.Response:\n"
            "    user_id = request.url.path.split('/')[-1]\n"
            "    return httpx.Response(200, json={'name': f'User {user_id}'})\n\n"
            "with httpx.Client(transport=httpx.MockTransport(mock_handler)) as client:\n"
            "    assert get_user_name(client, 42) == 'User 42'\n"
            "```\n\n"
            "## ASGITransport: test FastAPI apps\n\n"
            "HTTPX can call a FastAPI app directly — no Uvicorn, no open port:\n\n"
            "```python\n"
            "from fastapi import FastAPI\n"
            "import httpx\n\n"
            "app = FastAPI()\n\n"
            "@app.get('/hello')\n"
            "def hello():\n"
            "    return {'message': 'hi'}\n\n"
            "transport = httpx.ASGITransport(app=app)\n"
            "with httpx.Client(transport=transport, base_url='http://test') as client:\n"
            "    r = client.get('/hello')\n"
            "    assert r.status_code == 200\n"
            "    assert r.json() == {'message': 'hi'}\n"
            "```\n\n"
            "This is how `fastapi.testclient.TestClient` works under the hood.\n\n"
            "## Sessions, headers, and cookies\n\n"
            "```python\n"
            "with httpx.Client() as client:\n"
            "    client.headers['User-Agent'] = 'myapp/1.0'\n"
            "    client.headers['Accept'] = 'application/json'\n"
            "    r1 = client.get('https://api.example.com/me')\n"
            "    r2 = client.get('https://api.example.com/settings')\n"
            "    # both requests share default headers and connection pool\n"
            "```\n\n"
            "Per-request headers merge with client defaults. Cookies persist on the "
            "client the same way as `requests.Session`.\n\n"
            "## Inspecting responses\n\n"
            "```python\n"
            "r = httpx.get('https://httpbin.org/status/404', timeout=10.0)\n"
            "r.status_code          # 404\n"
            "r.headers['content-type']\n"
            "r.text                 # body as str\n"
            "r.content              # body as bytes\n"
            "r.json()               # parse JSON (raises if not JSON)\n"
            "r.raise_for_status()   # raises httpx.HTTPStatusError on 4xx/5xx\n"
            "r.elapsed.total_seconds()  # how long the request took\n"
            "```\n\n"
            "Always check status before calling `.json()`. Error pages are often HTML, "
            "not JSON — calling `.json()` on a 500 HTML page raises `JSONDecodeError`.\n\n"
            "## Error handling pattern\n\n"
            "```python\n"
            "try:\n"
            "    r = httpx.get(url, timeout=10.0)\n"
            "    r.raise_for_status()\n"
            "    data = r.json()\n"
            "except httpx.TimeoutException:\n"
            "    print('server too slow')\n"
            "except httpx.HTTPStatusError as e:\n"
            "    print(f'HTTP {e.response.status_code}: {e.response.text[:200]}')\n"
            "except httpx.RequestError as e:\n"
            "    print(f'network problem: {e}')\n"
            "```\n\n"
            "## HTTPX vs requests\n\n"
            "| Feature              | requests | httpx |\n"
            "|----------------------|----------|-------|\n"
            "| Sync API             | yes      | yes   |\n"
            "| Async API            | no       | yes   |\n"
            "| MockTransport        | no       | yes   |\n"
            "| ASGI app testing     | no       | yes   |\n"
            "| HTTP/2 (optional)    | no       | yes   |\n\n"
            "For simple sync scripts, either library works. Choose HTTPX when you need "
            "async, built-in mocking, or tight integration with FastAPI tests.\n\n"
            "## Common pitfalls\n\n"
            "- No timeout → hung workers in production\n"
            "- Calling `.json()` on a 500 HTML error page\n"
            "- Using sync `httpx.get()` inside `async def` FastAPI routes\n"
            "- Creating a new `Client` per request (loses connection pooling)\n"
            "- Putting API keys in query strings (they end up in logs and browser history)\n"
            "- Retrying POST requests blindly (can duplicate side effects)\n"
            "- Forgetting `raise_for_status()` and treating 404/500 responses as success\n\n"
            "## Practice\n\n"
            "Build an httpx Request and inspect its method and URL.\n\n"
            "## Summary\n\n"
            "HTTPX = requests-like ergonomics + async + MockTransport for tests. "
            "Build `Request` objects to verify URL logic; use `Client`/`AsyncClient` "
            "for real calls; mock the transport to keep tests fast and offline."
        ),
    },
]
