"""Pandas track lesson guides."""

LESSONS = [
    {
        "slug": "01_series_basics",
        "track": "pandas",
        "difficulty": "easy",
        "title": "Pandas Series Basics",
        "tags": ["pandas", "series"],
        "exercise": "content/problems/pandas/easy/01_double_series.py",
        "body": (
            "# Pandas Series Basics\n\n"
            "## Overview\n\n"
            "A `Series` is a one-dimensional labeled array — like a single column in "
            "a spreadsheet or a Python dict with a fixed order. It is the building "
            "block of DataFrames and the first pandas type to master.\n\n"
            "If you know Python lists and dicts, a Series combines both: ordered "
            "values with optional labels (the index).\n\n"
            "Real-world uses:\n\n"
            "- Daily temperature readings with date labels\n"
            "- Stock prices indexed by timestamp\n"
            "- Survey scores for each respondent ID\n"
            "- Any column you pull out of a larger table\n\n"
            "Install with `pip install pandas` (NumPy is installed automatically).\n\n"
            "## Creating a Series\n\n"
            "```python\n"
            "import pandas as pd\n\n"
            "s = pd.Series([10, 20, 30])                    # default index 0, 1, 2\n"
            "s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])\n"
            "s = pd.Series({'a': 10, 'b': 20, 'c': 30})     # keys become index\n"
            "```\n\n"
            "Print a Series to see values aligned with their labels:\n\n"
            "```\n"
            "a    10\n"
            "b    20\n"
            "c    30\n"
            "dtype: int64\n"
            "```\n\n"
            "## Index and values\n\n"
            "```python\n"
            "s.index    # Index(['a', 'b', 'c'])\n"
            "s.values   # numpy array: array([10, 20, 30])\n"
            "s.dtype    # int64\n"
            "len(s)     # 3\n"
            "s.name     # optional name (useful when Series becomes a DataFrame column)\n"
            "```\n\n"
            "Two ways to access elements:\n\n"
            "```python\n"
            "s['b']      # label-based (loc style)\n"
            "s.iloc[1]   # position-based — always 0, 1, 2...\n"
            "s.loc['b']  # explicit label access\n"
            "```\n\n"
            "**Watch out:** if your index is integers, `s[0]` might mean label `0`, "
            "not the first row. Prefer `.iloc` for position and `.loc` for labels.\n\n"
            "## Vectorized operations\n\n"
            "The core pandas idea: operate on the whole Series at once, not element "
            "by element in a Python loop.\n\n"
            "```python\n"
            "s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])\n"
            "doubled = s * 2           # a→20, b→40, c→60\n"
            "shifted = s + 100\n"
            "avg = s.mean()            # 20.0\n"
            "summary = s.describe()    # count, mean, std, min, quartiles, max\n"
            "```\n\n"
            "**Worked example:** price with tax:\n\n"
            "```python\n"
            "prices = pd.Series({'widget': 9.99, 'gadget': 14.50, 'gizmo': 3.25})\n"
            "with_tax = (prices * 1.08).round(2)\n"
            "# widget    10.79\n"
            "# gadget    15.66\n"
            "# gizmo      3.51\n"
            "```\n\n"
            "**Worked example:** temperature conversion (Fahrenheit to Celsius):\n\n"
            "```python\n"
            "fahrenheit = pd.Series([32, 68, 98.6], index=['freezing', 'room', 'body'])\n"
            "celsius = (fahrenheit - 32) * 5/9\n"
            "# freezing      0.0\n"
            "# room         20.0\n"
            "# body         37.0\n"
            "```\n\n"
            "## Alignment on index\n\n"
            "When you combine two Series, pandas aligns by label:\n\n"
            "```python\n"
            "a = pd.Series([1, 2, 3], index=['x', 'y', 'z'])\n"
            "b = pd.Series([10, 20], index=['y', 'z'])\n"
            "a + b\n"
            "# x     NaN  (no match in b)\n"
            "# y    12.0\n"
            "# z    23.0\n"
            "```\n\n"
            "Missing labels become `NaN` (Not a Number). Use `.fillna(0)` if you need "
            "zeros instead:\n\n"
            "```python\n"
            "(a + b).fillna(0)\n"
            "```\n\n"
            "## Boolean filtering\n\n"
            "```python\n"
            "s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])\n"
            "s[s > 15]              # b→20, c→30, d→40\n"
            "s[s.isin([10, 30])]    # a→10, c→30\n"
            "s[s.between(15, 35)]   # b→20, c→30\n"
            "```\n\n"
            "The expression inside `s[...]` must be a boolean Series of the same length.\n\n"
            "**Worked example:** filter and transform:\n\n"
            "```python\n"
            "scores = pd.Series([55, 72, 88, 91, 63], index=['A', 'B', 'C', 'D', 'E'])\n"
            "passing = scores[scores >= 60]\n"
            "curved = passing + 5\n"
            "```\n\n"
            "## Useful methods\n\n"
            "```python\n"
            "s.sort_values()          # ascending by value\n"
            "s.sort_index()           # ascending by label\n"
            "s.unique()               # array of distinct values\n"
            "s.value_counts()         # frequency table\n"
            "s.isna().sum()           # count missing values\n"
            "s.apply(lambda x: x * 2) # element-wise function (slower than vectorized ops)\n"
            "```\n\n"
            "## Handling missing data in Series\n\n"
            "```python\n"
            "s = pd.Series([10, None, 30])\n"
            "s.isna()           # False, True, False\n"
            "s.dropna()         # remove NaN rows\n"
            "s.fillna(0)        # replace NaN with 0\n"
            "s.interpolate()    # fill gaps by interpolation\n"
            "```\n\n"
            "## Why vectorization matters\n\n"
            "Loops over rows are slow; NumPy/pandas C-backed ops are fast:\n\n"
            "```python\n"
            "# slow — avoid for large data\n"
            "doubled = pd.Series([x * 2 for x in s])\n\n"
            "# fast — preferred\n"
            "doubled = s * 2\n"
            "```\n\n"
            "On millions of rows the difference is seconds vs minutes.\n\n"
            "## Real-world scenario: daily sales totals\n\n"
            "```python\n"
            "sales = pd.Series(\n"
            "    [1200, 980, 1450, 1100, 1320],\n"
            "    index=pd.date_range('2025-01-01', periods=5, freq='D'),\n"
            ")\n"
            "sales.mean()                    # average daily sales\n"
            "sales[sales > sales.mean()]     # above-average days\n"
            "sales.pct_change()              # day-over-day percent change\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- SettingWithCopyWarning — use `.loc` for assignment: `s.loc[mask] = value`\n"
            "- Mixing `s[0]` (label if index is int) vs `s.iloc[0]` (always position)\n"
            "- Forgetting NaN propagates in arithmetic (`10 + NaN = NaN`)\n"
            "- Assuming `.sort_values()` mutates in place — it returns a new Series unless "
            "`inplace=True`\n"
            "- Using Python loops when a vectorized operation exists\n\n"
            "## Practice\n\n"
            "Double every value in a Series without a Python loop.\n\n"
            "## Summary\n\n"
            "Series = values + index + vectorized methods. Create with lists or dicts, "
            "access with `.loc`/`.iloc`, transform with arithmetic and boolean masks. "
            "Master Series before moving to multi-column DataFrames."
        ),
    },
    {
        "slug": "02_dataframe_operations",
        "track": "pandas",
        "difficulty": "medium",
        "title": "DataFrame Operations",
        "tags": ["pandas", "dataframe"],
        "exercise": "content/problems/pandas/easy/02_filter_dataframe.py",
        "body": (
            "# DataFrame Operations\n\n"
            "## Overview\n\n"
            "A `DataFrame` is a table of Series sharing one index — rows are records, "
            "columns are fields. Most real data work (filter, group, join, export) "
            "happens at the DataFrame level.\n\n"
            "Real-world uses:\n\n"
            "- Sales reports from CSV exports\n"
            "- Log analysis (filter errors, count by service)\n"
            "- Joining customer data with order history\n"
            "- Preparing cleaned data for charts or ML pipelines\n\n"
            "## Creating and inspecting\n\n"
            "```python\n"
            "import pandas as pd\n\n"
            "df = pd.DataFrame({\n"
            "    'name': ['Ada', 'Grace', 'Linus'],\n"
            "    'score': [98, 95, 88],\n"
            "    'department': ['eng', 'eng', 'ops'],\n"
            "})\n"
            "df.head()       # first 5 rows\n"
            "df.tail(3)      # last 3 rows\n"
            "df.info()       # dtypes, non-null counts, memory\n"
            "df.describe()   # numeric summary stats\n"
            "df.shape        # (rows, columns)\n"
            "df.columns.tolist()\n"
            "```\n\n"
            "Load from CSV — the most common entry point:\n\n"
            "```python\n"
            "df = pd.read_csv('sales.csv')\n"
            "df = pd.read_csv('sales.csv', parse_dates=['order_date'], usecols=['id', 'amount', 'region'])\n"
            "df.to_csv('cleaned.csv', index=False)\n"
            "```\n\n"
            "## Selecting columns and rows\n\n"
            "```python\n"
            "df['name']                  # Series — one column\n"
            "df[['name', 'score']]       # DataFrame — multiple columns\n"
            "df.loc[0]                   # row by label\n"
            "df.iloc[0]                  # row by position\n"
            "df.loc[0, 'name']           # single cell\n"
            "df[df['score'] >= 96]       # filter rows — boolean mask\n"
            "```\n\n"
            "**Worked example:** high performers in engineering:\n\n"
            "```python\n"
            "top_eng = df[(df['department'] == 'eng') & (df['score'] >= 96)]\n"
            "```\n\n"
            "Combine conditions with `&` (and), `|` (or). Wrap each condition in parentheses.\n\n"
            "**Worked example:** filter with `.query()`:\n\n"
            "```python\n"
            "top_eng = df.query(\"department == 'eng' and score >= 96\")\n"
            "```\n\n"
            "## Adding and mutating columns\n\n"
            "```python\n"
            "df['passed'] = df['score'] >= 60\n"
            "df['grade'] = pd.cut(df['score'], bins=[0, 60, 80, 100], labels=['C', 'B', 'A'])\n"
            "```\n\n"
            "Prefer `.assign` for method chains — avoids mutating the original:\n\n"
            "```python\n"
            "result = (\n"
            "    df.assign(doubled=lambda d: d['score'] * 2)\n"
            "      .assign(passed=lambda d: d['score'] >= 60)\n"
            "      .query('passed')\n"
            ")\n"
            "```\n\n"
            "## Sorting and ranking\n\n"
            "```python\n"
            "df.sort_values('score', ascending=False)\n"
            "df.sort_values(['department', 'score'], ascending=[True, False])\n"
            "df['rank'] = df['score'].rank(ascending=False)\n"
            "```\n\n"
            "## Groupby aggregations\n\n"
            "```python\n"
            "df.groupby('department')['score'].mean()\n"
            "df.groupby('department').agg(\n"
            "    avg_score=('score', 'mean'),\n"
            "    headcount=('name', 'count'),\n"
            "    top_score=('score', 'max'),\n"
            ")\n"
            "```\n\n"
            "**Worked example:** monthly revenue by region:\n\n"
            "```python\n"
            "sales = pd.read_csv('orders.csv', parse_dates=['order_date'])\n"
            "sales['month'] = sales['order_date'].dt.to_period('M')\n"
            "revenue = sales.groupby(['region', 'month'])['amount'].sum().reset_index()\n"
            "```\n\n"
            "**Worked example:** top customer per region:\n\n"
            "```python\n"
            "idx = sales.groupby('region')['amount'].idxmax()\n"
            "top_customers = sales.loc[idx, ['region', 'customer', 'amount']]\n"
            "```\n\n"
            "## Merge and concat\n\n"
            "Join two tables on a shared key (like SQL JOIN):\n\n"
            "```python\n"
            "users = pd.DataFrame({'user_id': [1, 2], 'name': ['Ada', 'Grace']})\n"
            "orders = pd.DataFrame({'user_id': [1, 1, 2], 'total': [50, 30, 80]})\n"
            "pd.merge(users, orders, on='user_id', how='left')\n"
            "```\n\n"
            "Stack tables vertically:\n\n"
            "```python\n"
            "pd.concat([df2024, df2025], ignore_index=True)\n"
            "```\n\n"
            "| how=    | Keeps rows from...                    |\n"
            "|----------|---------------------------------------|\n"
            "| inner    | both tables (intersection)            |\n"
            "| left     | left table + matches from right       |\n"
            "| right    | right table + matches from left       |\n"
            "| outer    | both tables (union, NaN where missing)|\n\n"
            "## String and datetime columns\n\n"
            "```python\n"
            "df['email_domain'] = df['email'].str.split('@').str[-1]\n"
            "df['year'] = df['order_date'].dt.year\n"
            "df['weekday'] = df['order_date'].dt.day_name()\n"
            "```\n\n"
            "Access string methods via `.str`; datetime parts via `.dt`.\n\n"
            "## Handling missing data\n\n"
            "```python\n"
            "df.isna().sum()              # count NaN per column\n"
            "df.dropna(subset=['score'])  # drop rows with NaN in score\n"
            "df.fillna({'score': 0})      # replace NaN with 0\n"
            "df['score'].fillna(df['score'].mean())  # fill with column mean\n"
            "```\n\n"
            "## Real-world scenario: clean a CSV export\n\n"
            "```python\n"
            "def clean_sales(path: str) -> pd.DataFrame:\n"
            "    df = pd.read_csv(path, parse_dates=['date'])\n"
            "    df = df.dropna(subset=['amount'])\n"
            "    df = df[df['amount'] > 0]\n"
            "    df['amount'] = df['amount'].round(2)\n"
            "    return df.sort_values('date')\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Chained indexing `df[df.a]['b'] = x` — use `.loc` once: "
            "`df.loc[df['a'], 'b'] = x`\n"
            "- Duplicate column names after merge — suffixes with `suffixes=('_left', '_right')`\n"
            "- Loading entire CSV when `usecols` or `dtype` would save memory\n"
            "- Forgetting `index=False` when writing CSV (extra unnamed index column)\n"
            "- `groupby` without `.reset_index()` when you need a flat DataFrame\n"
            "- Comparing strings with `==` when whitespace differs — use `.str.strip()` first\n\n"
            "## Practice\n\n"
            "Filter rows where a numeric column meets a condition.\n\n"
            "## Summary\n\n"
            "DataFrame workflow: load → inspect → filter/select → transform → "
            "group/merge → export. Stay vectorized end to end — let pandas do the "
            "looping in C, not Python."
        ),
    },
]
