"""Requests track lesson guides."""

LESSONS = [
    {
        "slug": "01_requests_intro",
        "track": "requests",
        "difficulty": "easy",
        "title": "The requests Library",
        "tags": ["requests"],
        "exercise": "content/problems/requests/easy/01_build_request.py",
        "body": (
            "# The requests Library\n\n"
            "## Overview\n\n"
            "`requests` is the de facto HTTP client for Python. It wraps urllib3 with "
            "a simple, readable API — most scripts that call a web API use it. You send "
            "a method and URL; you get back a `Response` with status, headers, and body.\n\n"
            "Real-world uses:\n\n"
            "- Fetching data from public APIs (weather, GitHub, payment providers)\n"
            "- Posting webhooks or form submissions\n"
            "- Downloading files and images\n"
            "- Integration tests against staging servers\n\n"
            "Install with `pip install requests`.\n\n"
            "## Basic GET\n\n"
            "```python\n"
            "import requests\n\n"
            "response = requests.get('https://api.example.com/users', timeout=10)\n"
            "response.raise_for_status()  # raises on 4xx/5xx\n"
            "data = response.json()\n"
            "print(data[0]['name'])\n"
            "```\n\n"
            "**Always set `timeout=`** in production. Without it, a hung server blocks "
            "your process indefinitely.\n\n"
            "Inspect the response:\n\n"
            "```python\n"
            "response.status_code              # 200\n"
            "response.headers                  # case-insensitive dict-like\n"
            "response.headers.get('Content-Type')\n"
            "response.text                     # str body\n"
            "response.content                  # bytes body\n"
            "response.elapsed.total_seconds()  # request duration\n"
            "response.url                      # final URL (after redirects)\n"
            "```\n\n"
            "## POST with JSON\n\n"
            "```python\n"
            "response = requests.post(\n"
            "    'https://api.example.com/users',\n"
            "    json={'name': 'Ada', 'role': 'admin'},\n"
            "    headers={'Authorization': 'Bearer TOKEN'},\n"
            "    timeout=10,\n"
            ")\n"
            "response.raise_for_status()\n"
            "new_user = response.json()\n"
            "```\n\n"
            "- `json=` — serializes a dict to JSON and sets `Content-Type: application/json`\n"
            "- `data=` — form-encoded body (`application/x-www-form-urlencoded`)\n"
            "- `files=` — multipart uploads\n\n"
            "**Worked example:** upload a file:\n\n"
            "```python\n"
            "with open('report.pdf', 'rb') as f:\n"
            "    r = requests.post(\n"
            "        'https://api.example.com/upload',\n"
            "        files={'file': ('report.pdf', f, 'application/pdf')},\n"
            "        headers={'Authorization': 'Bearer TOKEN'},\n"
            "        timeout=30,\n"
            "    )\n"
            "    r.raise_for_status()\n"
            "```\n\n"
            "## Query parameters\n\n"
            "Pass `params=` as a dict — requests builds and encodes the query string:\n\n"
            "```python\n"
            "requests.get(\n"
            "    'https://api.example.com/search',\n"
            "    params={'q': 'python', 'page': 2, 'sort': 'newest'},\n"
            "    timeout=10,\n"
            ")\n"
            "# GET https://api.example.com/search?q=python&page=2&sort=newest\n"
            "```\n\n"
            "Never hand-build query strings with user input — special characters need "
            "URL encoding that `params=` handles automatically.\n\n"
            "## Building requests without sending\n\n"
            "Great for unit tests of URL construction — no network, no mocks needed "
            "for the URL part:\n\n"
            "```python\n"
            "from requests import Request, Session\n\n"
            "req = Request('GET', 'https://api.example.com/search', params={'q': 'py'})\n"
            "prepared = Session().prepare_request(req)\n"
            "assert prepared.method == 'GET'\n"
            "assert 'q=py' in prepared.url\n"
            "```\n\n"
            "**Worked example:** helper that builds a search URL:\n\n"
            "```python\n"
            "def prepare_search(base: str, query: str, page: int = 1) -> str:\n"
            "    req = Request('GET', base, params={'q': query, 'page': page})\n"
            "    return Session().prepare_request(req).url\n\n"
            "url = prepare_search('https://shop.example/api/items', 'blue socks', page=3)\n"
            "# https://shop.example/api/items?q=blue+socks&page=3\n"
            "```\n\n"
            "**Worked example:** inspect headers before sending:\n\n"
            "```python\n"
            "def build_auth_request(url: str, token: str) -> requests.PreparedRequest:\n"
            "    req = Request('GET', url, headers={'Authorization': f'Bearer {token}'})\n"
            "    return Session().prepare_request(req)\n\n"
            "prepared = build_auth_request('https://api.example.com/me', 'secret')\n"
            "assert prepared.headers['Authorization'] == 'Bearer secret'\n"
            "```\n\n"
            "## Real-world scenario: GitHub API call\n\n"
            "```python\n"
            "import os\n"
            "import requests\n\n"
            "TOKEN = os.environ['GITHUB_TOKEN']  # never hard-code secrets\n\n"
            "def list_repos(owner: str) -> list[dict]:\n"
            "    r = requests.get(\n"
            "        f'https://api.github.com/users/{owner}/repos',\n"
            "        headers={'Authorization': f'Bearer {TOKEN}', 'Accept': 'application/vnd.github+json'},\n"
            "        params={'sort': 'updated', 'per_page': 10},\n"
            "        timeout=10,\n"
            "    )\n"
            "    r.raise_for_status()\n"
            "    return r.json()\n"
            "```\n\n"
            "## Sessions\n\n"
            "A `Session` reuses TCP connections and persists cookies/headers:\n\n"
            "```python\n"
            "with requests.Session() as s:\n"
            "    s.headers.update({'User-Agent': 'myapp/1.0'})\n"
            "    s.get('https://api.example.com/page1', timeout=10)\n"
            "    s.get('https://api.example.com/page2', timeout=10)\n"
            "    # second call reuses the connection — faster\n"
            "```\n\n"
            "Use a session when calling the same host repeatedly.\n\n"
            "## Downloading large files\n\n"
            "```python\n"
            "with requests.get(url, stream=True, timeout=30) as r:\n"
            "    r.raise_for_status()\n"
            "    with open('output.bin', 'wb') as f:\n"
            "        for chunk in r.iter_content(chunk_size=8192):\n"
            "            f.write(chunk)\n"
            "```\n\n"
            "`stream=True` avoids loading the entire file into memory.\n\n"
            "## Error handling pattern\n\n"
            "```python\n"
            "try:\n"
            "    r = requests.get(url, timeout=10)\n"
            "    r.raise_for_status()\n"
            "    data = r.json()\n"
            "except requests.Timeout:\n"
            "    print('server too slow')\n"
            "except requests.HTTPError as e:\n"
            "    print(f'HTTP error: {e.response.status_code}')\n"
            "except requests.JSONDecodeError:\n"
            "    print('response was not JSON')\n"
            "except requests.RequestException as e:\n"
            "    print(f'network problem: {e}')\n"
            "```\n\n"
            "Do not call `.json()` until you know the response succeeded and is JSON.\n\n"
            "## Common pitfalls\n\n"
            "- No timeout → hung workers forever\n"
            "- Trusting `response.json()` without checking status (500 pages are often HTML)\n"
            "- Sending secrets in query strings (logged in proxies, browser history, server logs)\n"
            "- Hard-coding URLs and API keys — use environment variables or config files\n"
            "- Ignoring rate limits (HTTP 429) — back off and respect `Retry-After`\n"
            "- Not handling redirects explicitly when POSTing (use `allow_redirects=False` "
            "to inspect 302 responses)\n\n"
            "## Practice\n\n"
            "Build a prepared GET request with query parameters.\n\n"
            "## Summary\n\n"
            "requests = ergonomic HTTP for sync Python. Use `get`/`post` with `timeout`, "
            "check status with `raise_for_status()`, parse JSON only on success. Test URL "
            "building with `Request` + `Session().prepare_request()`; use `Session` for "
            "repeated calls to the same API."
        ),
    },
    {
        "slug": "02_sessions_cookies",
        "track": "requests",
        "difficulty": "medium",
        "title": "Sessions, Cookies, and Retries",
        "tags": ["session", "cookies"],
        "exercise": "content/problems/requests/easy/02_set_headers.py",
        "body": (
            "# Sessions, Cookies, and Retries\n\n"
            "## Overview\n\n"
            "A `requests.Session` is a persistent client: it keeps headers, cookies, "
            "and TCP connections across multiple requests. Use it whenever you talk to "
            "the same host more than once — it is faster and mirrors how browsers work.\n\n"
            "Real-world uses:\n\n"
            "- Authenticated API clients (Bearer token on every call)\n"
            "- Cookie-based login flows (session ID after POST /login)\n"
            "- Scraping sites that set cookies on first visit\n"
            "- Resilient integrations that retry transient 502/503 errors\n\n"
            "## Default headers on a session\n\n"
            "```python\n"
            "import requests\n\n"
            "session = requests.Session()\n"
            "session.headers['Authorization'] = f'Bearer {token}'\n"
            "session.headers['Accept'] = 'application/json'\n"
            "session.headers['User-Agent'] = 'myapp/2.1'\n\n"
            "r = session.get('https://api.example.com/me', timeout=10)\n"
            "```\n\n"
            "Per-request headers merge with session defaults. A call-level header "
            "overrides the session value for that request only:\n\n"
            "```python\n"
            "session.get(url, headers={'X-Request-Id': 'abc-123'}, timeout=10)\n"
            "```\n\n"
            "**Worked example:** API client class:\n\n"
            "```python\n"
            "class ApiClient:\n"
            "    def __init__(self, base_url: str, token: str):\n"
            "        self.session = requests.Session()\n"
            "        self.session.headers.update({\n"
            "            'Authorization': f'Bearer {token}',\n"
            "            'Accept': 'application/json',\n"
            "        })\n"
            "        self.base_url = base_url.rstrip('/')\n\n"
            "    def get_user(self, user_id: int) -> dict:\n"
            "        r = self.session.get(f'{self.base_url}/users/{user_id}', timeout=10)\n"
            "        r.raise_for_status()\n"
            "        return r.json()\n\n"
            "    def create_user(self, payload: dict) -> dict:\n"
            "        r = self.session.post(f'{self.base_url}/users', json=payload, timeout=10)\n"
            "        r.raise_for_status()\n"
            "        return r.json()\n"
            "```\n\n"
            "## Cookies\n\n"
            "Sessions include a cookie jar that mimics browser behavior:\n\n"
            "```python\n"
            "session = requests.Session()\n\n"
            "# login — server responds with Set-Cookie\n"
            "session.post(\n"
            "    'https://app.example.com/login',\n"
            "    json={'user': 'ada', 'pass': '...'},\n"
            "    timeout=10,\n"
            ")\n\n"
            "# subsequent requests send the session cookie automatically\n"
            "dashboard = session.get('https://app.example.com/dashboard', timeout=10)\n"
            "dashboard.raise_for_status()\n"
            "```\n\n"
            "Set cookies manually when needed:\n\n"
            "```python\n"
            "session.cookies.set('session_id', 'abc123', domain='app.example.com')\n"
            "```\n\n"
            "Inspect cookies: `session.cookies.get_dict()`.\n\n"
            "**Worked example:** two-step auth flow:\n\n"
            "```python\n"
            "def authenticated_session(username: str, password: str) -> requests.Session:\n"
            "    s = requests.Session()\n"
            "    r = s.post('https://app.example.com/login', json={'user': username, 'pass': password}, timeout=10)\n"
            "    r.raise_for_status()\n"
            "    return s  # cookie jar now holds session token\n"
            "```\n\n"
            "## Retries with urllib3\n\n"
            "Transient server errors (502, 503, 504) often resolve on retry. Mount "
            "a retry adapter on the session:\n\n"
            "```python\n"
            "from requests.adapters import HTTPAdapter\n"
            "from urllib3.util.retry import Retry\n\n"
            "retry = Retry(\n"
            "    total=3,\n"
            "    backoff_factor=0.5,\n"
            "    status_forcelist=[502, 503, 504],\n"
            "    allowed_methods=['GET', 'HEAD', 'OPTIONS'],\n"
            ")\n"
            "adapter = HTTPAdapter(max_retries=retry)\n"
            "session = requests.Session()\n"
            "session.mount('https://', adapter)\n"
            "session.mount('http://', adapter)\n"
            "```\n\n"
            "`backoff_factor=0.5` waits 0.5s, 1s, 2s between retries. **Retry POST "
            "carefully** — a succeeded request that timed out on the client can cause "
            "duplicates if you retry blindly. Use idempotency keys for payment APIs.\n\n"
            "## Handling rate limits (429)\n\n"
            "```python\n"
            "import time\n\n"
            "def get_with_backoff(session, url, max_retries=3):\n"
            "    for attempt in range(max_retries):\n"
            "        r = session.get(url, timeout=10)\n"
            "        if r.status_code != 429:\n"
            "            r.raise_for_status()\n"
            "            return r\n"
            "        wait = int(r.headers.get('Retry-After', 2 ** attempt))\n"
            "        time.sleep(wait)\n"
            "    raise RuntimeError('rate limited after retries')\n"
            "```\n\n"
            "## Context manager\n\n"
            "```python\n"
            "with requests.Session() as s:\n"
            "    s.headers['Authorization'] = f'Bearer {token}'\n"
            "    s.get(url1, timeout=10)\n"
            "    s.get(url2, timeout=10)\n"
            "# connections closed cleanly\n"
            "```\n\n"
            "One session per worker thread. Do not share a single Session across "
            "threads without care (urllib3 connection pool is not fully thread-safe "
            "for all usage patterns).\n\n"
            "## Testing sessions\n\n"
            "Test header merging logic directly without network:\n\n"
            "```python\n"
            "def build_session_headers(token: str) -> dict:\n"
            "    s = requests.Session()\n"
            "    s.headers['Authorization'] = f'Bearer {token}'\n"
            "    s.headers['Accept'] = 'application/json'\n"
            "    return dict(s.headers)\n\n"
            "assert build_session_headers('tok')['Authorization'] == 'Bearer tok'\n"
            "```\n\n"
            "For full HTTP mocking, use `responses` or `requests-mock` in pytest:\n\n"
            "```python\n"
            "import responses\n\n"
            "@responses.activate\n"
            "def test_get_user():\n"
            "    responses.add(responses.GET, 'https://api.test/users/1',\n"
            "                  json={'name': 'Ada'}, status=200)\n"
            "    client = ApiClient('https://api.test', 'fake-token')\n"
            "    assert client.get_user(1)['name'] == 'Ada'\n\n"
            "@responses.activate\n"
            "def test_create_user():\n"
            "    responses.add(responses.POST, 'https://api.test/users',\n"
            "                  json={'id': 42, 'name': 'Grace'}, status=201)\n"
            "    client = ApiClient('https://api.test', 'fake-token')\n"
            "    result = client.create_user({'name': 'Grace'})\n"
            "    assert result['id'] == 42\n"
            "```\n\n"
            "## Real-world scenario: paginated API with session\n\n"
            "```python\n"
            "def fetch_all_users(client: ApiClient) -> list[dict]:\n"
            "    users = []\n"
            "    page = 1\n"
            "    while True:\n"
            "        r = client.session.get(\n"
            "            f'{client.base_url}/users',\n"
            "            params={'page': page, 'limit': 100},\n"
            "            timeout=10,\n"
            "        )\n"
            "        r.raise_for_status()\n"
            "        batch = r.json()\n"
            "        if not batch:\n"
            "            break\n"
            "        users.extend(batch)\n"
            "        page += 1\n"
            "    return users\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Creating a new `Session()` per request (loses pooling and cookie benefits)\n"
            "- Retrying POST on 500 without idempotency keys\n"
            "- Storing session tokens in committed files (`cookies.txt`, `.env` in git)\n"
            "- Forgetting to set timeouts on session requests too\n"
            "- Assuming cookies persist after `Session` is closed — save tokens explicitly "
            "if you need them later\n"
            "- Not checking `Retry-After` on 429 responses\n\n"
            "## Practice\n\n"
            "Configure a session with shared auth headers.\n\n"
            "## Summary\n\n"
            "Session = persistent client state across requests. Configure default headers "
            "once, let cookies flow automatically, mount retry adapters for transient "
            "errors on safe methods, and use one session per logical client (per thread "
            "or async worker)."
        ),
    },
]
