"""Rich track lesson guides."""

LESSONS = [
    {
        "slug": "01_rich_intro",
        "track": "rich",
        "difficulty": "easy",
        "title": "Rich Terminal Output",
        "tags": ["rich", "console"],
        "exercise": "content/problems/rich/easy/01_build_table.py",
        "body": (
            "# Rich Terminal Output\n\n"
            "## Overview\n\n"
            "Rich renders beautiful terminal UI: colors, tables, progress bars, syntax "
            "highlighting, markdown, and trees. It detects terminal width and degrades "
            "gracefully when color is unavailable.\n\n"
            "Plain `print()` dumps raw text. Rich structures output so humans can "
            "scan it quickly — especially tables, errors, and nested data.\n\n"
            "Real-world uses:\n\n"
            "- CLI tools that need readable output for humans (not machines)\n"
            "- Debug dashboards during long-running data imports\n"
            "- Pretty-printing nested JSON or config in dev tools\n"
            "- Status tables in deployment scripts\n\n"
            "Install with `pip install rich`. Run `python -m rich` to see a demo "
            "of everything Rich can do.\n\n"
            "## Console basics\n\n"
            "```python\n"
            "from rich.console import Console\n\n"
            "console = Console()\n"
            "console.print('plain text')\n"
            "console.print('[bold green]Success[/] operation complete')\n"
            "console.print({'user': 'Ada', 'score': 98})  # pretty dict\n"
            "console.print('[red]Error:[/] file not found', style='bold')\n"
            "```\n\n"
            "Markup uses `[style]` tags inspired by BBCode. Close with `[/]` or "
            "`[/bold green]`. Common styles: `bold`, `italic`, `dim`, `underline`, "
            "and colors like `red`, `cyan`, `bright_white`.\n\n"
            "**Worked example:** status messages:\n\n"
            "```python\n"
            "def log_ok(console: Console, msg: str) -> None:\n"
            "    console.print(f'[green]OK[/] {msg}')\n\n"
            "def log_err(console: Console, msg: str) -> None:\n"
            "    console.print(f'[red]FAIL[/] {msg}')\n\n"
            "def log_warn(console: Console, msg: str) -> None:\n"
            "    console.print(f'[yellow]WARN[/] {msg}')\n"
            "```\n\n"
            "## Tables\n\n"
            "Tables are the most common Rich structure in exercises:\n\n"
            "```python\n"
            "from rich.console import Console\n"
            "from rich.table import Table\n\n"
            "console = Console()\n"
            "table = Table(title='Users')\n"
            "table.add_column('Name', style='cyan')\n"
            "table.add_column('Score', justify='right', style='magenta')\n"
            "table.add_row('Ada', '98')\n"
            "table.add_row('Grace', '95')\n"
            "console.print(table)\n"
            "```\n\n"
            "Build tables programmatically from data:\n\n"
            "```python\n"
            "users = [('Ada', 98), ('Grace', 95), ('Linus', 88)]\n"
            "table = Table(title='Leaderboard')\n"
            "table.add_column('Name')\n"
            "table.add_column('Score', justify='right')\n"
            "for name, score in users:\n"
            "    table.add_row(name, str(score))\n"
            "assert table.row_count == 3\n"
            "```\n\n"
            "Tables expose `.columns` and `.rows` for testing without rendering ANSI.\n\n"
            "**Worked example:** build table from list of dicts:\n\n"
            "```python\n"
            "def build_user_table(records: list[dict]) -> Table:\n"
            "    table = Table(title='Users')\n"
            "    table.add_column('ID', justify='right')\n"
            "    table.add_column('Name')\n"
            "    table.add_column('Role')\n"
            "    for r in records:\n"
            "        table.add_row(str(r['id']), r['name'], r['role'])\n"
            "    return table\n\n"
            "t = build_user_table([{'id': 1, 'name': 'Ada', 'role': 'admin'}])\n"
            "assert t.row_count == 1\n"
            "```\n\n"
            "## Capturing output in tests\n\n"
            "Redirect Console output to a string buffer:\n\n"
            "```python\n"
            "import io\n"
            "from rich.console import Console\n\n"
            "buf = io.StringIO()\n"
            "console = Console(file=buf, width=80, force_terminal=True)\n"
            "console.print('[bold]hello[/]')\n"
            "text = buf.getvalue()\n"
            "assert 'hello' in text\n"
            "```\n\n"
            "For tables, prefer asserting structure over parsing ANSI escape codes:\n\n"
            "```python\n"
            "assert table.row_count == 2\n"
            "assert table.columns[0].header == 'Name'\n"
            "```\n\n"
            "## Panels and rules\n\n"
            "Group related output visually:\n\n"
            "```python\n"
            "from rich.panel import Panel\n"
            "from rich.rule import Rule\n\n"
            "console.print(Rule('[bold]Results'))\n"
            "console.print(Panel('Deployment finished successfully.', title='Done', border_style='green'))\n"
            "console.print(Panel('Connection refused on port 5432.', title='Error', border_style='red'))\n"
            "```\n\n"
            "## Syntax highlighting and JSON\n\n"
            "```python\n"
            "from rich.syntax import Syntax\n"
            "from rich.json import JSON\n\n"
            "code = 'def hello():\\n    return 42'\n"
            "console.print(Syntax(code, 'python', theme='monokai', line_numbers=True))\n"
            "console.print(JSON('{\"active\": true, \"count\": 3}'))\n"
            "```\n\n"
            "Great for CLI tools that display config files or API responses.\n\n"
            "## Progress bars (preview)\n\n"
            "```python\n"
            "from rich.progress import track\n\n"
            "for item in track(range(100), description='Processing...'):\n"
            "    ...  # work\n"
            "```\n\n"
            "Rich handles spinner, percentage, and ETA automatically.\n\n"
            "## Real-world scenario: deployment summary\n\n"
            "```python\n"
            "from rich.console import Console\n"
            "from rich.table import Table\n\n"
            "def print_deploy_summary(services: list[dict]) -> None:\n"
            "    console = Console()\n"
            "    table = Table(title='Deploy Results')\n"
            "    table.add_column('Service')\n"
            "    table.add_column('Status', justify='center')\n"
            "    for svc in services:\n"
            "        status = '[green]OK[/]' if svc['ok'] else '[red]FAIL[/]'\n"
            "        table.add_row(svc['name'], status)\n"
            "    console.print(table)\n\n"
            "print_deploy_summary([\n"
            "    {'name': 'api', 'ok': True},\n"
            "    {'name': 'worker', 'ok': False},\n"
            "])\n"
            "```\n\n"
            "## When to use Rich\n\n"
            "- CLI tools for humans (not machine-parseable stdout)\n"
            "- Long scripts where you want visibility without a GUI\n"
            "- Nested data structures that `print()` makes unreadable\n\n"
            "When **not** to use Rich: output piped to another program (`mytool | jq`) "
            "— provide a `--plain` flag that prints simple text.\n\n"
            "## Common pitfalls\n\n"
            "- Parsing ANSI codes in tests — capture via Console or inspect table structure\n"
            "- Assuming wide terminal — set `width=` in tests for consistent layout\n"
            "- Rich in CI without `force_terminal=True` when you need styles applied\n"
            "- Forgetting Rich adds escape codes — `len(output)` != visible character count\n"
            "- Mixing `print()` and `console.print()` — stick to one Console instance\n\n"
            "## Practice\n\n"
            "Build a table programmatically and assert row count.\n\n"
            "## Summary\n\n"
            "Rich = structured terminal rendering. Create `Console`, build data structures "
            "(Table, Panel), and let Rich handle layout and color. Test by inspecting "
            "table rows/columns or capturing output to a StringIO buffer."
        ),
    },
    {
        "slug": "02_tables_panels",
        "track": "rich",
        "difficulty": "medium",
        "title": "Tables, Panels, and Layout",
        "tags": ["rich", "layout"],
        "exercise": "content/problems/rich/easy/04_panel_wrap.py",
        "body": (
            "# Tables, Panels, and Layout\n\n"
            "## Overview\n\n"
            "Beyond single tables, Rich composes layouts: styled columns, stacked panels, "
            "and live-updating displays. This lesson covers structuring CLI dashboards "
            "that stay readable in narrow terminals.\n\n"
            "Real-world uses:\n\n"
            "- Deployment dashboards (service status side by side)\n"
            "- Test runners showing pass/fail panels per suite\n"
            "- Download managers with live progress tables\n"
            "- Log tailers with highlighted error panels\n\n"
            "## Table styling in depth\n\n"
            "```python\n"
            "from rich.table import Table\n\n"
            "table = Table(\n"
            "    title='Service Health',\n"
            "    show_header=True,\n"
            "    header_style='bold magenta',\n"
            "    border_style='blue',\n"
            "    show_lines=True,\n"
            ")\n"
            "table.add_column('ID', style='dim', width=6)\n"
            "table.add_column('Service', min_width=12)\n"
            "table.add_column('Status', justify='center')\n"
            "table.add_column('Latency', justify='right')\n"
            "table.add_row('1', 'api-gateway', '[green]OK[/]', '42ms')\n"
            "table.add_row('2', 'worker', '[red]DOWN[/]', '-')\n"
            "```\n\n"
            "Column `width` fixes size; `min_width`/`max_width` constrain flexible "
            "columns. `justify` controls alignment: `left`, `center`, `right`.\n\n"
            "**Worked example:** build status table from dicts:\n\n"
            "```python\n"
            "services = [\n"
            "    {'id': 1, 'name': 'api', 'ok': True, 'ms': 42},\n"
            "    {'id': 2, 'name': 'db', 'ok': False, 'ms': None},\n"
            "]\n"
            "table = Table(title='Health')\n"
            "table.add_column('ID', justify='right')\n"
            "table.add_column('Name')\n"
            "table.add_column('Status', justify='center')\n"
            "table.add_column('Latency', justify='right')\n"
            "for s in services:\n"
            "    status = '[green]OK[/]' if s['ok'] else '[red]FAIL[/]'\n"
            "    latency = f\"{s['ms']}ms\" if s['ms'] is not None else '-'\n"
            "    table.add_row(str(s['id']), s['name'], status, latency)\n"
            "```\n\n"
            "## Panel variants\n\n"
            "Panels wrap content with a border and optional title:\n\n"
            "```python\n"
            "from rich.panel import Panel\n"
            "from rich.text import Text\n\n"
            "error = Text.from_markup('[red]Error[/]: connection timeout after 30s')\n"
            "panel = Panel(error, title='API', border_style='red', expand=False)\n"
            "console.print(panel)\n"
            "```\n\n"
            "Wrap long text with explicit width:\n\n"
            "```python\n"
            "Panel('Short status message.', title='Build #42', border_style='green')\n"
            "Panel(long_log_text, title='stderr', width=80)\n"
            "```\n\n"
            "**Worked example:** wrap status in a panel (exercise pattern):\n\n"
            "```python\n"
            "def make_status_panel(message: str, title: str = 'Status') -> Panel:\n"
            "    return Panel(message, title=title, border_style='blue', expand=False)\n\n"
            "p = make_status_panel('All systems operational')\n"
            "assert p.title == 'Status'\n"
            "assert p.renderable == 'All systems operational'\n"
            "```\n\n"
            "## Columns layout\n\n"
            "Display panels side by side:\n\n"
            "```python\n"
            "from rich.columns import Columns\n\n"
            "ok_panel = Panel('All tests passed', title='Unit', border_style='green')\n"
            "warn_panel = Panel('2 warnings', title='Lint', border_style='yellow')\n"
            "console.print(Columns([ok_panel, warn_panel], equal=True, expand=True))\n"
            "```\n\n"
            "Rich reflows columns when the terminal is too narrow.\n\n"
            "## Live display\n\n"
            "Update a table in place without flooding scrollback:\n\n"
            "```python\n"
            "import time\n"
            "from rich.live import Live\n"
            "from rich.table import Table\n\n"
            "table = Table()\n"
            "table.add_column('Step')\n"
            "table.add_column('Status')\n\n"
            "with Live(table, refresh_per_second=4):\n"
            "    for step in ['fetch', 'validate', 'upload', 'done']:\n"
            "        table.add_row(step, 'running...')\n"
            "        time.sleep(0.5)\n"
            "        table.rows[-1] = (step, '[green]done[/]')\n"
            "```\n\n"
            "Use `Live` for progress dashboards; use `track` for simple loops.\n\n"
            "## Tree and Markdown\n\n"
            "```python\n"
            "from rich.tree import Tree\n"
            "from rich.markdown import Markdown\n\n"
            "tree = Tree('[bold]Project[/]')\n"
            "src = tree.add('[cyan]src[/]')\n"
            "src.add('main.py')\n"
            "src.add('utils.py')\n"
            "console.print(tree)\n\n"
            "console.print(Markdown('# Release Notes\\n\\n- Fixed login bug\\n- Updated deps'))\n"
            "```\n\n"
            "## Group and Align\n\n"
            "```python\n"
            "from rich.align import Align\n"
            "from rich.console import Group\n\n"
            "console.print(Align.center('[bold]Deploy Summary[/]'))\n"
            "console.print(Group(panel_a, panel_b, table))\n"
            "```\n\n"
            "## Real-world scenario: test runner dashboard\n\n"
            "```python\n"
            "def print_test_results(results: list[dict]) -> None:\n"
            "    passed = sum(1 for r in results if r['passed'])\n"
            "    failed = len(results) - passed\n"
            "    summary = Panel(\n"
            "        f'[green]{passed} passed[/]  [red]{failed} failed[/]',\n"
            "        title='Summary',\n"
            "        border_style='cyan',\n"
            "    )\n"
            "    table = Table(title='Failures')\n"
            "    table.add_column('Test')\n"
            "    table.add_column('Error')\n"
            "    for r in results:\n"
            "        if not r['passed']:\n"
            "            table.add_row(r['name'], r['error'])\n"
            "    console.print(Group(summary, table))\n"
            "```\n\n"
            "## Testing structured output\n\n"
            "Assert on data, not rendered strings:\n\n"
            "```python\n"
            "def make_panel(message: str, title: str) -> Panel:\n"
            "    return Panel(message, title=title, border_style='blue')\n\n"
            "p = make_panel('ready', 'Status')\n"
            "assert p.title == 'Status'\n"
            "assert p.renderable == 'ready'\n"
            "```\n\n"
            "For tables: check `table.row_count`, column headers, and cell values "
            "before calling `console.print()`.\n\n"
            "## Common pitfalls\n\n"
            "- Live display without bounding rows — table grows forever; replace rows "
            "or clear periodically\n"
            "- Nested panels exceeding terminal height — use `height=` or scroll in "
            "an external pager\n"
            "- Hard-coding Unicode box chars — use Rich primitives so width math works\n"
            "- Mixing `print()` and `console.print()` — stick to one Console instance\n"
            "- Forgetting `expand=False` on panels in narrow layouts\n\n"
            "## Practice\n\n"
            "Wrap status text in a styled panel with a title.\n\n"
            "## Summary\n\n"
            "Compose small Rich objects into layouts. Style tables with column width and "
            "justify; wrap messages in Panels; place panels side by side with Columns; "
            "use Live for in-place updates. Test the objects you build, not the ANSI output."
        ),
    },
]
