"""Servers track lesson guides."""

LESSONS = [
    {
        "slug": "01_routing",
        "track": "servers",
        "difficulty": "easy",
        "title": "Request Routing",
        "tags": ["routing"],
        "exercise": "content/problems/servers/easy/01_route_matcher.py",
        "body": (
            "# Request Routing\n\n"
            "## Overview\n\n"
            "Routing maps an incoming request (method + path) to the code that handles it. "
            "Every web framework — from a 50-line stdlib server to FastAPI — has a router "
            "at its core.\n\n"
            "When a browser requests `GET /users/42`, the server must answer two questions: "
            "which function runs, and what is `42`? Routing is that decision step — classify "
            "the request, extract parameters, call the handler, return a response.\n\n"
            "If you have written `if path == '/health':` in a script, you already understand "
            "routing at a basic level. Production routers add patterns, method checks, and "
            "clean 404/405 responses.\n\n"
            "## Static routes\n\n"
            "The simplest router is a dictionary lookup keyed by method and path:\n\n"
            "```python\n"
            "def home(request):\n"
            "    return {'status': 200, 'body': 'welcome'}\n\n"
            "def health(request):\n"
            "    return {'status': 200, 'body': 'ok'}\n\n"
            "def not_found(request):\n"
            "    return {'status': 404, 'body': 'not found'}\n\n"
            "routes = {\n"
            "    ('GET', '/'): home,\n"
            "    ('GET', '/health'): health,\n"
            "}\n\n"
            "def dispatch(method: str, path: str, request: dict) -> dict:\n"
            "    handler = routes.get((method, path), not_found)\n"
            "    return handler(request)\n"
            "```\n\n"
            "Try it in the REPL:\n\n"
            "```python\n"
            "dispatch('GET', '/health', {})   # {'status': 200, 'body': 'ok'}\n"
            "dispatch('GET', '/missing', {})  # {'status': 404, ...}\n"
            "```\n\n"
            "This works for fixed paths. Real APIs need paths with variable segments.\n\n"
            "## Path parameters\n\n"
            "When a segment varies (`/users/42`), match with a pattern and capture groups:\n\n"
            "```python\n"
            "import re\n\n"
            "USER_PATTERN = re.compile(r'^/users/(?P<id>\\d+)$')\n\n"
            "def match_user(path: str) -> dict | None:\n"
            "    m = USER_PATTERN.match(path)\n"
            "    if m:\n"
            "        return {'id': int(m.group('id'))}\n"
            "    return None\n\n"
            "match_user('/users/42')   # {'id': 42}\n"
            "match_user('/users/abc')  # None\n"
            "```\n\n"
            "Frameworks expose the same idea as `/users/{id}` or `/users/<id>` — you write "
            "a template; the framework compiles it to a regex or trie.\n\n"
            "Convert captured strings to the types your handler expects:\n\n"
            "```python\n"
            "def get_user(path: str) -> dict | None:\n"
            "    params = match_user(path)\n"
            "    if params is None:\n"
            "        return None\n"
            "    user_id = params['id']\n"
            "    return {'id': user_id, 'name': f'User {user_id}'}\n"
            "```\n\n"
            "## Worked example: template matcher\n\n"
            "Convert a path template into a regex and extract named groups:\n\n"
            "```python\n"
            "import re\n\n"
            "def compile_template(template: str) -> re.Pattern:\n"
            "    parts = []\n"
            "    for segment in template.strip('/').split('/'):\n"
            "        if segment.startswith('{') and segment.endswith('}'):\n"
            "            name = segment[1:-1]\n"
            "            parts.append(f'(?P<{name}>[^/]+)')\n"
            "        else:\n"
            "            parts.append(re.escape(segment))\n"
            "    pattern = '^/' + '/'.join(parts) + '$'\n"
            "    return re.compile(pattern)\n\n"
            "route = compile_template('/users/{id}/posts/{slug}')\n"
            "m = route.match('/users/42/posts/hello-world')\n"
            "m.groupdict()  # {'id': '42', 'slug': 'hello-world'}\n"
            "```\n\n"
            "Step by step:\n"
            "1. Split the template on `/`.\n"
            "2. `{id}` becomes a named capture group `(?P<id>[^/]+)`.\n"
            "3. Literal segments are escaped so `.` does not mean any character.\n"
            "4. `^` and `$` anchor the match to the full path.\n\n"
            "Build a small router that tries templates in order:\n\n"
            "```python\n"
            "TEMPLATES = [\n"
            "    ('/users/{id}', get_user_handler),\n"
            "    ('/health', health_handler),\n"
            "]\n"
            "COMPILED = [(compile_template(t), fn) for t, fn in TEMPLATES]\n\n"
            "def route_request(method: str, path: str) -> dict:\n"
            "    for pattern, handler in COMPILED:\n"
            "        m = pattern.match(path)\n"
            "        if m:\n"
            "            return handler(method, m.groupdict())\n"
            "    return {'status': 404, 'body': 'not found'}\n"
            "```\n\n"
            "Register specific paths before wildcards so `/users/me` is not captured "
            "as `{id}`.\n\n"
            "## Method-aware routing\n\n"
            "The same path can mean different things for different HTTP methods:\n\n"
            "```python\n"
            "routes = {\n"
            "    ('GET', '/items'): list_items,\n"
            "    ('POST', '/items'): create_item,\n"
            "}\n\n"
            "def dispatch(method: str, path: str, request: dict) -> dict:\n"
            "    handler = routes.get((method, path))\n"
            "    if handler is None:\n"
            "        if any(k[1] == path for k in routes):\n"
            "            return {'status': 405, 'body': 'method not allowed'}\n"
            "        return {'status': 404, 'body': 'not found'}\n"
            "    return handler(request)\n"
            "```\n\n"
            "```\n"
            "GET  /items  → list\n"
            "POST /items  → create\n"
            "```\n\n"
            "Always key routes by `(method, path)` tuple or equivalent. Return "
            "405 Method Not Allowed when the path exists but the verb does not.\n\n"
            "Worked example: distinguish 404 vs 405:\n\n"
            "```python\n"
            "routes = {('GET', '/items'): list_items}\n\n"
            "dispatch('DELETE', '/items', {})  # 405 — path exists, method wrong\n"
            "dispatch('GET', '/orders', {})    # 404 — path unknown\n"
            "```\n\n"
            "## Middleware order\n\n"
            "Request flows through layers before your handler runs:\n\n"
            "```\n"
            "socket → parse request → middleware chain → router → handler → response\n"
            "```\n\n"
            "Auth and logging middleware run before the router; error handlers wrap the "
            "outside so exceptions become proper HTTP responses.\n\n"
            "The router sits *after* parsing (you need method and path) but *before* "
            "business logic (the handler should receive extracted params).\n\n"
            "## Worked example: end-to-end mini server flow\n\n"
            "Tie routing pieces together without a framework:\n\n"
            "```python\n"
            "def handle_request(method: str, path: str) -> dict:\n"
            "    static = routes.get((method, path))\n"
            "    if static:\n"
            "        return static({})\n"
            "    params = match_user(path)\n"
            "    if params and method == 'GET':\n"
            "        return {'status': 200, 'body': f'user {params[\"id\"]}'}\n"
            "    if params:\n"
            "        return {'status': 405, 'body': 'method not allowed'}\n"
            "    return {'status': 404, 'body': 'not found'}\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Trailing slash mismatches (`/users` vs `/users/`) — pick one convention\n"
            "- Greedy patterns that swallow too much of the path — use `[^/]+` per segment\n"
            "- Forgetting to return 405 Method Not Allowed for wrong verb\n"
            "- Matching routes in arbitrary order — register specific paths before wildcards\n"
            "- Leaving captured params as strings when you need `int` or `UUID`\n"
            "- Case-sensitive paths on Linux — `/Users` and `/users` are different\n\n"
            "## Practice\n\n"
            "Implement a matcher that extracts named groups from a path template.\n\n"
            "## Summary\n\n"
            "Routing = classify request → call handler. Start with dict lookup; add regex "
            "or trie when paths have parameters. Key by `(method, path)`, extract params "
            "with named groups, and distinguish 404 (unknown path) from 405 (wrong method)."
        ),
    },
    {
        "slug": "02_middleware",
        "track": "servers",
        "difficulty": "medium",
        "title": "Middleware and Request Lifecycle",
        "tags": ["middleware", "wsgi"],
        "exercise": "content/problems/servers/easy/10_request_log_line.py",
        "body": (
            "# Middleware and Request Lifecycle\n\n"
            "## Overview\n\n"
            "Middleware wraps request handling to add cross-cutting behavior: logging, "
            "authentication, CORS headers, compression, error pages. Each layer calls "
            "the next inner layer.\n\n"
            "Handlers should focus on business logic (create user, fetch order). "
            "Middleware handles concerns that apply to *many* routes — things you "
            "do not want to copy-paste into every handler.\n\n"
            "Imagine peeling an onion: the request travels inward through layers until "
            "it reaches your handler, then the response travels back out through the "
            "same layers in reverse order.\n\n"
            "## Onion model\n\n"
            "Picture nested wrappers. The request enters from the outside; the response "
            "unwinds back out:\n\n"
            "```\n"
            "Request  → [Logging] → [Auth] → [Router] → Handler\n"
            "Response ← [Logging] ← [Auth] ← [Router] ← Handler\n"
            "```\n\n"
            "Outer middleware sees the request first and the response last. That is why "
            "logging middleware can record total time including inner layers.\n\n"
            "Order matters:\n\n"
            "```\n"
            "1. Error handler (outermost — catches exceptions from everything inside)\n"
            "2. Logging / timing\n"
            "3. CORS (before response leaves)\n"
            "4. Authentication (attach user to request)\n"
            "5. Router + handler (innermost)\n"
            "```\n\n"
            "## Simple WSGI-style wrapper\n\n"
            "WSGI apps are callables `(environ, start_response) -> iterable`. "
            "Middleware is a function that takes an app and returns a new app:\n\n"
            "```python\n"
            "def logging_middleware(app):\n"
            "    def wrapper(environ, start_response):\n"
            "        method = environ.get('REQUEST_METHOD', 'GET')\n"
            "        path = environ.get('PATH_INFO', '/')\n"
            "        print(f'{method} {path}')\n"
            "        return app(environ, start_response)\n"
            "    return wrapper\n"
            "```\n\n"
            "Stack middleware by nesting — outermost runs first on the way in:\n\n"
            "```python\n"
            "app = logging_middleware(timing_middleware(core_app))\n"
            "```\n\n"
            "Reading the stack right-to-left: `core_app` is innermost; `logging_middleware` "
            "wraps everything and runs first when a request arrives.\n\n"
            "## Worked example: request log line with timing\n\n"
            "A practical logger records method, path, status, and duration:\n\n"
            "```python\n"
            "import time\n\n"
            "def request_log_middleware(app):\n"
            "    def wrapper(environ, start_response):\n"
            "        start = time.perf_counter()\n"
            "        method = environ.get('REQUEST_METHOD', 'GET')\n"
            "        path = environ.get('PATH_INFO', '/')\n"
            "        status_holder = []\n\n"
            "        def custom_start_response(status, headers, exc_info=None):\n"
            "            status_holder.append(status)\n"
            "            return start_response(status, headers, exc_info)\n\n"
            "        try:\n"
            "            result = app(environ, custom_start_response)\n"
            "        finally:\n"
            "            elapsed_ms = (time.perf_counter() - start) * 1000\n"
            "            code = status_holder[0].split()[0] if status_holder else '???'\n"
            "            print(f'{method} {path} {code} {elapsed_ms:.1f}ms')\n"
            "        return result\n"
            "    return wrapper\n"
            "```\n\n"
            "Step by step:\n"
            "1. Record start time before calling the inner app.\n"
            "2. Wrap `start_response` to capture the HTTP status code.\n"
            "3. Call the inner app — it may be routing, auth, or the real handler.\n"
            "4. In `finally`, log one line regardless of success or exception.\n\n"
            "Example output: `GET /health 200 1.3ms`\n\n"
            "Why wrap `start_response`? The inner app chooses the status (200, 404, 500). "
            "Middleware that only logs before calling the inner app would not know the "
            "final status.\n\n"
            "## Worked example: add a response header\n\n"
            "Middleware can modify headers on the way out:\n\n"
            "```python\n"
            "def security_headers_middleware(app):\n"
            "    def wrapper(environ, start_response):\n"
            "        def custom_start_response(status, headers, exc_info=None):\n"
            "            headers = list(headers)\n"
            "            headers.append(('X-Content-Type-Options', 'nosniff'))\n"
            "            return start_response(status, headers, exc_info)\n"
            "        return app(environ, custom_start_response)\n"
            "    return wrapper\n"
            "```\n\n"
            "Every response now includes `X-Content-Type-Options: nosniff` without "
            "touching individual handlers.\n\n"
            "## Worked example: global exception handler\n\n"
            "Convert uncaught errors into JSON 500 responses:\n\n"
            "```python\n"
            "import json\n\n"
            "def error_middleware(app):\n"
            "    def wrapper(environ, start_response):\n"
            "        try:\n"
            "            return app(environ, start_response)\n"
            "        except Exception:\n"
            "            body = json.dumps({'error': 'internal_server_error'}).encode()\n"
            "            start_response('500 Internal Server Error', [\n"
            "                ('Content-Type', 'application/json'),\n"
            "                ('Content-Length', str(len(body))),\n"
            "            ])\n"
            "            return [body]\n"
            "    return wrapper\n"
            "```\n\n"
            "Place this outermost so it catches failures from auth, routing, and handlers.\n\n"
            "## ASGI (async) equivalent\n\n"
            "Modern async frameworks use ASGI. The shape is the same — wrap the inner "
            "app — but with `async def` and `scope`, `receive`, `send`:\n\n"
            "```python\n"
            "class LoggingMiddleware:\n"
            "    def __init__(self, app):\n"
            "        self.app = app\n\n"
            "    async def __call__(self, scope, receive, send):\n"
            "        if scope['type'] == 'http':\n"
            "            method = scope['method']\n"
            "            path = scope['path']\n"
            "            print(f'{method} {path}')\n"
            "        await self.app(scope, receive, send)\n"
            "```\n\n"
            "FastAPI and Starlette build on this pattern. The wrapping idea is identical "
            "to WSGI — only the callable signature changes.\n\n"
            "## What belongs in middleware\n\n"
            "- Request/response logging with timing\n"
            "- Adding security headers (`X-Content-Type-Options`, etc.)\n"
            "- Session cookie parsing (attach user to request context)\n"
            "- Global exception → JSON error mapping\n"
            "- CORS headers for browser clients\n\n"
            "## What does NOT belong\n\n"
            "- Business logic specific to one route (put that in the handler)\n"
            "- Heavy DB queries per request without caching\n"
            "- Parsing request bodies for a single endpoint\n\n"
            "## Stacking middleware: full example\n\n"
            "```python\n"
            "def build_app(core):\n"
            "  app = core\n"
            "  app = security_headers_middleware(app)\n"
            "  app = request_log_middleware(app)\n"
            "  app = error_middleware(app)   # outermost\n"
            "  return app\n"
            "```\n\n"
            "Each line wraps the previous `app`. The last wrapper added is the first "
            "to see incoming requests.\n\n"
            "## Common pitfalls\n\n"
            "- Middleware that forgets to call the inner app — requests hang forever\n"
            "- Swallowing exceptions without re-raising or converting to 500 JSON\n"
            "- Wrong order: CORS must run early; auth before handlers that need identity\n"
            "- Mutating global state per request without thread/async safety\n"
            "- Logging bodies with passwords or API keys\n"
            "- Forgetting to return the inner app's iterable (WSGI) or await it (ASGI)\n\n"
            "## Practice\n\n"
            "Build a request logger that records method and path.\n\n"
            "## Summary\n\n"
            "Middleware composes behavior around handlers. Keep each layer focused; "
            "order matters. Wrap the inner app, always call through, and use the onion "
            "model to decide what runs before routing versus after the handler returns."
        ),
    },
]
