"""SQLite track lesson guides."""

LESSONS = [
    {
        "slug": "01_sqlite_intro",
        "track": "sqlite",
        "difficulty": "easy",
        "title": "sqlite3 and In-Memory Databases",
        "tags": ["sqlite", "sql"],
        "exercise": "content/problems/sqlite/easy/01_create_insert_query.py",
        "body": (
            "# sqlite3 and In-Memory Databases\n\n"
            "## Overview\n\n"
            "SQLite is a full SQL database engine in a single file — or entirely in RAM. "
            "Python's `sqlite3` module is in the standard library, so there is nothing "
            "extra to install. It is ideal for local apps, prototypes, and fast unit tests.\n\n"
            "Unlike client/server databases (PostgreSQL, MySQL), SQLite runs inside "
            "your Python process. No separate server to start or configure.\n\n"
            "Real-world uses:\n\n"
            "- Desktop app local storage (browser history, notes apps)\n"
            "- Prototyping before moving to PostgreSQL\n"
            "- Caching structured data between script runs\n"
            "- Unit tests with `:memory:` databases (isolated, instant teardown)\n\n"
            "## Connecting\n\n"
            "```python\n"
            "import sqlite3\n\n"
            "conn = sqlite3.connect(':memory:')  # RAM only — gone when closed\n"
            "conn = sqlite3.connect('app.db')    # persistent file on disk\n"
            "```\n\n"
            "Use `:memory:` in tests — each test gets a clean database with zero "
            "filesystem cleanup. Use a file path for apps that need data to survive "
            "restarts.\n\n"
            "Context manager closes the connection automatically:\n\n"
            "```python\n"
            "with sqlite3.connect('app.db') as conn:\n"
            "    conn.execute('SELECT 1')\n"
            "# conn closed here\n"
            "```\n\n"
            "## DDL and DML\n\n"
            "Create tables, insert rows, commit changes:\n\n"
            "```python\n"
            "conn = sqlite3.connect(':memory:')\n"
            "conn.execute('''\n"
            "    CREATE TABLE users (\n"
            "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n"
            "        name TEXT NOT NULL,\n"
            "        email TEXT UNIQUE\n"
            "    )\n"
            "''')\n"
            "conn.executemany(\n"
            "    'INSERT INTO users (name, email) VALUES (?, ?)',\n"
            "    [\n"
            "        ('Ada Lovelace', 'ada@example.com'),\n"
            "        ('Grace Hopper', 'grace@example.com'),\n"
            "    ],\n"
            ")\n"
            "conn.commit()\n"
            "```\n\n"
            "**Worked example:** seed and query in a test fixture:\n\n"
            "```python\n"
            "def make_db():\n"
            "    conn = sqlite3.connect(':memory:')\n"
            "    conn.execute('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)')\n"
            "    conn.executemany('INSERT INTO users (name) VALUES (?)', [('Ada',), ('Grace',)])\n"
            "    conn.commit()\n"
            "    return conn\n\n"
            "conn = make_db()\n"
            "rows = conn.execute('SELECT name FROM users ORDER BY name').fetchall()\n"
            "# [('Ada',), ('Grace',)]\n"
            "```\n\n"
            "## Querying\n\n"
            "```python\n"
            "rows = conn.execute(\n"
            "    'SELECT id, name FROM users ORDER BY name'\n"
            ").fetchall()\n"
            "# [(2, 'Grace Hopper'), (1, 'Ada Lovelace')]\n\n"
            "one = conn.execute(\n"
            "    'SELECT name FROM users WHERE id = ?', (1,)\n"
            ").fetchone()\n"
            "# ('Ada Lovelace',)\n"
            "```\n\n"
            "- `fetchone()` — one row or `None`\n"
            "- `fetchall()` — list of all rows\n"
            "- `fetchmany(n)` — batch for large result sets\n\n"
            "**Always use `?` placeholders** — never f-string SQL with user input:\n\n"
            "```python\n"
            "# DANGEROUS — SQL injection\n"
            "conn.execute(f\"SELECT * FROM users WHERE name = '{user_input}'\")\n\n"
            "# SAFE\n"
            "conn.execute('SELECT * FROM users WHERE name = ?', (user_input,))\n"
            "```\n\n"
            "## Row factories\n\n"
            "By default rows are tuples. Enable dict-like access:\n\n"
            "```python\n"
            "conn.row_factory = sqlite3.Row\n"
            "row = conn.execute('SELECT * FROM users WHERE id = 1').fetchone()\n"
            "row['name']   # 'Ada Lovelace'\n"
            "row.keys()    # column names\n"
            "dict(row)     # plain dict\n"
            "```\n\n"
            "Much easier to read than `row[1]` when you have many columns.\n\n"
            "## Transactions\n\n"
            "Wrap related writes so they succeed or fail together:\n\n"
            "```python\n"
            "with conn:\n"
            "    conn.execute('INSERT INTO users (name) VALUES (?)', ('New User',))\n"
            "    conn.execute('INSERT INTO audit_log (action) VALUES (?)', ('user_created',))\n"
            "# commits on success, rolls back on exception — no explicit commit needed\n"
            "```\n\n"
            "On persistent connections outside `with conn:`, call `conn.commit()` "
            "after writes or changes are lost on close.\n\n"
            "**Worked example:** transfer between accounts:\n\n"
            "```python\n"
            "def transfer(conn, from_id: int, to_id: int, amount: float) -> None:\n"
            "    with conn:\n"
            "        conn.execute(\n"
            "            'UPDATE accounts SET balance = balance - ? WHERE id = ?',\n"
            "            (amount, from_id),\n"
            "        )\n"
            "        conn.execute(\n"
            "            'UPDATE accounts SET balance = balance + ? WHERE id = ?',\n"
            "            (amount, to_id),\n"
            "        )\n"
            "    # both updates commit together or neither does\n"
            "```\n\n"
            "## Inserts and last row id\n\n"
            "```python\n"
            "cur = conn.execute('INSERT INTO users (name) VALUES (?)', ('Linus',))\n"
            "new_id = cur.lastrowid\n"
            "conn.commit()\n"
            "```\n\n"
            "## Updates and deletes\n\n"
            "```python\n"
            "conn.execute('UPDATE users SET name = ? WHERE id = ?', ('Ada L.', 1))\n"
            "conn.execute('DELETE FROM users WHERE id = ?', (99,))\n"
            "conn.commit()\n"
            "```\n\n"
            "Check `cur.rowcount` to see how many rows were affected.\n\n"
            "## SQLite types (flexible typing)\n\n"
            "SQLite uses dynamic typing — a column declared `INTEGER` can store text. "
            "Enforce types in your application layer or with `CHECK` constraints:\n\n"
            "```sql\n"
            "CREATE TABLE scores (\n"
            "    value INTEGER CHECK(value >= 0 AND value <= 100)\n"
            ");\n"
            "```\n\n"
            "Storage classes: `NULL`, `INTEGER`, `REAL`, `TEXT`, `BLOB`.\n\n"
            "## Real-world scenario: simple key-value cache\n\n"
            "```python\n"
            "def init_cache(conn):\n"
            "    conn.execute('''\n"
            "        CREATE TABLE IF NOT EXISTS cache (\n"
            "            key TEXT PRIMARY KEY,\n"
            "            value TEXT NOT NULL,\n"
            "            expires_at REAL\n"
            "        )\n"
            "    ''')\n\n"
            "def cache_set(conn, key: str, value: str) -> None:\n"
            "    conn.execute(\n"
            "        'INSERT OR REPLACE INTO cache (key, value) VALUES (?, ?)',\n"
            "        (key, value),\n"
            "    )\n"
            "    conn.commit()\n\n"
            "def cache_get(conn, key: str) -> str | None:\n"
            "    row = conn.execute('SELECT value FROM cache WHERE key = ?', (key,)).fetchone()\n"
            "    return row[0] if row else None\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Forgetting `commit()` on persistent connections\n"
            "- SQL injection via string formatting\n"
            "- Assuming strict column types — SQLite is permissive\n"
            "- Sharing one connection across threads without `check_same_thread=False` "
            "(usually use one connection per thread)\n"
            "- Not closing connections — use context managers or `conn.close()`\n"
            "- Unique constraint violations — wrap inserts in try/except or use "
            "`INSERT OR IGNORE` / `INSERT OR REPLACE`\n\n"
            "## Practice\n\n"
            "Create a table, insert rows, query ordered results.\n\n"
            "## Summary\n\n"
            "sqlite3 = zero-config SQL in Python. Connect with `:memory:` for tests, "
            "use parameterized `?` queries, enable `row_factory` for readable rows, "
            "and wrap writes in `with conn:` transactions."
        ),
    },
    {
        "slug": "02_joins_queries",
        "track": "sqlite",
        "difficulty": "medium",
        "title": "JOINs and Analytical Queries",
        "tags": ["sql", "join"],
        "exercise": "content/problems/sqlite/medium/09_join_users_orders.py",
        "body": (
            "# JOINs and Analytical Queries\n\n"
            "## Overview\n\n"
            "Real data lives in multiple related tables. JOIN combines rows across tables; "
            "GROUP BY aggregates them. These patterns appear in every app beyond "
            "single-table CRUD.\n\n"
            "Real-world uses:\n\n"
            "- Order history per customer (users + orders)\n"
            "- Revenue by product category (products + line_items)\n"
            "- Active users who never placed an order (LEFT JOIN + NULL check)\n"
            "- Monthly expense totals (GROUP BY month)\n\n"
            "## Sample schema\n\n"
            "```sql\n"
            "CREATE TABLE users (\n"
            "    id INTEGER PRIMARY KEY,\n"
            "    name TEXT NOT NULL\n"
            ");\n"
            "CREATE TABLE orders (\n"
            "    id INTEGER PRIMARY KEY,\n"
            "    user_id INTEGER NOT NULL,\n"
            "    total REAL NOT NULL,\n"
            "    FOREIGN KEY (user_id) REFERENCES users(id)\n"
            ");\n"
            "```\n\n"
            "Seed data for examples:\n\n"
            "```python\n"
            "conn.executemany('INSERT INTO users (id, name) VALUES (?, ?)', [(1, 'Ada'), (2, 'Grace'), (3, 'Linus')])\n"
            "conn.executemany('INSERT INTO orders (user_id, total) VALUES (?, ?)', [(1, 50), (1, 30), (2, 80)])\n"
            "conn.commit()\n"
            "```\n\n"
            "Ada has two orders; Grace has one; Linus has none.\n\n"
            "## INNER JOIN\n\n"
            "Returns only rows with matches on **both** sides:\n\n"
            "```sql\n"
            "SELECT u.name, o.id AS order_id, o.total\n"
            "FROM users u\n"
            "INNER JOIN orders o ON o.user_id = u.id\n"
            "WHERE o.total > 100\n"
            "ORDER BY o.total DESC;\n"
            "```\n\n"
            "Users with no orders are excluded. Orders with invalid `user_id` are excluded.\n\n"
            "**From Python:**\n\n"
            "```python\n"
            "sql = '''\n"
            "    SELECT u.name, o.total\n"
            "    FROM users u\n"
            "    INNER JOIN orders o ON o.user_id = u.id\n"
            "    WHERE o.total > ?\n"
            "'''\n"
            "rows = conn.execute(sql, (100,)).fetchall()\n"
            "```\n\n"
            "## LEFT JOIN\n\n"
            "Keeps **all** rows from the left table; missing right-side matches are NULL:\n\n"
            "```sql\n"
            "SELECT u.name, COUNT(o.id) AS order_count, COALESCE(SUM(o.total), 0) AS spent\n"
            "FROM users u\n"
            "LEFT JOIN orders o ON o.user_id = u.id\n"
            "GROUP BY u.id, u.name\n"
            "ORDER BY spent DESC;\n"
            "```\n\n"
            "Users with zero orders appear with `order_count = 0` and `spent = 0`.\n\n"
            "**Worked example:** find users who never ordered:\n\n"
            "```sql\n"
            "SELECT u.name\n"
            "FROM users u\n"
            "LEFT JOIN orders o ON o.user_id = u.id\n"
            "WHERE o.id IS NULL;\n"
            "```\n\n"
            "Returns `Linus` — he has no matching orders.\n\n"
            "**Worked example:** join users to order totals (exercise pattern):\n\n"
            "```python\n"
            "def user_order_totals(conn) -> list[tuple]:\n"
            "    sql = '''\n"
            "        SELECT u.name, o.total\n"
            "        FROM users u\n"
            "        JOIN orders o ON o.user_id = u.id\n"
            "        ORDER BY u.name, o.total\n"
            "    '''\n"
            "    return conn.execute(sql).fetchall()\n"
            "# [('Ada', 50), ('Ada', 30), ('Grace', 80)]\n"
            "```\n\n"
            "## Aggregations\n\n"
            "```sql\n"
            "SELECT category, SUM(amount) AS total, COUNT(*) AS txn_count\n"
            "FROM expenses\n"
            "GROUP BY category\n"
            "HAVING total > 500\n"
            "ORDER BY total DESC;\n"
            "```\n\n"
            "- `WHERE` filters rows **before** grouping\n"
            "- `HAVING` filters groups **after** aggregation\n"
            "- Common aggregates: `COUNT`, `SUM`, `AVG`, `MIN`, `MAX`\n\n"
            "**Worked example:** top spender:\n\n"
            "```sql\n"
            "SELECT u.name, SUM(o.total) AS lifetime_total\n"
            "FROM users u\n"
            "JOIN orders o ON o.user_id = u.id\n"
            "GROUP BY u.id, u.name\n"
            "ORDER BY lifetime_total DESC\n"
            "LIMIT 1;\n"
            "```\n\n"
            "## Subqueries and EXISTS\n\n"
            "Sometimes a subquery is clearer than a JOIN:\n\n"
            "```sql\n"
            "SELECT name FROM users u\n"
            "WHERE EXISTS (\n"
            "    SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.total > 1000\n"
            ");\n"
            "```\n\n"
            "`EXISTS` stops at the first match — often efficient for \"has any\" checks.\n\n"
            "## Indexes for performance\n\n"
            "```sql\n"
            "CREATE INDEX idx_orders_user_id ON orders(user_id);\n"
            "```\n\n"
            "Speeds up JOINs and WHERE clauses on `user_id`. For small test databases "
            "it does not matter; for production SQLite files with millions of rows, "
            "indexes are essential.\n\n"
            "## JOIN types at a glance\n\n"
            "| Type        | Result                                      |\n"
            "|-------------|---------------------------------------------|\n"
            "| INNER JOIN  | only matching rows from both tables         |\n"
            "| LEFT JOIN   | all left rows + matches from right (or NULL)|\n"
            "| CROSS JOIN  | every left row paired with every right row  |\n\n"
            "Missing `ON` clause on INNER JOIN → Cartesian product (huge, usually wrong).\n\n"
            "## Python integration pattern\n\n"
            "```python\n"
            "def get_user_totals(conn, min_total: float) -> list[sqlite3.Row]:\n"
            "    conn.row_factory = sqlite3.Row\n"
            "    sql = '''\n"
            "        SELECT u.name, SUM(o.total) AS lifetime_total\n"
            "        FROM users u\n"
            "        JOIN orders o ON o.user_id = u.id\n"
            "        GROUP BY u.id, u.name\n"
            "        HAVING lifetime_total >= ?\n"
            "        ORDER BY lifetime_total DESC\n"
            "    '''\n"
            "    return conn.execute(sql, (min_total,)).fetchall()\n"
            "```\n\n"
            "## Real-world scenario: monthly sales report\n\n"
            "```python\n"
            "def monthly_sales(conn, year: int) -> list[sqlite3.Row]:\n"
            "    conn.row_factory = sqlite3.Row\n"
            "    sql = '''\n"
            "        SELECT strftime('%Y-%m', created_at) AS month,\n"
            "               COUNT(*) AS order_count,\n"
            "               SUM(total) AS revenue\n"
            "        FROM orders\n"
            "        WHERE strftime('%Y', created_at) = ?\n"
            "        GROUP BY month\n"
            "        ORDER BY month\n"
            "    '''\n"
            "    return conn.execute(sql, (str(year),)).fetchall()\n"
            "```\n\n"
            "SQLite's `strftime` extracts date parts from ISO-8601 text timestamps.\n\n"
            "## Common pitfalls\n\n"
            "- Cartesian product from missing or wrong `ON` clause\n"
            "- Selecting non-aggregated columns not in `GROUP BY` (SQLite allows loosely; "
            "other databases error — write portable SQL)\n"
            "- Duplicate rows from many-to-many joins without `DISTINCT` or proper grouping\n"
            "- Using INNER JOIN when you need users with zero orders (use LEFT JOIN)\n"
            "- Forgetting parameterized `HAVING`/`WHERE` values in Python tuples\n"
            "- Comparing NULL with `= NULL` — use `IS NULL` instead\n\n"
            "## Practice\n\n"
            "Join users to orders and list names with order totals.\n\n"
            "## Summary\n\n"
            "Master INNER vs LEFT JOIN, GROUP BY with aggregates, and WHERE vs HAVING. "
            "Combine with parameterized queries from Python — that covers most application "
            "SQL you will write."
        ),
    },
]
