"""Syntax track lesson guides."""

LESSONS = [
    {
        "slug": "01_list_comprehensions",
        "track": "syntax",
        "difficulty": "easy",
        "title": "List Comprehensions",
        "tags": ["comprehension", "list"],
        "exercise": "content/problems/syntax/easy/01_list_comprehension_evens.py",
        "body": (
            "# List Comprehensions\n\n"
            "## Overview\n\n"
            "A list comprehension builds a new list in one expression. It is the idiomatic "
            "Python replacement for simple loops that append to a list.\n\n"
            "**Why use them?** Comprehensions are faster to read and often faster to run "
            "than equivalent `for` loops because Python can optimize the whole expression. "
            "They also make the intent obvious: \"build a list of X from Y where Z.\"\n\n"
            "Think of a comprehension as a **recipe in one line**: you say what goes into "
            "the new list, where it comes from, and (optionally) which items to skip.\n\n"
            "## Syntax\n\n"
            "```python\n"
            "[expression for item in iterable if condition]\n"
            "```\n\n"
            "Read left to right: **what to collect**, **from where**, **optional filter**.\n\n"
            "Fill in this sentence for any comprehension:\n\n"
            "- \"Give me `[expression]` for each `item` in `iterable` (only if `condition`).\"\n\n"
            "Example sentence: \"Give me `x * x` for each `x` in `range(10)`\" → ten squares.\n\n"
            "## Basic examples\n\n"
            "Build a list of squares from 0 through 9:\n\n"
            "```python\n"
            "squares = [x * x for x in range(10)]\n"
            "# squares == [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]\n"
            "```\n\n"
            "The loop version does the same thing but spreads the logic across four lines:\n\n"
            "```python\n"
            "squares = []\n"
            "for x in range(10):\n"
            "    squares.append(x * x)\n"
            "```\n\n"
            "Keep only even numbers from a list:\n\n"
            "```python\n"
            "numbers = [1, 2, 3, 4, 5, 6]\n"
            "evens = [x for x in numbers if x % 2 == 0]\n"
            "# evens == [2, 4, 6]\n"
            "```\n\n"
            "**Why `x % 2 == 0`?** The `%` operator gives the remainder after division. "
            "Even numbers leave remainder 0 when divided by 2. The `if` clause filters "
            "before the expression runs — only passing items get collected.\n\n"
            "Transform and filter strings in one pass:\n\n"
            "```python\n"
            "names = ['ada', '', 'bob', 'charlie']\n"
            "labels = [name.upper() for name in names if name]\n"
            "# labels == ['ADA', 'BOB', 'CHARLIE']  (empty string skipped)\n"
            "```\n\n"
            "Convert temperatures from Fahrenheit to Celsius:\n\n"
            "```python\n"
            "fahrenheit = [32, 50, 68, 86]\n"
            "celsius = [(f - 32) * 5 / 9 for f in fahrenheit]\n"
            "# celsius == [0.0, 10.0, 20.0, 30.0]\n"
            "```\n\n"
            "**Why the `if name` check?** Empty strings are falsy in Python. Filtering them "
            "out avoids calling `.upper()` on junk data and keeps your output clean.\n\n"
            "## Worked example: from loop to comprehension\n\n"
            "**Goal:** square every even number in `[3, 8, 5, 12, 7, 4]`.\n\n"
            "**Step 1 — write the loop first** (always a safe starting point):\n\n"
            "```python\n"
            "numbers = [3, 8, 5, 12, 7, 4]\n"
            "result = []\n"
            "for x in numbers:\n"
            "    if x % 2 == 0:\n"
            "        result.append(x * x)\n"
            "# result == [64, 144, 16]\n"
            "```\n\n"
            "**Step 2 — identify the three parts:**\n\n"
            "- Expression: `x * x` (what you append)\n"
            "- Iterable: `numbers` (what you loop over)\n"
            "- Filter: `x % 2 == 0` (the `if` inside the loop)\n\n"
            "**Step 3 — compress into one line:**\n\n"
            "```python\n"
            "result = [x * x for x in numbers if x % 2 == 0]\n"
            "# same output: [64, 144, 16]\n"
            "```\n\n"
            "Nothing changed logically — only the shape. The expression is what you used "
            "to `append`. The `if` clause is the guard inside the loop.\n\n"
            "## Worked example: cleaning user input\n\n"
            "**Input:** `raw = ['  ada  ', '', 'BOB', '  ', 'charlie']`\n\n"
            "**Goal:** strip whitespace and drop blanks.\n\n"
            "```python\n"
            "clean = [name.strip().lower() for name in raw if name.strip()]\n"
            "# clean == ['ada', 'bob', 'charlie']\n"
            "```\n\n"
            "**Trace for `'  ada  '`:**\n\n"
            "1. `name.strip()` → `'ada'` (truthy, passes filter)\n"
            "2. Expression: `'ada'.lower()` → `'ada'`\n\n"
            "**Trace for `'  '`:**\n\n"
            "1. `name.strip()` → `''` (falsy, skipped)\n\n"
            "**Why chain `.strip().lower()` in the expression?** You only transform "
            "values that survived the filter, so you never waste work on blanks.\n\n"
            "## Filter + transform together\n\n"
            "```python\n"
            "numbers = [1, 2, 3, 4, 5, 6]\n"
            "even_squares = [x * x for x in numbers if x % 2 == 0]\n"
            "# even_squares == [4, 16, 36]\n"
            "```\n\n"
            "Equivalent loop:\n\n"
            "```python\n"
            "result = []\n"
            "for x in numbers:\n"
            "    if x % 2 == 0:\n"
            "        result.append(x * x)\n"
            "```\n\n"
            "**Why not two steps?** A single comprehension avoids building a temporary "
            "intermediate list and keeps the data flow in one place.\n\n"
            "Build index-value pairs from a list:\n\n"
            "```python\n"
            "colors = ['red', 'green', 'blue']\n"
            "indexed = [(i, color) for i, color in enumerate(colors)]\n"
            "# indexed == [(0, 'red'), (1, 'green'), (2, 'blue')]\n"
            "```\n\n"
            "Extract lengths of words longer than three characters:\n\n"
            "```python\n"
            "words = ['cat', 'elephant', 'dog', 'mouse']\n"
            "long_lengths = [len(w) for w in words if len(w) > 3]\n"
            "# long_lengths == [8, 5]\n"
            "```\n\n"
            "## Conditional expressions inside comprehensions\n\n"
            "The `if` **after** `for` filters items. An `if/else` **inside** the expression "
            "transforms each item (ternary):\n\n"
            "```python\n"
            "nums = [1, 2, 3, 4, 5]\n"
            "# Filter: keep only evens, then double\n"
            "doubled_evens = [x * 2 for x in nums if x % 2 == 0]\n"
            "# [4, 8]\n\n"
            "# Ternary: double evens, keep odds unchanged\n"
            "mixed = [x * 2 if x % 2 == 0 else x for x in nums]\n"
            "# [1, 4, 3, 8, 5]\n"
            "```\n\n"
            "**Why the position matters:** `[x for x in nums if x > 0]` skips items. "
            "`[x if x > 0 else 0 for x in nums]` keeps every item but replaces negatives "
            "with 0. Same keyword, different job.\n\n"
            "Label numbers as even or odd strings:\n\n"
            "```python\n"
            "labels = ['even' if n % 2 == 0 else 'odd' for n in range(4)]\n"
            "# ['even', 'odd', 'even', 'odd']\n"
            "```\n\n"
            "## Nested comprehensions\n\n"
            "Generate all coordinate pairs in a 3x3 grid:\n\n"
            "```python\n"
            "pairs = [(x, y) for x in range(3) for y in range(3)]\n"
            "# pairs == [(0,0), (0,1), (0,2), (1,0), ..., (2,2)]\n"
            "```\n\n"
            "**Why two `for` clauses?** Same as nested loops: outer `x`, inner `y`. "
            "Read them left to right, outermost first.\n\n"
            "Build a multiplication table as a list of lists:\n\n"
            "```python\n"
            "matrix = [[i * j for j in range(3)] for i in range(3)]\n"
            "# matrix == [[0, 0, 0], [0, 1, 2], [0, 2, 4]]\n"
            "```\n\n"
            "Flatten a 2D list into one row:\n\n"
            "```python\n"
            "grid = [[1, 2], [3, 4], [5, 6]]\n"
            "flat = [cell for row in grid for cell in row]\n"
            "# flat == [1, 2, 3, 4, 5, 6]\n"
            "```\n\n"
            "Collect all vowels from a list of words:\n\n"
            "```python\n"
            "words = ['hello', 'sky']\n"
            "vowels = [ch for word in words for ch in word if ch in 'aeiou']\n"
            "# vowels == ['e', 'o']\n"
            "```\n\n"
            "Keep nesting shallow — deeply nested comprehensions hurt readability. "
            "**Why?** Each extra `for` adds mental load. If you need three or more levels, "
            "a regular loop with clear variable names is often kinder to future readers.\n\n"
            "## Dict and set comprehensions\n\n"
            "Map each word to its length:\n\n"
            "```python\n"
            "words = ['cat', 'elephant', 'dog']\n"
            "lengths = {word: len(word) for word in words}\n"
            "# lengths == {'cat': 3, 'elephant': 8, 'dog': 3}\n"
            "```\n\n"
            "Collect unique positive values:\n\n"
            "```python\n"
            "items = [-1, 3, 3, 0, 7, -2, 7]\n"
            "positives = {x for x in items if x > 0}\n"
            "# positives == {3, 7}  (sets discard duplicates)\n"
            "```\n\n"
            "Invert a simple mapping (swap keys and values):\n\n"
            "```python\n"
            "scores = {'ada': 95, 'bob': 87}\n"
            "by_score = {score: name for name, score in scores.items()}\n"
            "# by_score == {95: 'ada', 87: 'bob'}\n"
            "```\n\n"
            "Build a set of file extensions:\n\n"
            "```python\n"
            "files = ['report.pdf', 'notes.txt', 'data.pdf']\n"
            "extensions = {f.split('.')[-1] for f in files}\n"
            "# extensions == {'pdf', 'txt'}\n"
            "```\n\n"
            "**Why dict/set comprehensions?** Same readability win as list comprehensions, "
            "but you choose the collection type with the outer braces: `{}` for dict "
            "(with `key: value`) or `{expr}` for set.\n\n"
            "## Generator expressions (memory-friendly cousin)\n\n"
            "Parentheses instead of brackets create a generator — lazy, one item at a time:\n\n"
            "```python\n"
            "# Good: sum without storing millions of values\n"
            "total = sum(x * x for x in range(1_000_000))\n\n"
            "# Wasteful: builds a list of 1 million ints first\n"
            "total = sum([x * x for x in range(1_000_000)])\n"
            "```\n\n"
            "Check if any name is too long:\n\n"
            "```python\n"
            "names = ['ada', 'alexandria', 'bob']\n"
            "has_long = any(len(n) > 10 for n in names)\n"
            "# has_long == False\n"
            "```\n\n"
            "**Why generators?** They avoid allocating a full list when you only need to "
            "iterate once (sum, any, all, max, or a single for-loop).\n\n"
            "## When NOT to use them\n\n"
            "- Side effects (printing, file I/O, database calls) — comprehensions should "
            "be pure transforms\n"
            "- Long multi-line logic — use a regular loop so you can add comments and "
            "breakpoints\n"
            "- When a generator suffices: `(x for x in big)` saves memory\n"
            "- When readability suffers — a verbose loop beats a cryptic one-liner\n\n"
            "```python\n"
            "# Bad: side effect inside comprehension\n"
            "[print(x) for x in items]  # works but unclear; use a for-loop\n"
            "```\n\n"
            "## Common pitfalls\n\n"
            "- Shadowing loop variables — in Python 3 the loop variable leaks to outer "
            "scope after the comprehension; avoid reusing names like `i` or `x` nearby\n"
            "- Building huge lists when `sum(...)`, `any(...)`, or a generator would work\n"
            "- Putting the `if` in the wrong position (filter vs ternary — see above)\n"
            "- Nested comprehensions that are hard to read — switch to nested loops\n\n"
            "```python\n"
            "# Filter before transform (correct for evens only)\n"
            "[x * 2 for x in nums if x % 2 == 0]\n\n"
            "# Conditional expression (different meaning — every item kept)\n"
            "[x * 2 if x % 2 == 0 else x for x in nums]\n"
            "```\n\n"
            "## Practice\n\n"
            "Filter even numbers and square them in one comprehension.\n\n"
            "Given `numbers = [1, 2, 3, 4, 5, 6]`, the answer is `[4, 16, 36]`.\n\n"
            "```python\n"
            "numbers = [1, 2, 3, 4, 5, 6]\n"
            "answer = [x * x for x in numbers if x % 2 == 0]\n"
            "# answer == [4, 16, 36]\n"
            "```\n\n"
            "## Summary\n\n"
            "Comprehensions = concise map+filter. Prefer them for pure transforms; prefer "
            "loops for effects and complex control flow. When learning, write the loop "
            "first, then refactor — that builds intuition for what the comprehension is "
            "actually doing."
        ),
    },
    {
        "slug": "02_unpacking",
        "track": "syntax",
        "difficulty": "easy",
        "title": "Iterable Unpacking",
        "tags": ["unpacking"],
        "exercise": "content/problems/syntax/easy/05_unpacking_head_tail.py",
        "body": (
            "# Iterable Unpacking\n\n"
            "## Overview\n\n"
            "Python can assign multiple names from any iterable in one statement. "
            "The `*` operator collects \"the rest\" into a list. This shows up in "
            "function calls, loops, and data splitting constantly.\n\n"
            "**Why learn unpacking?** It replaces index gymnastics (`items[0]`, "
            "`items[1:]`) with readable names (`first`, `rest`). Code that splits "
            "boundaries — first/last, head/tail, config merges — becomes shorter "
            "and less error-prone.\n\n"
            "Unpacking is one of Python's most practical everyday features. Once you "
            "see `head, *tail = data`, slicing with `[0]` and `[1:]` starts to feel clumsy.\n\n"
            "## Basic unpacking\n\n"
            "Assign three values from a list:\n\n"
            "```python\n"
            "first, second, third = [1, 2, 3]\n"
            "# first == 1, second == 2, third == 3\n"
            "```\n\n"
            "Unpack a tuple returned from a function:\n\n"
            "```python\n"
            "def min_max(nums):\n"
            "    return min(nums), max(nums)\n\n"
            "lo, hi = min_max([3, 1, 4, 1, 5])\n"
            "# lo == 1, hi == 5\n"
            "```\n\n"
            "**Why tuples and unpacking go together?** Functions often return multiple "
            "values as a tuple. Unpacking gives each value a meaningful name in one line.\n\n"
            "Swap two variables without a temporary:\n\n"
            "```python\n"
            "a, b = 10, 20\n"
            "a, b = b, a\n"
            "# a == 20, b == 10\n"
            "```\n\n"
            "**Why does swap work?** Python evaluates the right-hand side into a tuple "
            "first `(b, a)`, then unpacks it into `(a, b)`. No temp variable needed.\n\n"
            "Unpack any iterable, not just lists:\n\n"
            "```python\n"
            "x, y, z = range(3)\n"
            "# x == 0, y == 1, z == 2\n"
            "```\n\n"
            "Ignore values you do not need with `_`:\n\n"
            "```python\n"
            "name, _, city = ('Ada', 36, 'London')\n"
            "# name == 'Ada', city == 'London' (age discarded)\n"
            "```\n\n"
            "**Why `_`?** It signals \"I must accept this position but I do not care about "
            "the value.\" Readers know the middle slot is intentionally unused.\n\n"
            "## Star unpacking\n\n"
            "Grab the first element and collect everything else:\n\n"
            "```python\n"
            "head, *tail = [1, 2, 3, 4]\n"
            "# head == 1, tail == [2, 3, 4]\n"
            "```\n\n"
            "Split into first, middle, and last:\n\n"
            "```python\n"
            "seq = [10, 20, 30, 40, 50]\n"
            "first, *middle, last = seq\n"
            "# first == 10, middle == [20, 30, 40], last == 50\n"
            "```\n\n"
            "Collect everything except the final element:\n\n"
            "```python\n"
            "items = ['a', 'b', 'c']\n"
            "*start, end = items\n"
            "# start == ['a', 'b'], end == 'c'\n"
            "```\n\n"
            "Exactly one `*` is allowed on the left side of assignment.\n\n"
            "**Why is `*rest` always a list?** Even when it captures a single element, "
            "Python uses a list so you can always iterate or slice `rest` predictably.\n\n"
            "Take the first two and bundle the rest:\n\n"
            "```python\n"
            "first, second, *others = [1, 2, 3, 4, 5]\n"
            "# first == 1, second == 2, others == [3, 4, 5]\n"
            "```\n\n"
            "## Worked example: head and tail\n\n"
            "**Input:** `data = [42, 7, 13, 99]`\n\n"
            "**Step 1:** unpack with star\n\n"
            "```python\n"
            "head, *tail = data\n"
            "```\n\n"
            "**Output:** `head == 42`, `tail == [7, 13, 99]`\n\n"
            "**Use case:** recursive algorithms often process the first element, then "
            "recurse on the tail:\n\n"
            "```python\n"
            "def sum_list(nums):\n"
            "    if not nums:\n"
            "        return 0\n"
            "    head, *tail = nums\n"
            "    return head + sum_list(tail)\n\n"
            "sum_list([1, 2, 3])  # 6\n"
            "```\n\n"
            "**Edge case — single element:**\n\n"
            "```python\n"
            "head, *tail = [99]\n"
            "# head == 99, tail == []  (empty list, not an error)\n"
            "```\n\n"
            "**Edge case — empty list:** raises `ValueError` because there is no value "
            "for `head`.\n\n"
            "## Worked example: splitting a CSV row\n\n"
            "**Input:** `row = ['2024-01-15', 'ada', 'admin', 'eng']`\n\n"
            "**Goal:** date, username, and everything else as roles.\n\n"
            "```python\n"
            "date, user, *roles = row\n"
            "# date == '2024-01-15'\n"
            "# user == 'ada'\n"
            "# roles == ['admin', 'eng']\n"
            "```\n\n"
            "**Why better than indexing?** If more role columns appear later, `roles` "
            "grows automatically. You do not need to change `row[3:]` magic numbers.\n\n"
            "## In function calls\n\n"
            "Splat a list into positional arguments:\n\n"
            "```python\n"
            "def greet(first, last):\n"
            "    return f'Hello, {first} {last}'\n\n"
            "parts = ['Ada', 'Lovelace']\n"
            "greet(*parts)  # same as greet('Ada', 'Lovelace')\n"
            "# returns 'Hello, Ada Lovelace'\n"
            "```\n\n"
            "Pass extra values from one list into another call:\n\n"
            "```python\n"
            "def add(a, b, c):\n"
            "    return a + b + c\n\n"
            "values = [1, 2, 3]\n"
            "add(*values)  # 6\n"
            "```\n\n"
            "Collect extra positional and keyword arguments:\n\n"
            "```python\n"
            "def log(msg, *args, **kwargs):\n"
            "    print(msg, args, kwargs)\n\n"
            "log('done', 1, 2, key='value')\n"
            "# prints: done (1, 2) {'key': 'value'}\n"
            "```\n\n"
            "Forward arguments to another function:\n\n"
            "```python\n"
            "def wrapper(*args, **kwargs):\n"
            "    return real_function(*args, **kwargs)\n"
            "```\n\n"
            "**Why `*args` and `**kwargs`?** They let one function accept any signature "
            "and pass it through — essential for decorators and wrappers.\n\n"
            "Unpack a dict into keyword arguments:\n\n"
            "```python\n"
            "def connect(host, port, timeout=30):\n"
            "    return f'{host}:{port} timeout={timeout}'\n\n"
            "opts = {'host': 'localhost', 'port': 8080, 'timeout': 5}\n"
            "connect(**opts)\n"
            "# 'localhost:8080 timeout=5'\n"
            "```\n\n"
            "## In loops\n\n"
            "Unpack each row as a key plus remaining values:\n\n"
            "```python\n"
            "records = [('user', 'ada', 'admin'), ('user', 'bob', 'guest')]\n"
            "for kind, *fields in records:\n"
            "    print(kind, fields)\n"
            "# user ['ada', 'admin']\n"
            "# user ['bob', 'guest']\n"
            "```\n\n"
            "Iterate with index and value using `enumerate`:\n\n"
            "```python\n"
            "colors = ['red', 'green', 'blue']\n"
            "for i, color in enumerate(colors):\n"
            "    print(i, color)\n"
            "# 0 red\n"
            "# 1 green\n"
            "# 2 blue\n"
            "```\n\n"
            "Zip two lists into pairs:\n\n"
            "```python\n"
            "names = ['ada', 'bob']\n"
            "scores = [95, 87]\n"
            "for name, score in zip(names, scores):\n"
            "    print(name, score)\n"
            "# ada 95\n"
            "# bob 87\n"
            "```\n\n"
            "**Why unpack in the loop header?** It keeps the loop body focused on logic "
            "instead of indexing `row[0]`, `row[1]`.\n\n"
            "## Extended iterable unpacking (Python 3.5+)\n\n"
            "Merge lists without mutating originals:\n\n"
            "```python\n"
            "a = [1, 2]\n"
            "b = [3, 4]\n"
            "merged = [0, *a, *b, 5]\n"
            "# merged == [0, 1, 2, 3, 4, 5]\n"
            "```\n\n"
            "Prepend and append in one expression:\n\n"
            "```python\n"
            "defaults = ['http', 'localhost']\n"
            "path = [*defaults, 'api', 'v1']\n"
            "# ['http', 'localhost', 'api', 'v1']\n"
            "```\n\n"
            "Merge dictionaries (later keys win):\n\n"
            "```python\n"
            "defaults = {'host': 'localhost', 'port': 8080, 'debug': False}\n"
            "overrides = {'port': 3000, 'debug': True}\n"
            "combined = {**defaults, **overrides}\n"
            "# combined == {'host': 'localhost', 'port': 3000, 'debug': True}\n"
            "```\n\n"
            "Add one extra key without copying the whole dict manually:\n\n"
            "```python\n"
            "base = {'a': 1, 'b': 2}\n"
            "extended = {**base, 'c': 3}\n"
            "# {'a': 1, 'b': 2, 'c': 3}\n"
            "```\n\n"
            "**Why `{**a, **b}`?** It creates a new dict without modifying either input — "
            "safer than manual `.update()` when you need to keep defaults intact.\n\n"
            "## Common pitfalls\n\n"
            "- Too many or too few values without `*` → `ValueError`\n"
            "- Using `*` on both sides of assignment (invalid syntax)\n"
            "- Forgetting that `*rest` is always a list, even for one element\n"
            "- Confusing `*args` (tuple in function defs) with `*rest` (list in assignments)\n"
            "- Unpacking `None` — always ensure the iterable exists before unpacking\n\n"
            "```python\n"
            "# ValueError: not enough values to unpack\n"
            "a, b = [1]\n\n"
            "# Fix: use star or provide defaults elsewhere\n"
            "a, *rest = [1]  # a == 1, rest == []\n"
            "```\n\n"
            "## Practice\n\n"
            "Split a list into head (first element) and tail (everything else).\n\n"
            "```python\n"
            "data = [10, 20, 30]\n"
            "head, *tail = data\n"
            "# head == 10, tail == [20, 30]\n"
            "```\n\n"
            "Bonus: split into first, last, and middle:\n\n"
            "```python\n"
            "data = [10, 20, 30, 40]\n"
            "first, *middle, last = data\n"
            "# first == 10, middle == [20, 30], last == 40\n"
            "```\n\n"
            "## Summary\n\n"
            "Unpacking makes boundary code readable: first/last, head/tail, merge configs, "
            "and splat arguments. Reach for `*` whenever you find yourself slicing with "
            "`[0]` and `[1:]` repeatedly."
        ),
    },
    {
        "slug": "03_decorators",
        "track": "syntax",
        "difficulty": "medium",
        "title": "Decorators",
        "tags": ["decorator"],
        "exercise": "content/problems/syntax/medium/09_decorator_shout.py",
        "body": (
            "# Decorators\n\n"
            "## Overview\n\n"
            "A decorator wraps a function (or class) to add behavior without editing its "
            "body. Syntax `@decorator` above `def` is sugar for "
            "`func = decorator(func)` at **definition time**.\n\n"
            "**Why use decorators?** They separate cross-cutting concerns — logging, "
            "timing, validation, caching — from business logic. The wrapped function "
            "stays focused on what it does; the decorator handles the boilerplate "
            "around every call.\n\n"
            "Real projects use decorators constantly: web frameworks use them for routes "
            "and auth; `functools.lru_cache` speeds up expensive functions; `@property` "
            "turns methods into attributes. Learning the pattern unlocks a lot of Python code.\n\n"
            "## What happens at definition time\n\n"
            "```python\n"
            "@shout\n"
            "def greet(name):\n"
            "    return f'hello {name}'\n"
            "```\n\n"
            "Python executes this in order:\n\n"
            "1. Define the function object `greet`\n"
            "2. Pass it to `shout(greet)`\n"
            "3. Bind the return value back to the name `greet`\n\n"
            "After decoration, calling `greet('ada')` actually calls the inner `wrapper`.\n\n"
            "**Critical insight:** Decoration runs **once** when Python reads the `def`, "
            "not each time you call the function. The wrapper is installed permanently "
            "(until you reassign `greet`).\n\n"
            "## Minimal decorator\n\n"
            "```python\n"
            "import functools\n\n"
            "def shout(func):\n"
            "    @functools.wraps(func)\n"
            "    def wrapper(*args, **kwargs):\n"
            "        result = func(*args, **kwargs)\n"
            "        return result.upper() if isinstance(result, str) else result\n"
            "    return wrapper\n\n"
            "@shout\n"
            "def greet(name):\n"
            "    return f'hello {name}'\n"
            "```\n\n"
            "**Concrete output:**\n\n"
            "```python\n"
            "greet('ada')   # returns 'HELLO ADA'\n"
            "greet(42)      # returns 42 (not a string, left unchanged)\n"
            "```\n\n"
            "**Why `*args, **kwargs`?** The wrapper must accept any arguments the original "
            "function accepts, or decoration breaks for functions with different signatures.\n\n"
            "**Why return `wrapper` from `shout`?** The decorator is a function that takes "
            "`func` and returns a **new callable** that replaces it. Forgetting `return wrapper` "
            "means `greet` becomes `None` and every call crashes.\n\n"
            "## Why functools.wraps matters\n\n"
            "Without `@functools.wraps(func)`:\n\n"
            "```python\n"
            "greet.__name__   # 'wrapper'  (misleading in stack traces)\n"
            "greet.__doc__    # None       (docstring lost)\n"
            "```\n\n"
            "With `@functools.wraps(func)`:\n\n"
            "```python\n"
            "greet.__name__   # 'greet'\n"
            "greet.__doc__    # original docstring preserved\n"
            "```\n\n"
            "**Why does this matter?** Debuggers, loggers, and `help(greet)` rely on "
            "`__name__` and `__doc__`. Losing them makes production issues harder to trace.\n\n"
            "## Worked example: timing decorator\n\n"
            "```python\n"
            "import functools\n"
            "import time\n\n"
            "def timer(func):\n"
            "    @functools.wraps(func)\n"
            "    def wrapper(*args, **kwargs):\n"
            "        start = time.perf_counter()\n"
            "        result = func(*args, **kwargs)\n"
            "        elapsed = time.perf_counter() - start\n"
            "        print(f'{func.__name__} took {elapsed:.4f}s')\n"
            "        return result\n"
            "    return wrapper\n\n"
            "@timer\n"
            "def slow_add(a, b):\n"
            "    time.sleep(0.1)\n"
            "    return a + b\n"
            "```\n\n"
            "**Output when called:**\n\n"
            "```python\n"
            "slow_add(2, 3)  # prints 'slow_add took 0.1001s', returns 5\n"
            "```\n\n"
            "The original function's return value passes through unchanged — the decorator "
            "only adds side effects around the call.\n\n"
            "**Why `time.perf_counter()`?** It is monotonic and high resolution — better "
            "for measuring short intervals than `time.time()`.\n\n"
            "## Worked example: logging arguments\n\n"
            "```python\n"
            "def log_calls(func):\n"
            "    @functools.wraps(func)\n"
            "    def wrapper(*args, **kwargs):\n"
            "        print(f'calling {func.__name__} with {args=} {kwargs=}')\n"
            "        return func(*args, **kwargs)\n"
            "    return wrapper\n\n"
            "@log_calls\n"
            "def add(a, b):\n"
            "    return a + b\n\n"
            "add(2, b=3)\n"
            "# calling add with args=(2,) kwargs={'b': 3}\n"
            "# returns 5\n"
            "```\n\n"
            "**Why log before `func(...)`?** You capture inputs even if the inner function "
            "raises an exception — useful when debugging failures.\n\n"
            "## Decorators with arguments\n\n"
            "When the decorator itself needs configuration, add a factory layer:\n\n"
            "```python\n"
            "def repeat(n):\n"
            "    def decorator(func):\n"
            "        @functools.wraps(func)\n"
            "        def wrapper(*args, **kwargs):\n"
            "            result = None\n"
            "            for _ in range(n):\n"
            "                result = func(*args, **kwargs)\n"
            "            return result\n"
            "        return wrapper\n"
            "    return decorator\n\n"
            "@repeat(3)\n"
            "def ping():\n"
            "    print('ping')\n"
            "```\n\n"
            "**What `@repeat(3)` expands to:**\n\n"
            "1. `repeat(3)` returns the `decorator` function\n"
            "2. `decorator(ping)` returns `wrapper`\n"
            "3. `ping` now points to `wrapper`\n\n"
            "Calling `ping()` prints `'ping'` three times.\n\n"
            "Three levels: **factory** → **decorator** → **wrapper**.\n\n"
            "**Why three levels?** `@repeat(3)` must call `repeat(3)` first to get the "
            "actual decorator. Without the factory, you could not pass `n` at decoration time.\n\n"
            "Retry on failure (simplified):\n\n"
            "```python\n"
            "def retry(times):\n"
            "    def decorator(func):\n"
            "        @functools.wraps(func)\n"
            "        def wrapper(*args, **kwargs):\n"
            "            last_exc = None\n"
            "            for _ in range(times):\n"
            "                try:\n"
            "                    return func(*args, **kwargs)\n"
            "                except Exception as exc:\n"
            "                    last_exc = exc\n"
            "            raise last_exc\n"
            "        return wrapper\n"
            "    return decorator\n"
            "```\n\n"
            "## Common built-ins\n\n"
            "- `@property` — expose a method as a read-only attribute\n"
            "- `@staticmethod` / `@classmethod` — alternate binding for class methods\n"
            "- `@lru_cache` — memoization (cache function results by arguments)\n"
            "- `@dataclass` — auto-generate `__init__`, `__repr__`, etc.\n\n"
            "```python\n"
            "from functools import lru_cache\n\n"
            "@lru_cache(maxsize=None)\n"
            "def fib(n):\n"
            "    if n < 2:\n"
            "        return n\n"
            "    return fib(n - 1) + fib(n - 2)\n\n"
            "fib(100)  # fast — intermediate results cached\n"
            "```\n\n"
            "`@property` example — computed attribute:\n\n"
            "```python\n"
            "class Circle:\n"
            "    def __init__(self, radius):\n"
            "        self.radius = radius\n\n"
            "    @property\n"
            "    def area(self):\n"
            "        return 3.14159 * self.radius ** 2\n\n"
            "c = Circle(2)\n"
            "c.area  # 12.56636 — called like an attribute, not c.area()\n"
            "```\n\n"
            "**Why `@property`?** It keeps a clean public API (`obj.area`) while allowing "
            "validation or computation behind the scenes.\n\n"
            "## Stacking decorators\n\n"
            "```python\n"
            "@a\n"
            "@b\n"
            "def f():\n"
            "    pass\n"
            "```\n\n"
            "Equivalent to `f = a(b(f))` — **bottom decorator applied first**.\n\n"
            "**Why order matters?** If `@timer` is outside `@cache`, you time cache hits too. "
            "If `@cache` is outside `@timer`, you only time the first uncached call.\n\n"
            "Concrete stacking trace:\n\n"
            "```python\n"
            "@timer      # applied second: timer(wrapper_from_cache)\n"
            "@lru_cache  # applied first: cache(f)\n"
            "def work(n):\n"
            "    return n * n\n"
            "```\n\n"
            "First call: cache miss → `work` runs → result cached → timer prints.\n"
            "Second call with same `n`: cache hit → `work` body skipped → timer still runs.\n\n"
            "## Common pitfalls\n\n"
            "- Forgetting to `return wrapper` from the decorator (silently returns `None`)\n"
            "- Expecting decoration at call time — it runs once at import/definition\n"
            "- Stacking order: `@a @b def f` → `f = a(b(f))` (bottom decorator applied first)\n"
            "- Forgetting `@functools.wraps` and losing metadata\n"
            "- Decorating instance methods without understanding `self` is just the first arg\n\n"
            "## Practice\n\n"
            "Write a decorator that uppercases string return values.\n\n"
            "```python\n"
            "@shout\n"
            "def greet(name):\n"
            "    return f'hello {name}'\n\n"
            "greet('world')  # 'HELLO WORLD'\n"
            "```\n\n"
            "## Summary\n\n"
            "Decorators = higher-order functions for cross-cutting concerns: logging, timing, "
            "auth, caching, validation. They run at definition time, wrap the original "
            "callable, and should always use `@functools.wraps` to preserve introspection."
        ),
    },
    {
        "slug": "04_dicts_and_sets",
        "track": "syntax",
        "difficulty": "easy",
        "title": "Dicts, Sets, and defaultdict",
        "tags": ["dict", "set", "collections"],
        "exercise": "content/problems/syntax/easy/07_defaultdict_groupby.py",
        "body": (
            "# Dicts, Sets, and defaultdict\n\n"
            "## Overview\n\n"
            "Dictionaries map keys to values in O(1) average time. Sets store unique "
            "elements for O(1) membership tests. Together they power counting, grouping, and "
            "deduplication — three of the most common patterns in Python programs.\n\n"
            "**Why not just use lists?** Searching a list is O(n); dict and set lookups "
            "are O(1) on average. For \"have I seen this before?\" or \"how many times "
            "did this appear?\", dicts and sets are the right tool.\n\n"
            "Interview problems and real apps alike lean on these structures. Mastering "
            "them means fewer nested loops and clearer code.\n\n"
            "## Dict essentials\n\n"
            "Count word frequencies with `.get()`:\n\n"
            "```python\n"
            "words = ['cat', 'dog', 'cat', 'bird', 'dog', 'cat']\n"
            "counts = {}\n"
            "for word in words:\n"
            "    counts[word] = counts.get(word, 0) + 1\n"
            "# counts == {'cat': 3, 'dog': 2, 'bird': 1}\n"
            "```\n\n"
            "**Why `.get(word, 0)`?** Accessing a missing key with `counts[word]` raises "
            "`KeyError`. `.get` returns 0 for new words so you can increment safely.\n\n"
            "Iterate key-value pairs:\n\n"
            "```python\n"
            "for word, count in counts.items():\n"
            "    print(f'{word}: {count}')\n"
            "# cat: 3\n"
            "# dog: 2\n"
            "# bird: 1\n"
            "```\n\n"
            "Safe lookup with a default:\n\n"
            "```python\n"
            "scores = {'ada': 95, 'bob': 87}\n"
            "scores.get('charlie', 0)  # 0 (key missing, no error)\n"
            "```\n\n"
            "Build a dict from two parallel lists:\n\n"
            "```python\n"
            "keys = ['a', 'b', 'c']\n"
            "vals = [1, 2, 3]\n"
            "mapping = dict(zip(keys, vals))\n"
            "# {'a': 1, 'b': 2, 'c': 3}\n"
            "```\n\n"
            "Check membership before expensive work:\n\n"
            "```python\n"
            "allowed = {'admin', 'editor', 'viewer'}\n"
            "role = 'guest'\n"
            "if role in allowed:\n"
            "    grant_access()\n"
            "```\n\n"
            "## Worked example: two-sum lookup\n\n"
            "**Problem:** find two indices whose values sum to `target`.\n\n"
            "```python\n"
            "nums = [2, 7, 11, 15]\n"
            "target = 9\n"
            "seen = {}\n"
            "for i, num in enumerate(nums):\n"
            "    need = target - num\n"
            "    if need in seen:\n"
            "        print(seen[need], i)  # 0 1\n"
            "        break\n"
            "    seen[num] = i\n"
            "```\n\n"
            "**Walkthrough step by step:**\n\n"
            "| i | num | need | seen before | action        |\n"
            "|---|-----|------|-------------|---------------|\n"
            "| 0 | 2   | 7    | {}          | store 2→0     |\n"
            "| 1 | 7   | 2    | {2:0}       | 2 found! → 0,1|\n\n"
            "**Output:** indices `0` and `1` because `2 + 7 = 9`.\n\n"
            "**Why a dict?** You need instant lookup of \"have we seen the complement?\" "
            "while scanning left to right. A list would require scanning `seen` each time.\n\n"
            "## Sets for uniqueness\n\n"
            "Track visited nodes:\n\n"
            "```python\n"
            "visited = set()\n"
            "for node in graph_neighbors:\n"
            "    if node not in visited:\n"
            "        visited.add(node)\n"
            "        process(node)\n"
            "```\n\n"
            "**Why `if node not in visited`?** Set membership is O(1). A list would be O(n) "
            "per check and grow expensive on large graphs.\n\n"
            "Deduplicate while preserving order:\n\n"
            "```python\n"
            "items = ['b', 'a', 'b', 'c', 'a']\n"
            "unique = list(dict.fromkeys(items))\n"
            "# unique == ['b', 'a', 'c']\n"
            "```\n\n"
            "Set operations for overlap:\n\n"
            "```python\n"
            "a = {1, 2, 3}\n"
            "b = {2, 3, 4}\n"
            "a & b   # {2, 3}  intersection — in both\n"
            "a | b   # {1, 2, 3, 4}  union — in either\n"
            "a - b   # {1}  difference — in a but not b\n"
            "```\n\n"
            "Find users in both groups:\n\n"
            "```python\n"
            "group_a = {'ada', 'bob', 'cleo'}\n"
            "group_b = {'bob', 'dana', 'ada'}\n"
            "both = group_a & group_b\n"
            "# {'ada', 'bob'}\n"
            "```\n\n"
            "**Why `dict.fromkeys` instead of `set`?** Sets discard order. Dict keys "
            "preserve insertion order (Python 3.7+), giving you uniqueness and order.\n\n"
            "## defaultdict — group without boilerplate\n\n"
            "```python\n"
            "from collections import defaultdict\n\n"
            "employees = [('Ada', 'eng'), ('Bob', 'sales'), ('Cleo', 'eng')]\n"
            "groups = defaultdict(list)\n"
            "for name, dept in employees:\n"
            "    groups[dept].append(name)\n"
            "# dict(groups) == {'eng': ['Ada', 'Cleo'], 'sales': ['Bob']}\n"
            "```\n\n"
            "**Why defaultdict?** Without it you write:\n\n"
            "```python\n"
            "groups = {}\n"
            "for name, dept in employees:\n"
            "    if dept not in groups:\n"
            "        groups[dept] = []\n"
            "    groups[dept].append(name)\n"
            "```\n\n"
            "Every grouping problem repeats that `if` check. `defaultdict(list)` creates "
            "an empty list on first access automatically.\n\n"
            "Group words by first letter:\n\n"
            "```python\n"
            "words = ['apple', 'banana', 'apricot', 'blueberry']\n"
            "by_letter = defaultdict(list)\n"
            "for word in words:\n"
            "    by_letter[word[0]].append(word)\n"
            "# {'a': ['apple', 'apricot'], 'b': ['banana', 'blueberry']}\n"
            "```\n\n"
            "Count with `defaultdict(int)` — zero default:\n\n"
            "```python\n"
            "votes = defaultdict(int)\n"
            "for choice in ['a', 'b', 'a', 'a', 'c']:\n"
            "    votes[choice] += 1\n"
            "# dict(votes) == {'a': 3, 'b': 1, 'c': 1}\n"
            "```\n\n"
            "**Why `int` as factory?** Calling `int()` returns `0`, so missing keys start "
            "at zero and `+= 1` works without `.get`.\n\n"
            "## Counter for frequencies\n\n"
            "```python\n"
            "from collections import Counter\n\n"
            "words = ['cat', 'dog', 'cat', 'bird', 'dog', 'cat']\n"
            "counts = Counter(words)\n"
            "# Counter({'cat': 3, 'dog': 2, 'bird': 1})\n\n"
            "top = counts.most_common(2)\n"
            "# [('cat', 3), ('dog', 2)]\n"
            "```\n\n"
            "Compare two strings for anagrams:\n\n"
            "```python\n"
            "from collections import Counter\n\n"
            "def is_anagram(a, b):\n"
            "    return Counter(a) == Counter(b)\n\n"
            "is_anagram('listen', 'silent')  # True\n"
            "is_anagram('hello', 'world')    # False\n"
            "```\n\n"
            "**Why Counter over manual counting?** It is shorter, supports arithmetic "
            "(`counts1 + counts2`), subtraction, and `most_common(k)` is built in.\n\n"
            "## Worked example: first duplicate\n\n"
            "**Input:** `nums = [1, 3, 4, 3, 2, 1]` — find the first value that appears twice.\n\n"
            "```python\n"
            "def first_duplicate(nums):\n"
            "    seen = set()\n"
            "    for n in nums:\n"
            "        if n in seen:\n"
            "            return n\n"
            "        seen.add(n)\n"
            "    return None\n\n"
            "first_duplicate([1, 3, 4, 3, 2, 1])  # 3\n"
            "```\n\n"
            "**Trace:**\n\n"
            "- See 1 → add to seen `{1}`\n"
            "- See 3 → add `{1, 3}`\n"
            "- See 4 → add `{1, 3, 4}`\n"
            "- See 3 again → already in seen → return `3`\n\n"
            "## Common patterns\n\n"
            "- **Two-sum lookup**: store complements in a dict (see worked example above)\n"
            "- **Group by key**: `defaultdict(list)` or `itertools.groupby` (requires sorted input)\n"
            "- **Visited set** in graph/BFS traversal — O(1) \"already seen?\" checks\n"
            "- **Frequency map** for anagrams: compare `Counter(s1)` vs `Counter(s2)`\n\n"
            "## Common pitfalls\n\n"
            "- Using mutable objects (lists) as dict keys — keys must be hashable\n"
            "- Modifying a dict while iterating — iterate over `list(d)` copy instead\n"
            "- `set()` loses order; use `dict.fromkeys` trick if order matters\n"
            "- Assuming `defaultdict` creates nested dicts — use `defaultdict(lambda: defaultdict(int))` "
            "or nested factories for 2D grouping\n"
            "- Using `is` to compare small integers/strings when you mean value equality in dict keys\n\n"
            "```python\n"
            "# Dangerous while iterating\n"
            "for k in d:\n"
            "    if bad(k):\n"
            "        del d[k]  # RuntimeError\n\n"
            "# Safe: iterate a snapshot\n"
            "for k in list(d):\n"
            "    if bad(k):\n"
            "        del d[k]\n"
            "```\n\n"
            "## Practice\n\n"
            "Group words by their first letter using defaultdict.\n\n"
            "```python\n"
            "from collections import defaultdict\n\n"
            "words = ['apple', 'apricot', 'banana']\n"
            "by_letter = defaultdict(list)\n"
            "for w in words:\n"
            "    by_letter[w[0]].append(w)\n"
            "# {'a': ['apple', 'apricot'], 'b': ['banana']}\n"
            "```\n\n"
            "## Summary\n\n"
            "| Need            | Tool          |\n"
            "|-----------------|---------------|\n"
            "| Count           | dict / Counter|\n"
            "| Unique items    | set           |\n"
            "| Group lists     | defaultdict   |\n"
            "| Fast lookup     | dict / set    |"
        ),
    },
    {
        "slug": "05_error_handling",
        "track": "syntax",
        "difficulty": "easy",
        "title": "Exceptions and Context Managers",
        "tags": ["exceptions", "with"],
        "exercise": "content/problems/syntax/medium/22_context_manager_timer.py",
        "body": (
            "# Exceptions and Context Managers\n\n"
            "## Overview\n\n"
            "Python uses exceptions for error flow. `try/except` handles expected failures; "
            "`with` guarantees cleanup via context managers (files, locks, timers).\n\n"
            "**Why exceptions instead of error codes?** Error codes force every caller to "
            "check return values. Exceptions separate happy-path logic from error handling "
            "and automatically propagate up the call stack until something catches them.\n\n"
            "Well-written Python rarely checks \"did this fail?\" after every line. Instead, "
            "you handle predictable failures at boundaries (user input, files, network) and "
            "let unexpected bugs surface with a clear traceback.\n\n"
            "## try / except / else / finally\n\n"
            "Parse JSON safely:\n\n"
            "```python\n"
            "import json\n\n"
            "text = '{\"name\": \"ada\"}'\n"
            "try:\n"
            "    data = json.loads(text)\n"
            "except json.JSONDecodeError as exc:\n"
            "    print(f'invalid json: {exc}')\n"
            "    data = None\n"
            "else:\n"
            "    print(f'parsed: {data}')   # runs only if no exception\n"
            "finally:\n"
            "    print('done parsing')      # always runs\n"
            "```\n\n"
            "**Output with valid JSON:**\n\n"
            "```\n"
            "parsed: {'name': 'ada'}\n"
            "done parsing\n"
            "```\n\n"
            "**Output with invalid JSON `'not json'`:**\n\n"
            "```\n"
            "invalid json: Expecting value: line 1 column 1 (char 0)\n"
            "done parsing\n"
            "```\n\n"
            "**Why four blocks?** Each has a distinct role:\n\n"
            "- `try` — code that might fail\n"
            "- `except` — handle a specific failure\n"
            "- `else` — runs only on success (keeps `try` block small)\n"
            "- `finally` — cleanup that must run regardless\n\n"
            "Convert user input to int:\n\n"
            "```python\n"
            "raw = '42'\n"
            "try:\n"
            "    value = int(raw)\n"
            "except ValueError:\n"
            "    print('not a number')\n"
            "    value = None\n"
            "```\n\n"
            "**Input `'42'` →** `value == 42`. **Input `'abc'` →** prints message, `value is None`.\n\n"
            "## Raising exceptions\n\n"
            "Validate input and fail fast:\n\n"
            "```python\n"
            "def set_age(age):\n"
            "    if age < 0:\n"
            "        raise ValueError('age must be non-negative')\n"
            "    return age\n"
            "```\n\n"
            "```python\n"
            "set_age(25)   # 25\n"
            "set_age(-1)   # ValueError: age must be non-negative\n"
            "```\n\n"
            "Re-raise after logging:\n\n"
            "```python\n"
            "try:\n"
            "    risky_operation()\n"
            "except IOError as exc:\n"
            "    log.error('disk error: %s', exc)\n"
            "    raise   # propagate to caller after recording\n"
            "```\n\n"
            "**Why specific types like `ValueError`?** Callers can catch exactly what they "
            "expect. A bare `except:` catches everything — including `KeyboardInterrupt` "
            "and bugs you did not intend to hide.\n\n"
            "Chain exceptions with context:\n\n"
            "```python\n"
            "try:\n"
            "    parse(data)\n"
            "except ParseError as exc:\n"
            "    raise ValueError('bad user payload') from exc\n"
            "```\n\n"
            "**Why `from exc`?** The traceback shows both the original cause and your "
            "higher-level message — invaluable when debugging layered systems.\n\n"
            "## EAFP vs LBYL\n\n"
            "**EAFP** (Easier to Ask Forgiveness than Permission) — try, then handle:\n\n"
            "```python\n"
            "try:\n"
            "    value = config['timeout']\n"
            "except KeyError:\n"
            "    value = 30  # default\n"
            "```\n\n"
            "**LBYL** (Look Before You Leap) — check first:\n\n"
            "```python\n"
            "if 'timeout' in config:\n"
            "    value = config['timeout']\n"
            "else:\n"
            "    value = 30\n"
            "```\n\n"
            "Convert with EAFP when failure is rare:\n\n"
            "```python\n"
            "def to_int(text):\n"
            "    try:\n"
            "        return int(text)\n"
            "    except ValueError:\n"
            "        return None\n"
            "```\n\n"
            "**Why EAFP is Pythonic?** It avoids race conditions in concurrent code and "
            "keeps the happy path unindented. Use LBYL when the check is cheap and the "
            "exception path is common.\n\n"
            "## Context managers\n\n"
            "Files must be closed even when reads fail:\n\n"
            "```python\n"
            "with open('data.txt') as f:\n"
            "    content = f.read()\n"
            "# file closed automatically, even if read() raised an error\n"
            "```\n\n"
            "**Why `with`?** Without it you need `try/finally` around every `open()`:\n\n"
            "```python\n"
            "f = open('data.txt')\n"
            "try:\n"
            "    content = f.read()\n"
            "finally:\n"
            "    f.close()\n"
            "```\n\n"
            "The context manager protocol (`__enter__` / `__exit__`) handles that boilerplate.\n\n"
            "Multiple resources in one statement:\n\n"
            "```python\n"
            "with open('in.txt') as src, open('out.txt', 'w') as dst:\n"
            "    dst.write(src.read())\n"
            "# both files closed when block ends\n"
            "```\n\n"
            "## Worked example: timer context manager\n\n"
            "```python\n"
            "import time\n"
            "from contextlib import contextmanager\n\n"
            "@contextmanager\n"
            "def timer(label):\n"
            "    start = time.perf_counter()\n"
            "    yield                    # body of `with` block runs here\n"
            "    elapsed = time.perf_counter() - start\n"
            "    print(f'{label}: {elapsed:.4f}s')\n"
            "```\n\n"
            "**Usage:**\n\n"
            "```python\n"
            "with timer('sort'):\n"
            "    sorted(range(100000, 0, -1))\n"
            "# prints something like: sort: 0.0234s\n"
            "```\n\n"
            "**How it works:**\n\n"
            "1. Code before `yield` runs on entry (`__enter__`)\n"
            "2. Your `with` block body executes at `yield`\n"
            "3. Code after `yield` runs on exit (`__exit__`), even if the block raised\n\n"
            "If the block raises, the exception propagates after the cleanup code unless "
            "you suppress it in `__exit__`.\n\n"
            "## Class-based context manager\n\n"
            "```python\n"
            "class Timer:\n"
            "    def __init__(self, label):\n"
            "        self.label = label\n\n"
            "    def __enter__(self):\n"
            "        self.start = time.perf_counter()\n"
            "        return self\n\n"
            "    def __exit__(self, exc_type, exc_val, exc_tb):\n"
            "        elapsed = time.perf_counter() - self.start\n"
            "        print(f'{self.label}: {elapsed:.4f}s')\n"
            "        return False  # do not suppress exceptions\n"
            "```\n\n"
            "**Usage:**\n\n"
            "```python\n"
            "with Timer('work') as t:\n"
            "    do_something()\n"
            "# work: 0.0012s\n"
            "```\n\n"
            "**Why two styles?** `@contextmanager` is concise for simple setup/teardown. "
            "A class is clearer when you need state, multiple methods, or reusable instances.\n\n"
            "## Worked example: suppressing known errors\n\n"
            "```python\n"
            "from contextlib import suppress\n\n"
            "with suppress(FileNotFoundError):\n"
            "    os.remove('temp.cache')\n"
            "# no crash if file already gone\n"
            "```\n\n"
            "**Why `suppress`?** Cleaner than an empty `except` block when you genuinely "
            "expect and ignore a specific failure.\n\n"
            "## Common pitfalls\n\n"
            "- Swallowing exceptions with `pass` — at least log what went wrong\n"
            "- Catching `Exception` too broadly and hiding bugs\n"
            "- `return` in `finally` overrides other returns (avoid returning from `finally`)\n"
            "- Catching the wrong type — `except KeyError` will not catch `ValueError`\n"
            "- Opening files without `with` and forgetting `close()` on error paths\n\n"
            "```python\n"
            "# Too broad — hides bugs\n"
            "try:\n"
            "    process()\n"
            "except Exception:\n"
            "    pass\n\n"
            "# Better — catch what you expect\n"
            "try:\n"
            "    process()\n"
            "except (ValueError, KeyError) as exc:\n"
            "    log.warning('expected issue: %s', exc)\n"
            "```\n\n"
            "## Practice\n\n"
            "Build a timer context manager that prints elapsed seconds.\n\n"
            "```python\n"
            "with timer('work'):\n"
            "    do_something()\n"
            "# work: 0.0012s\n"
            "```\n\n"
            "## Summary\n\n"
            "Handle errors at boundaries with specific exception types; use `with` for "
            "resource lifecycle (files, locks, connections, timers); let unexpected bugs "
            "propagate with clear stack traces rather than silencing them."
        ),
    },
]
