"""Tkinter track lesson guides."""

LESSONS = [
    {
        "slug": "01_tkinter_intro",
        "track": "tkinter",
        "difficulty": "easy",
        "title": "Tkinter Without a Window",
        "tags": ["tkinter"],
        "exercise": "content/problems/tkinter/easy/02_grid_layout.py",
        "body": (
            "# Tkinter Without a Window\n\n"
            "## Overview\n\n"
            "Tkinter is Python's built-in GUI toolkit. You create a window, place "
            "widgets (labels, buttons, text fields) inside it, and run an event loop "
            "that waits for clicks and keystrokes.\n\n"
            "Real-world uses:\n\n"
            "- Small desktop utilities (file renamers, config editors)\n"
            "- Internal tools where a web app is overkill\n"
            "- Prototyping UI layouts before moving to a richer framework\n"
            "- Teaching GUI concepts without extra dependencies\n\n"
            "On many Linux systems you need the Tk package installed first "
            "(e.g. `pacman -S python-tk` on Arch). On Windows and macOS it usually "
            "ships with Python.\n\n"
            "**Headless exercises:** pyPracLab tests layout and validation as plain "
            "Python data (dicts, lists) so CI runs without a display server. You learn "
            "the *rules* of grid and pack first; opening a real window comes later.\n\n"
            "## Minimal window app\n\n"
            "Every Tkinter program follows the same skeleton:\n\n"
            "```python\n"
            "import tkinter as tk\n\n"
            "root = tk.Tk()                    # 1. create the main window\n"
            "root.title('My App')              # 2. configure it\n"
            "label = tk.Label(root, text='Hello')\n"
            "label.pack()                      # 3. place widgets\n"
            "root.mainloop()                   # 4. start the event loop\n"
            "```\n\n"
            "`mainloop()` blocks until the user closes the window. While it runs, "
            "Tkinter listens for events (button clicks, key presses, window resize) "
            "and redraws widgets as needed.\n\n"
            "Run locally to see it:\n\n"
            "```bash\n"
            "python my_app.py\n"
            "```\n\n"
            "## Widget hierarchy\n\n"
            "Every widget has exactly one **parent**. The root window is the top-level "
            "parent; frames group child widgets inside it.\n\n"
            "```\n"
            "Tk (root)\n"
            " └── Frame (form area)\n"
            "      ├── Label  ('Email:')\n"
            "      ├── Entry  (text input)\n"
            "      └── Button ('Submit')\n"
            "```\n\n"
            "Common widgets:\n\n"
            "| Widget   | Purpose                          |\n"
            "|----------|----------------------------------|\n"
            "| `Label`  | Static text or image             |\n"
            "| `Button` | Clickable action                 |\n"
            "| `Entry`  | Single-line text input           |\n"
            "| `Text`   | Multi-line editable area         |\n"
            "| `Frame`  | Invisible container for grouping |\n"
            "| `Checkbutton` | On/off toggle             |\n"
            "| `Radiobutton` | Pick one of several options |\n\n"
            "**Worked example:** a login form in real Tkinter:\n\n"
            "```python\n"
            "import tkinter as tk\n\n"
            "root = tk.Tk()\n"
            "root.title('Login')\n\n"
            "tk.Label(root, text='Username:').grid(row=0, column=0, sticky='e', padx=5)\n"
            "username = tk.Entry(root)\n"
            "username.grid(row=0, column=1, sticky='ew', padx=5)\n\n"
            "tk.Label(root, text='Password:').grid(row=1, column=0, sticky='e', padx=5)\n"
            "password = tk.Entry(root, show='*')\n"
            "password.grid(row=1, column=1, sticky='ew', padx=5)\n\n"
            "tk.Button(root, text='Sign in').grid(row=2, column=0, columnspan=2, pady=8)\n"
            "root.columnconfigure(1, weight=1)  # entry column stretches on resize\n"
            "root.mainloop()\n"
            "```\n\n"
            "## Geometry managers\n\n"
            "Layout managers decide *where* widgets go inside their parent:\n\n"
            "| Manager | Mental model                    | Best for                    |\n"
            "|---------|---------------------------------|-----------------------------|\n"
            "| `pack`  | Stack widgets along a side      | Toolbars, simple vertical lists |\n"
            "| `grid`  | Spreadsheet rows and columns    | Forms, calculators, tables  |\n"
            "| `place` | Absolute x/y coordinates        | Rare — custom overlays      |\n\n"
            "**Golden rule:** pick one manager per parent container. Do not call both "
            "`pack()` and `grid()` on widgets that share the same parent — Tkinter "
            "will raise an error or behave unpredictably.\n\n"
            "Complex UIs nest frames: pack regions (header, body, footer), then grid "
            "inside each frame.\n\n"
            "## Grid layout as data (headless pattern)\n\n"
            "Instead of calling `.grid()` in tests, build a list of placement specs "
            "and validate them in pure Python:\n\n"
            "```python\n"
            "def plan(specs: list[tuple[str, int, int]]) -> list[dict]:\n"
            "    \"\"\"Turn (name, row, col) tuples into grid() keyword dicts.\"\"\"\n"
            "    return [\n"
            "        {'widget': name, 'row': row, 'col': col, 'sticky': 'ew'}\n"
            "        for name, row, col in specs\n"
            "    ]\n\n"
            "layout = plan([('email_label', 0, 0), ('email_entry', 0, 1)])\n"
            "# [{'widget': 'email_label', 'row': 0, 'col': 0, 'sticky': 'ew'}, ...]\n"
            "```\n\n"
            "Then apply the specs when you actually build the GUI:\n\n"
            "```python\n"
            "widgets = {'email_label': tk.Label(frame, text='Email:'),\n"
            "           'email_entry': tk.Entry(frame)}\n"
            "for spec in plan([('email_label', 0, 0), ('email_entry', 0, 1)]):\n"
            "    w = widgets.pop(spec['widget'])\n"
            "    w.grid(row=spec['row'], column=spec['col'], sticky=spec['sticky'])\n"
            "```\n\n"
            "Separating **layout planning** from **widget creation** makes both testable "
            "without a display.\n\n"
            "## sticky and column weight\n\n"
            "`sticky` tells a widget which edges of its grid cell to stick to:\n\n"
            "```python\n"
            "# 'ew' = east + west → stretch horizontally\n"
            "entry.grid(row=0, column=1, sticky='ew')\n\n"
            "# 'nsew' = fill the entire cell\n"
            "text_area.grid(row=1, column=0, columnspan=2, sticky='nsew')\n"
            "```\n\n"
            "Without `columnconfigure(..., weight=1)`, sticky has nothing to stretch "
            "into — the entry stays narrow when the window grows.\n\n"
            "```python\n"
            "parent.columnconfigure(1, weight=1)  # column 1 absorbs extra width\n"
            "parent.rowconfigure(1, weight=1)     # row 1 absorbs extra height\n"
            "```\n\n"
            "## Variables and widget state\n\n"
            "Tkinter `Variable` objects sync widget state with Python:\n\n"
            "```python\n"
            "name_var = tk.StringVar(value='Ada')\n"
            "entry = tk.Entry(root, textvariable=name_var)\n"
            "print(name_var.get())   # read current text\n"
            "name_var.set('Grace')   # update entry from code\n"
            "```\n\n"
            "Useful for validation exercises: check `name_var.get()` before enabling "
            "a submit button.\n\n"
            "## Detecting layout conflicts\n\n"
            "Two widgets cannot occupy the same `(row, column)` in one parent:\n\n"
            "```python\n"
            "def find_grid_collisions(specs: list[dict]) -> list[tuple[int, int]]:\n"
            "    seen: set[tuple[int, int]] = set()\n"
            "    collisions = []\n"
            "    for spec in specs:\n"
            "        cell = (spec['row'], spec['col'])\n"
            "        if cell in seen:\n"
            "            collisions.append(cell)\n"
            "        seen.add(cell)\n"
            "    return collisions\n"
            "```\n\n"
            "Run this on your planned layout before building widgets.\n\n"
            "## Real-world scenario: settings dialog\n\n"
            "A typical settings panel uses grid for labeled fields:\n\n"
            "```python\n"
            "FIELDS = [\n"
            "    ('Host', 0), ('Port', 1), ('Timeout (s)', 2),\n"
            "]\n\n"
            "def build_settings_specs() -> list[dict]:\n"
            "    specs = []\n"
            "    for label, row in FIELDS:\n"
            "        specs.append({'widget': f'{label}_label', 'row': row, 'col': 0, 'sticky': 'e'})\n"
            "        specs.append({'widget': f'{label}_entry', 'row': row, 'col': 1, 'sticky': 'ew'})\n"
            "    return specs\n"
            "```\n\n"
            "Labels right-aligned (`sticky='e'`), entries stretch (`sticky='ew'`).\n\n"
            "## Common pitfalls\n\n"
            "- Missing `python-tk` package on Linux → `ModuleNotFoundError: tkinter`\n"
            "- Mixing `pack` and `grid` in the same parent frame\n"
            "- Forgetting `columnconfigure` weight — entries do not grow on resize\n"
            "- Updating widgets from background threads — use `root.after(0, callback)` "
            "to schedule UI changes on the main thread\n"
            "- Calling `mainloop()` in unit tests — blocks forever; test layout data instead\n\n"
            "## Practice\n\n"
            "Compute grid positions for a form layout from a spec list.\n\n"
            "## Summary\n\n"
            "Tkinter = widgets + layout managers + event loop. Use `grid` for forms, "
            "`pack` for stacked regions, and separate layout specs from widget creation "
            "so you can validate layouts headlessly in CI."
        ),
    },
    {
        "slug": "02_layout_managers",
        "track": "tkinter",
        "difficulty": "easy",
        "title": "Grid and Pack Layout",
        "tags": ["tkinter", "layout"],
        "exercise": "content/problems/tkinter/easy/05_pack_specs.py",
        "body": (
            "# Grid and Pack Layout\n\n"
            "## Overview\n\n"
            "Layout managers position widgets inside their parent. **grid** suits forms "
            "and calculators; **pack** suits toolbars and simple vertical stacks. "
            "Most real apps combine both by nesting `Frame` widgets.\n\n"
            "Real-world uses:\n\n"
            "- Email client: pack toolbar top, pack status bar bottom, grid message list\n"
            "- Calculator: grid for the button pad, pack for the display\n"
            "- IDE-style app: pack sidebar + main area, grid tabs inside main area\n\n"
            "## grid in detail\n\n"
            "Each widget gets a `(row, column)` address. Rows and columns start at 0.\n\n"
            "```python\n"
            "label.grid(row=0, column=0, sticky='e', padx=5, pady=2)\n"
            "entry.grid(row=0, column=1, sticky='we', padx=5)\n"
            "button.grid(row=1, column=0, columnspan=2, pady=8)\n"
            "```\n\n"
            "Key options:\n\n"
            "| Option       | Meaning                                      |\n"
            "|--------------|----------------------------------------------|\n"
            "| `row`, `column` | Cell address (0-based)                    |\n"
            "| `sticky`     | Anchor within cell: `n`, `s`, `e`, `w` or combos |\n"
            "| `padx`, `pady` | External padding (pixels)                |\n"
            "| `columnspan` | Widget spans multiple columns                |\n"
            "| `rowspan`    | Widget spans multiple rows                   |\n\n"
            "**sticky cheat sheet:**\n\n"
            "```\n"
            "  n\n"
            "w + e   (ew = stretch horizontally)\n"
            "  s\n"
            "nsew    (fill entire cell)\n"
            "```\n\n"
            "**Worked example:** calculator button pad:\n\n"
            "```python\n"
            "BUTTONS = [\n"
            "    ('7', 0, 0), ('8', 0, 1), ('9', 0, 2),\n"
            "    ('4', 1, 0), ('5', 1, 1), ('6', 1, 2),\n"
            "    ('1', 2, 0), ('2', 2, 1), ('3', 2, 2),\n"
            "    ('0', 3, 0), ('.', 3, 1), ('=', 3, 2),\n"
            "]\n\n"
            "def button_grid_specs() -> list[dict]:\n"
            "    return [\n"
            "        {'widget': label, 'row': r, 'col': c, 'sticky': 'nsew'}\n"
            "        for label, r, c in BUTTONS\n"
            "    ]\n"
            "```\n\n"
            "Make every column and row equal width with weights:\n\n"
            "```python\n"
            "for col in range(3):\n"
            "    parent.columnconfigure(col, weight=1, uniform='btn')\n"
            "for row in range(4):\n"
            "    parent.rowconfigure(row, weight=1, uniform='btn')\n"
            "```\n\n"
            "## Configuring stretch\n\n"
            "Without `weight`, extra window space stays empty:\n\n"
            "```python\n"
            "parent.columnconfigure(1, weight=1)  # column 1 expands horizontally\n"
            "parent.rowconfigure(0, weight=1)   # row 0 expands vertically\n"
            "entry.grid(row=0, column=1, sticky='nsew')  # entry fills growing cell\n"
            "```\n\n"
            "Use `uniform='group'` when multiple columns should share space equally "
            "(calculator buttons, equal-width form columns).\n\n"
            "## pack in detail\n\n"
            "Pack stacks widgets along one side of the parent. **Order matters** — "
            "the first widget packed gets priority along that side.\n\n"
            "```python\n"
            "toolbar.pack(side='top', fill='x')       # full-width bar at top\n"
            "content.pack(expand=True, fill='both')   # middle grows\n"
            "status.pack(side='bottom', fill='x')     # full-width bar at bottom\n"
            "```\n\n"
            "| Option    | Meaning                                           |\n"
            "|-----------|---------------------------------------------------|\n"
            "| `side`    | `top`, `bottom`, `left`, `right`                  |\n"
            "| `fill`    | `x`, `y`, or `both` — stretch to fill parent axis |\n"
            "| `expand`  | Widget gets extra space when window grows         |\n"
            "| `padx/pady` | External padding                              |\n\n"
            "**Worked example:** pack specs as data (matches the exercise pattern):\n\n"
            "```python\n"
            "def pack_specs(items: list[tuple[str, str]]) -> list[dict]:\n"
            "    \"\"\"Convert (widget_name, side) to pack() keyword dicts.\"\"\"\n"
            "    return [\n"
            "        {'widget': widget, 'side': side, 'fill': 'x'}\n"
            "        for widget, side in items\n"
            "    ]\n\n"
            "specs = pack_specs([('toolbar', 'top'), ('status', 'bottom')])\n"
            "# [{'widget': 'toolbar', 'side': 'top', 'fill': 'x'},\n"
            "#  {'widget': 'status', 'side': 'bottom', 'fill': 'x'}]\n"
            "```\n\n"
            "Apply specs to real widgets:\n\n"
            "```python\n"
            "widgets = {'toolbar': toolbar_frame, 'status': status_label}\n"
            "for spec in pack_specs([('toolbar', 'top'), ('status', 'bottom')]):\n"
            "    widgets[spec['widget']].pack(side=spec['side'], fill=spec['fill'])\n"
            "```\n\n"
            "## Pack order and priority\n\n"
            "Packing `top` then `bottom` reserves space from both edges inward:\n\n"
            "```\n"
            "┌─────────────────────┐\n"
            "│ toolbar  (top)      │\n"
            "├─────────────────────┤\n"
            "│                     │\n"
            "│ content (expand)    │\n"
            "│                     │\n"
            "├─────────────────────┤\n"
            "│ status   (bottom)   │\n"
            "└─────────────────────┘\n"
            "```\n\n"
            "If you pack `bottom` first, then `top`, the visual result is the same — "
            "but packing `content` last with `expand=True` ensures it fills the middle.\n\n"
            "```python\n"
            "def pack_order(specs: list[dict]) -> list[str]:\n"
            "    \"\"\"Return widget names in recommended pack sequence.\"\"\"\n"
            "    priority = {'top': 0, 'bottom': 1, 'left': 2, 'right': 3}\n"
            "    return [s['widget'] for s in sorted(specs, key=lambda s: priority[s['side']])]\n"
            "```\n\n"
            "## Nesting frames: the professional pattern\n\n"
            "Combine pack regions with grid forms inside each region:\n\n"
            "```python\n"
            "root = tk.Tk()\n\n"
            "toolbar = tk.Frame(root)\n"
            "toolbar.pack(side='top', fill='x')\n"
            "tk.Button(toolbar, text='Open').pack(side='left', padx=4)\n"
            "tk.Button(toolbar, text='Save').pack(side='left', padx=4)\n\n"
            "form = tk.Frame(root)\n"
            "form.pack(expand=True, fill='both', padx=10, pady=10)\n"
            "tk.Label(form, text='Name:').grid(row=0, column=0, sticky='e')\n"
            "tk.Entry(form).grid(row=0, column=1, sticky='ew')\n"
            "form.columnconfigure(1, weight=1)\n\n"
            "status = tk.Label(root, text='Ready', anchor='w')\n"
            "status.pack(side='bottom', fill='x')\n"
            "root.mainloop()\n"
            "```\n\n"
            "Each frame is its own layout island — pack inside the root, grid inside "
            "the form frame.\n\n"
            "## Choosing grid vs pack\n\n"
            "| Scenario                    | Manager | Why                          |\n"
            "|-----------------------------|---------|------------------------------|\n"
            "| Labeled input form          | grid    | aligned columns and rows     |\n"
            "| Toolbar with buttons        | pack    | horizontal strip             |\n"
            "| Log output below controls   | pack    | top controls, bottom log     |\n"
            "| Keyboard / calculator pad   | grid    | uniform button grid          |\n"
            "| Sidebar + main content      | pack    | left sidebar, right body     |\n\n"
            "## Validation without GUI\n\n"
            "Exercises test pure functions on layout specs:\n\n"
            "```python\n"
            "def validate_grid(specs: list[dict]) -> bool:\n"
            "    cells = [(s['row'], s['col']) for s in specs]\n"
            "    return len(cells) == len(set(cells))  # no duplicate cells\n\n"
            "def validate_pack_sides(specs: list[dict]) -> bool:\n"
            "    allowed = {'top', 'bottom', 'left', 'right'}\n"
            "    return all(s['side'] in allowed for s in specs)\n"
            "```\n\n"
            "Detect grid collisions (two widgets same row/column), verify pack sides "
            "are valid, and confirm sticky values use only `n`, `s`, `e`, `w`.\n\n"
            "## Real-world scenario: three-pane editor\n\n"
            "```python\n"
            "def editor_layout() -> dict:\n"
            "    return {\n"
            "        'pack': [\n"
            "            {'widget': 'menu_bar', 'side': 'top', 'fill': 'x'},\n"
            "            {'widget': 'main_pane', 'side': 'top', 'fill': 'both', 'expand': True},\n"
            "            {'widget': 'status_bar', 'side': 'bottom', 'fill': 'x'},\n"
            "        ],\n"
            "        'grid_inside_main': [\n"
            "            {'widget': 'file_tree', 'row': 0, 'col': 0, 'sticky': 'ns'},\n"
            "            {'widget': 'editor', 'row': 0, 'col': 1, 'sticky': 'nsew'},\n"
            "        ],\n"
            "    }\n"
            "```\n\n"
            "Pack the outer shell; grid the inner split. Column 1 gets `weight=1` so "
            "the editor expands.\n\n"
            "## Common pitfalls\n\n"
            "- Forgetting `sticky='we'` on `Entry` — field stays tiny when window grows\n"
            "- `grid` without `columnconfigure` — labels clip on resize\n"
            "- Duplicate `(row, column)` assignments — second widget hides the first\n"
            "- Packing `content` before `toolbar` without `expand` — middle does not fill\n"
            "- Using `place` for entire layouts — hard to maintain; prefer grid/pack\n\n"
            "## Practice\n\n"
            "Determine correct pack order for top/content/bottom regions.\n\n"
            "## Summary\n\n"
            "grid = 2D coordinates + sticky + weight. pack = side + fill + expand. "
            "Nest frames to combine both in complex UIs. Express layouts as testable "
            "spec dicts, then apply them when building real widgets."
        ),
    },
]
